### ISSUE TITLE
elasticsearch 2.0 support

### ISSUE THREAD

**Issue by nsiitk** [strapdata/elassandra#1]
How to test elassandra with elasticsearch 2.0. Is the project need a lot of rewrite?

**Comment by vroyer** [comment]
Hi Nitin,
I am currently working to upgrade to elasticsearch 2.1 by merging modifications on roughly 200 files. It should be available in 2 or 3 weeks.
Regards.
Vincent.

**Comment by nsiitk** [comment]
Hi Vincent is there any update on the merging. Can I help in any way?

**Comment by vroyer** [comment]
Hi Nitin, 
I just release a Elassandra 2.1.1-rc1 based on ES 2.1.1+C\* 2.2.4. it works with kibana 4.1.3+
Let me know it you face any issue.

**Comment by nsiitk** [comment]
Hi Vincent,
 I am not able to build. I have changed cassandra version 2.2.1-SNAPSHOT to 2.2.1 as maven was not able to identify. I got failed with "Failed to execute goal de.thetaphi:forbiddenapis:2.0:check (check-forbidden-apis) on project elassandra: Check for forbidden API calls failed"
I checked elasticsearch and found they have same issue but they have shifted to gradle from maven
https://github.com/elastic/elasticsearch/issues/14412.

**Comment by vroyer** [comment]
Yes, ES has just shift to gradle in 2.2, but i elassandra is fork from 2.1. Look at the elasticsearch parent project, in the pom.xml, comment the plugin forbidden api or add excludes for org.apache.cassandra and org.elasticsearch.cassandra. Do the same for licence header check.

You also should update the Cassandra dependency to version 2.2.1, and report the modifications i have done to Cassandra into your Cassandra 2.2.1 source code (very few lines to add function hooks).

**Comment by nsiitk** [comment]
build is done but I am not sure why do I need  -Dcassandra.home=<path/to/cassandra> in build command. does it required to first install cassandra and then set cassandra.home to elassandra path?

**Comment by nsiitk** [comment]
running failed due to main folder not available int install directory.
I found this in conf/cassandra-env.ps1
Add build/classes/main so it works in development

do I need to run this sh file or can just comment the classpath entry of main.

**Comment by nsiitk** [comment]
sorry issue was in bin/cassandra.in.sh commented the line. 
but again it fails Caused by: java.lang.IllegalStateException: Classpath should not contain empty elements!

**Comment by nsiitk** [comment]
edited cassandra.in.sh to fix these issue but now it looks for jsr223 in libs which is not present in tar file extraction. Do we need to install cassandra also as I can see the folder there.  then comes the confusion that cassandra home need to be set to elssandra or cassandra

**Comment by vroyer** [comment]
You should set CASSANDRA_HOME=your_elassandra_install_directory (elassandra is an enhanced version of cassandra).

The cassandra.in.sh try to load in your classpath unnecessary jars located in <your_elassandra_install_directory>/lib/jsr223. Create an empty lib/jsr223 directory or comment this part in your cassandra.in.sh .

**Comment by vroyer** [comment]
To avoid empty CLASSPATH elements and JarHell errors, please comment these lines in your cassandra.in.sh :
#cassandra_bin="$CASSANDRA_HOME/build/classes/main"
#cassandra_bin="$cassandra_bin:$CASSANDRA_HOME/build/classes/thrift"

#CLASSPATH="$CASSANDRA_CONF:$cassandra_bin"

#JSR223 - collect all JSR223 engines' jars
#for jsr223jar in "$CASSANDRA_HOME"/lib/jsr223/_/_.jar; do
#CLASSPATH="$CLASSPATH:$jsr223jar"
#done
