### ISSUE TITLE
New Packages

### ISSUE THREAD

**Issue by lmangani** [strapdata/elassandra#1]
First of all, thanks for pushing the latest version with 2.4 - Excited to test it out!
Is there a timeline for the release of new deb/rpm packages with the latest bundle?

Thanks in advance!

**Comment by vroyer** [comment]
Hi,
Yes, I’m currently fighting with maven to publish on maven central, compile with travis and generates packaging, but yes, deb and rpm are coming soon.
Be careful, this release is very fresh, bulk operation is not yet running.
Thanks.

**Comment by lmangani** [comment]
@vroyer thanks for the heads up and looking forward to the package! My insert setup is almost entirely bulk based, but I'll do some general testing to wire Kibi/Kibana and our alerting plugin for a ride. Is there a (generic) idea when bulk would be included, or anything the community can help with at this stage?

**Comment by vroyer** [comment]
Bulk should be available next week, i let you know.
You can use kibana 4.6.3 (no more source code change now).

**Comment by vroyer** [comment]
You can use https://github.com/vroyer/cqlinject <https://github.com/vroyer/cqlinject> to load your data, it convert JSON bulk files to CQL INSERT, this is fault tolerant and faster….
Cheers.
Vincent.

**Comment by lmangani** [comment]
@vroyer going to give it a shot - would bulk data be indexed and consumable in ES queries directly this way or would mapping be required?

**Comment by lmangani** [comment]
Elassandra 2.4.2 runs with latest zip builds, closing this issue as we're able to test and will open some more detailed ones next :)
Thanks for the great work @vroyer
