### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by yanelev** [strapdata/elassandra#10]
Hi,

The tool looks promising indeed, Tried to follow the install process but it isn't that clear unfortunately. I am using Ubuntu 14.04. 
I have already installed elastic and cassandra  and it works. 
But when I try to add the elassandra it doesn't combine them together.
Is there a detailed procedure for your installation?

Regards

**Comment by sergiomr88** [comment]
What is the problem exactly?

I was able to get the latest release running without installing Cassandra. As far as my understanding goes, elassandra is your cassandra database. It just has the elastic search stuff included. That being said, I'm currently using release 2.1.1 and to get it working I did install datastax's cassandra first.

**Comment by yanelev** [comment]
Thanks for the reply.

Here is one of the steps

Trying to install the cqlsh: (missing a file or something ..)

sanny@vm1:/home/elassandra# python pylib/setup.py
python: can't open file 'pylib/setup.py': [Errno 2] No such file or directory

**Comment by yanelev** [comment]
And another problem 

sanny@vm1:/home/elassandra/bin# cqlsh
Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 152, in <module>
    from cqlshlib import cql3handling, cqlhandling, pylexotron, sslhandling
ImportError: cannot import name sslhandling

**Comment by sergiomr88** [comment]
For cqlsh, I installed it with pip. After that you should have cqlsh, cqlshlib and cqlsh.py in /usr/bin/. 
Additionally, to use cqlsh you need to use Python 2.7. I don't know about Ubuntu, but Red Hat comes with Python 2.6 out of the box.

**Comment by yanelev** [comment]
Yes I do have it.
/usr/lib/pymodules/python2.7/cqlshlib#
But still when I try to run it I get the same error. Also install with pip install cqlsh.

sanny@vm1:/home/elassandra/bin# cqlsh
Traceback (most recent call last):
File "/usr/bin/cqlsh.py", line 152, in 
from cqlshlib import cql3handling, cqlhandling, pylexotron, sslhandling
ImportError: cannot import name sslhandling

**Comment by sergiomr88** [comment]
Have you also installed zlib-devel and openssl-devel?

**Comment by yanelev** [comment]
Nope , I assume I should. Is it specified somewhere ?

**Comment by yanelev** [comment]
Sorry already there .... my mistake

**Comment by vroyer** [comment]
cqlsh in elassandra (and cassandra 2.2+) require python 2.7. With redhat 6.x, install Software Collection from Redhat, then run the following command to overload python27 in your bash.
#scl enable python27 bash

Then install the cassandra driver (pip install cassandra-driver).

**Comment by yanelev** [comment]
Thank you for your reply.
So Ubuntu will not work?

**Comment by vroyer** [comment]
Yes, as soon as you apply elasticsearch 2.1.1 and cassandra 2.2.x requirements, it should work on Ubuntu.

**Comment by ChrisFeldmeier** [comment]
It should work on ubuntu I use it on debian ;-)

**Comment by yanelev** [comment]
I am really fighting with this installation, can someone please send out one step install. I really missing something: 
option 1; from source git clone the repo from github.
option 2: tarball repository but the link is 404.

What is the correct way?

Can you write some simple install process?

**Comment by sergiomr88** [comment]
The tarball can be found on https://github.com/vroyer/elassandra/releases 
If the setup of the machine is correct, just untar the downloaded tarball, edit your cassandra.yaml file, and then start up cassandra.

**Comment by chevalier2k** [comment]
I am trying to install this and am kind of lost. Can someone clarify that i have to have elasticsearch and cassandra installed before i install elassandra. I am trying to install it on centos 7. So also if someone can confirm that it should work on it.

**Comment by vroyer** [comment]
Hi,
Just install the elassandra tarball, it includes cassandra 2.2.5 and elasticsearch 2.1.1.
Yes, it works on redhat and it should work on centos.
Regards,
Vincent.

**Comment by chevalier2k** [comment]
Hi Vincent,

Is there a gracefull way to starting and stopping elassandra. By the way i did get it to work. Also when i start kibana after reboot, elasticsearch complains that index already exists.

Thanks
Vivek

**Comment by vroyer** [comment]
Hi Vivek,

Cassandra stop/start are documented there https://docs.datastax.com/en/cassandra/2.0/cassandra/reference/referenceStartStopTOC.html

Cassandra include a shutdown hook, a dedicated thread to finish ongoing writes regardless of the way you stop it (kill, nodetool stopdaemon, etc...).
In Elassandra, elasticsearch write requests are transformed to CQL writes managed by cassandra.
When elassandra restart, cassandra first replay commit logs and re-index your document.

In order to restart faster, you can flush cassandra before stopping (nodetool flush), but there is nothing special to makes gracefull stop/start. 

Regards,
Vincent.
