### ISSUE TITLE
Elassandra - Benchmarks with Spark Streaming / Kafka

### ISSUE THREAD

**Issue by boycode** [strapdata/elassandra#100]
Hi all,

Do we have any benchmarks results for data load from spark stream to elassandra  , and elasandra's benchmarks on creating secondary index from Cassandra.

Also pushing the data to elassandra - which one is best  REST or CQL ? Do we have any result comparison for that as well . 

Playing with Elassandra a lot . Much Interested to explore all the capabilities .

Can you any body help on this ?

Thanks,
Boycode

**Comment by DBarthe** [comment]
Hi @boycode,

In our benchmarks, indexing is faster on Elassandra than Elasticsearch 2.4.

Also, when you want push a lot of data, CQL should be faster.

I never used spark stream. We would appreciate feedbacks about using spark along elassandra. Do you know we made a modified [es-hadoop connector](https://github.com/strapdata/elasticsearch-hadoop) for elassandra ?

**Comment by boycode** [comment]
Hi @DBarthe ,

Thanks for your valuable feed backs. I will also try to publish the benchmarks on these R&D topics.

We tried  es-hadoop connector some long time back - with Spark. In here , I am  planning for DStream.

Thanks,
Boycode

**Comment by vroyer** [comment]
The elaticsearch-hadoop connector for Elassandra 5.5.+ is now available at [https://github.com/strapdata/elasticsearch-hadoop](https://github.com/strapdata/elasticsearch-hadoop).  Thanks.

**Comment by vroyer** [comment]
See http://www.strapdata.com/2017/11/06/fast-spark-aggregation-elassandra/.
