### ISSUE TITLE
Cassandra - CQL based inserts are not automatically indexed in elastic search

### ISSUE THREAD

**Issue by boycode** [strapdata/elassandra#102]
Hi all ,

I am trying to insert the via  CQL - to Cassandra , but these tables are not indexed in Elastic Search. But if I push data via elastic search API . It is automatically get indexed.

In detail.

1. Created the Cassandra Table with Index , Partition and Secondary Indexes. - Clustering + Composite Primary Key via CQL
2. Inserted Records using CQL
3. This information not indexed in the elastic search.

Can anybody please help me here.

Thanks,
Vishnu

**Comment by vroyer** [comment]
Hi Vishnu,

Cassandra table are indexed only if there is a corresponding elasticsearch mapping. There is 2 way to define this mapping.
A. Create the mapping with the Elastisearch API (a « put mapping » or an « index » with the dynamic mapping enabled).
B. Discover the mapping from the CQL schema by using a specific discovery mapping, see http://doc.elassandra.io/en/latest/mapping.html#bidirectionnal-mapping <http://doc.elassandra.io/en/latest/mapping.html#bidirectionnal-mapping>.

A soon as you have this mapping, your data will be indexed in elasticsearch.

**Comment by boycode** [comment]
Thanks @vroyer .

I am about to try these options. I will update the progress.

Thanks,
Vishnu

**Comment by boycode** [comment]
Thanks @vroyer . It worked well 👍 

 1. Created Cassandra Table , with index.
2. Nodetools - rebuild index
3. With Elastic Search - updated  - Bidirectional Mapping

Thanks,
Vishnu

**Comment by boycode** [comment]
Hi all,

I have one more query .  what would be be best design for retrieval query on elassandra .

I created a composite primary key   id,date+category (Partition).  Basically for better retrieval on Cassandra model . Trying to see here which the best design which can work better for similar queries on top of elassandra

```
CREATE TABLE XX_keyspace_Feed.TableXX (id text,event_timestamp timestamp,event_date date,type text,Catg text, PRIMARY KEY((id,event_date),Catg))

CREATE INDEX ON XX_keyspace_Feed.TableXX (Catg);
```
while describing the cassandra table - it shown that  elassandra created a custom index .  but the fields are not indexed . Please see the below

`CREATE CUSTOM INDEX elastic_TableXX_idx ON XX_keyspace_Feed.TableXX () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';`

 So for creating a composite primary key with clustering/partition . Do we have any best practices ?

Thanks,
Vishnu

**Comment by boycode** [comment]
Hi all ,

So just wanted to see if I create a composite primary key - how would be elastic search is creating the index .

It is mentioned that  :_id is converted to the underlying primary key . 

But the same I tried with Elassandra , it is creating the index in cassandra , also the CURL options is also working but inserted data via is not indexed inside elastic search.

I also tried Kibana to see the index created - It is not creating _id field for composite keys

Thanks,
Vishnu

**Comment by vroyer** [comment]
Hi,

If you want to use a composite key :
1. Create your cassandra table with cqlsh
2. Use a discover mapping as explained here http://doc.elassandra.io/en/latest/mapping.html#bidirectionnal-mapping <http://doc.elassandra.io/en/latest/mapping.html#bidirectionnal-mapping> to create the associated index. 
Then, for data inserted in your C* table, the _id will be a string representation of the primary key columns.

Cheers,
Vincent.

**Comment by boycode** [comment]
Thanks Vincent .

But I missed a very important point there where the combination is Compound primary key and composite partition key . For Composite primary key with out partition it will work properly.


CREATE TABLE XX_keyspace_Feed.TableXX (id text,event_timestamp timestamp,event_date date,type text,Catg text, **PRIMARY KEY((id,event_date),Catg)**)

In here , **the value/data  against the partition key** is not coming under _id 

Thanks,
Vishnu

**Comment by vroyer** [comment]
Hi Vishnu,

I guess, this is because the CQL type « date »  is not  currently supported (see http://doc.elassandra.io/en/latest/mapping.html <http://doc.elassandra.io/en/latest/mapping.html>).
It should work with a timestamp for exemple.

Cheers,
Vincent.

**Comment by boycode** [comment]
Thanks Vincent . Closing this issue.
