### ISSUE TITLE
Unable to search all documents

### ISSUE THREAD

**Issue by writeaditya** [strapdata/elassandra#104]
Hi,

I'am new to ES or elassandra and trying to learn some basic concept but I'am stuck at one point. My issue is when I am viewing single document by this query http://192.168.4.8:9200/twitter/tweet/1?pretty=true . ES gives result as 

{
    "_index": "twitter",
    "_type": "tweet",
    "_id": "1",
    "_version": 1,
    "found": true,
    "_source": {
        "message": "This is a tweet!",
        "user": {
            "uid": "12345",
            "name": {
                "last_name": "Royer",
                "first_name": "Vincent"
            }
        }
    }
}

But when I'am trying to view all the records it gives total records as 0 -  

http://192.168.4.8:9200/twitter/tweet/_search?pretty=true

{
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}

Where I'am gong wrong please help...

**Comment by vroyer** [comment]
Hi,

It should work as shown bellow.
Do you issue an http GET request when searching ?
What is your elssandra version ?

$curl -XPUT "$NODE:9200/twitter/tweet/1" -d' {
"message": "This is a tweet!",
"user": {
"uid": "12345",
"name": {
"last_name": "Royer",
"first_name": "Vincent"
}}}'
{"_index":"twitter","_type":"tweet","_id":"1","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}

Then, you should get this when searching :
$ curl -XGET "$NODE:9200/twitter/tweet/_search?pretty"
{
  "took" : 46,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "twitter",
      "_type" : "tweet",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "message" : "This is a tweet!",
        "user" : {
          "uid" : "12345",
          "name" : {
            "last_name" : "Royer",
            "first_name" : "Vincent"
          }
        }
      }
    } ]
  }
}

Thanks,
Vincent.

**Comment by writeaditya** [comment]
Hi Vincent,

Still no result.
Yes I have issued GET command to get results
and I'am using 2.4.2 elassandra version

{
    "name": "192.168.4.8",
    "cluster_name": "TestCluster",
    "cluster_uuid": "1787a6cf-ad47-41e3-a12e-933e9222954c",
    "version": {
        "number": "2.4.2",
        "build_hash": "cfeba3780e2f027a15f5e4943d2903ca9201fbba",
        "build_timestamp": "2017-03-02T22:03:10Z",
        "build_snapshot": false,
        "lucene_version": "5.5.2"
    },
    "tagline": "You Know, for Search"
}

I'am not using curl to execute search query. Working on postman chrome integration

**Comment by vroyer** [comment]
Hi,

According to the build date, your are probably using the release 2.4.2-10 having a bug fixed in 2.4.2.11+ (bug #84 = only indexing in debug mode). Please upgrade to 2.4.2-13 or to the very last release 2.4.5.4).

Thanks,
Vincent.

Envoyé de mon iPhone

**Comment by writeaditya** [comment]
Hi Vincent,

It worked now , may be there was some issue with version. We can close this call . Thanks for your support.
