### ISSUE TITLE
Failed to search with Chinese words

### ISSUE THREAD

**Issue by dickhfchan** [strapdata/elassandra#109]
curl -XPUT 'http://localhost:9200/dazzle/photo/1' -H 'Content-Type: application/json' -d '{
   "gid (S)": "id1499933211078",
   "galleryType (S)": "photo",
   "status (S)": "可出售,免費下載",
   "clickRate (N)": 129,
   "desc (S)": "rr",
   "downloaded (N)": 1,
   "owner_id (S)": "freepik.dazzle.website",
   "price (N)": 0,
   "rating (N)": 5,
   "remark (S)": "-",
   "original_url (S)": "https://designerrrr-output.s3-ap-northeast-1.amazonaws.com/images/freepik.dazzle.website/original/id1499933211078.jpg",
   "category (S)": "相片",
   "original_name (S)": "43751-O3VHAY.jpg",
   "large_url (S)": "https://designerrrr-output.s3-ap-northeast-1.amazonaws.com/images/freepik.dazzle.website/large/id1499933211078.jpg",
   "mid_url (S)": "https://designerrrr-output.s3-ap-northeast-1.amazonaws.com/images/freepik.dazzle.website/medium/id1499933211078.jpg",
   "small_url (S)": "https://designerrrr-output.s3-ap-northeast-1.amazonaws.com/images/freepik.dazzle.website/small/id1499933211078.jpg",
   "tags (L)": "[  { \"S\" : \"插圖\" },  { \"S\" : \"矢量\" },  { \"S\" : \"符號\" },  { \"S\" : \"設計（裝飾）\" },  { \"S\" : \"模板\" },  { \"S\" : \"圖像\" },  { \"S\" : \"平\" },  { \"S\" : \"標簽\" },  { \"S\" : \"元素\" },  { \"S\" : \"企業\" },  { \"S\" : \"跡象\" },  { \"S\" : \"紙\" },  { \"S\" : \"橫幅\" },  { \"S\" : \"孤立\" },  { \"S\" : \"設計\" },  { \"S\" : \"後臺\" },  { \"S\" : \"遊戲卡片\" },  { \"S\" : \"孤立的\" }]",
   "JSONcheck (S)": "checked",
   "newVersion (S)": "new",
   "authorize (S)": "-"
 }'

The above it the original update data. 

root@ip-172-31-15-110:/home/ubuntu# curl -XGET 'http://localhost:9200/dazzle/_search' -H 'Content-Type: application/json' -d '{
>     "query": {
>         "term": {
>            "category (S)": {
>               "value": "相片"
>            }
>         }
>     }
> }'
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

Searched but got not result.

Hi All, 

I appreciate any help to solve this issue. By the way, I found there is the analysis-smartcn plugin, do I need to install it first? I have tried to install this plugin but failed. Is there any script and path I can follow? 

Regards,
Dick Chan

**Comment by vroyer** [comment]
Hi,
You probably had the following error when inserting your document because of your field names.

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Unexpected character ('S' (code 83)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.common.io.stream.InputStreamStreamInput@47a19ba2; line: 18, column: 20]"}},"status":400}

So, search returns no results….

**Comment by dickhfchan** [comment]
Hi vroyer ,

Thank for your reply. 

The insert was successful. I just got issue with the query where ES can search by a single Chinese word but multiple Chinese word. 

I found the solution with match instead of term. 

"query": {
    "match": {
      "tags (L)": "相片" 
    }
  }
}'

.
