### ISSUE TITLE
Include Cassandra and ES version

### ISSUE THREAD

**Issue by ChrisFeldmeier** [strapdata/elassandra#11]
Please include Cassandra Version in Elasticsearch Url (http://NODE:9200) for better information. Would be perfect :+1:

**Comment by vroyer** [comment]
Elasticsearch version remains 2.1.1 because there is a version check when installing plugins (for example, elasticsearch-sql expect version 2.1.1 or 2.1.2). So, a specific version number could block some plugin installation.
