### ISSUE TITLE
copy_to question

### ISSUE THREAD

**Issue by twoofy** [strapdata/elassandra#113]
Hello

I'm having trouble getting copy_to to work.

```
{
 "properties" : {  "title": { "type": "string", "index": "analyzed", "store" : "yes", "cql_collection": "singleton", "copy_to": "all" },
 "description": { "type": "string", "index": "analyzed", "store" : "yes", "cql_collection": "singleton", "copy_to": "all" },
 "all" : { "type" : "string"}
 }

```
What its doing is creating the "all" column in the cassandra table, but not populating it with any data.

Is this feature supported and if so can someone help me understand what I'm doing wrong?

Thanks!

- Greg

**Comment by vroyer** [comment]
Sorry, this is not currently supported.
