### ISSUE TITLE
why my elasticsearch one element array will return string

### ISSUE THREAD

**Issue by hksfho** [strapdata/elassandra#114]
I save my data using the api

> curl -XPOST 'http://myip.com/index/type/id' -H 'Content-Type: application/json' -d '{ "twoarr": [ "a", "b" ], "onearr": ["a"] }'

and the mapping create automatically:

> {
>   "type": {
>     "properties": {
>       "onearr": {
>         "type": "string"
>       },
>       "twoarr": {
>         "type": "string"
>       }
>     }
>   }
> }

search:

> curl -XGET 'http://myip.com/index/type/id' -H 'Content-Type: application/json' -d '{}'

this is the result:

> {"twoarr":["a","b"],"onearr":"a"}

why the one element array convert to string automatically......

I want this:

> {"twoarr":["a","b"],"onearr":["a"]}

thank you.

**Comment by DBarthe** [comment]
Hi, I think this is the default elasticsearch behavior.

**Comment by DBarthe** [comment]
From [elasticsearch documentaion](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html):
> In Elasticsearch, there is no dedicated array type. Any field can contain zero or more values by default

But in elassandra, the elasticsearch properties can be backed by a casandra `Set<X>`, `List<X>`, or just `X`. This is configurable when you define the mapping with a parameter called `cql_collection` and this is documented [here](http://doc.elassandra.io/en/latest/mapping.html).

The client app may handle that and transforms single values to singleton arrays whenever It knows the property is logically an array. Don't know if better option exists...

**Comment by hksfho** [comment]
set cql_collection to Set<X>, List<X> or singleton also not work

**Comment by vroyer** [comment]
What do you mean by « also not work » ?
In elasticsearch, all fields are multi-valued, but when a field contains only one value, the field is displayed without brackets.

**Comment by dickhfchan** [comment]
The issue here is that ElasticSearch (without Cassandra) returns array with single item in a bracket. We have tested this in the cloud service in Elastic.io. For Elassandra, array with single item is returned without the bracket. The client has to check if this is string (without bracket) then turn the string to a array.

@hksfho  you can show vroyer the codes, the before and after, need to handle the missing bracket. 

I am sure why Elassandra and ElasticSearch behaviour differently in this area. If ElasticSearch is app on top of Cassandra (the architecture of Elassandra, it should behave the same as the pure ElasticSearch.

I can see the opportunity to have the ElasticSearch users migrate to Elassandra if they can run their ES app without the code changes.

**Comment by vroyer** [comment]
With elasticsearch, _source document is stored in lucene, with or without brackets for single-value fields. Then, elasticsearch brings back the stored document as you stored it.

In elassandra, _source is not stored as a blob by default, but in some cassandra columns. Then, _source is dynamically rebuild from theses columns, and by default singleton lists or singleton sets are converted to one element (i.e without bracket). 

This default behaviour could be change to add brackets in all cases (keep singleton list and set unchanged), but for documents inserted with a no-bracket single value, rebuilt _source would contains brackets surounding the single value (see #80), causing the same different behaviour !

So, the only way to strictly stick the elasticsearch behaviour is to store the _source in a dedicated cassandra column (a compressed blob). This can be done by enabling the _source (disabled by default in elassandra) in your mapping. Then, you will get brackets as you inserted in the _source.

Note that enabling source involve an overhead on disk of course, and changing the _source column in a CQL upsert won't update others columns, nor index its fields. This was primarily intended to store complex geoshape documents.

**Comment by dickhfchan** [comment]
@vroyer Thanks for your detail explanation. I can see the basic logics. Changing the default behaviour of the system is not a very good idea. We can accept there is variance between ElasticSearch and Elassandra. We have decided to change our client program to handle the issue.  

Thanks again. Looking forwards to the upgrade to ES5.5
