### ISSUE TITLE
Where is elasticsearch config file located?

### ISSUE THREAD

**Issue by hksfho** [strapdata/elassandra#115]
want to install Smart Chinese Analysis Plugin.
![2017-08-29 5 03 49](https://user-images.githubusercontent.com/11540687/29813223-0dae617c-8cdc-11e7-9f3a-232cc4af684f.png)

**Comment by DBarthe** [comment]
Hi @hksfho,

Sorry, for some reason, we missed it while packaging. My fault :s

You can download it from :
[https://github.com/strapdata/elassandra/blob/v2.4.5-strapdata/distribution/src/main/resources/conf/elasticsearch.yml](https://github.com/strapdata/elassandra/blob/v2.4.5-strapdata/distribution/src/main/resources/conf/elasticsearch.yml)

**Comment by hksfho** [comment]
restart server will it work??

**Comment by DBarthe** [comment]
It has to ! Is this a production server ?

**Comment by DBarthe** [comment]
Release 2.4.5.5 zip and tar have been updated. Thanks for reporting the issue :+1:
