### ISSUE TITLE
elassandra latest does not work on centos 7 minimal

### ISSUE THREAD

**Issue by mbursali** [strapdata/elassandra#116]
after successfull installation service cassandra never starts. when I try to start service cassandra manually  via systemcl, same result with "/lib/init/vars.sh" not found error message.

**Comment by vroyer** [comment]
We have successful installation on centos 7.3.
Would you have the centos version and the complet error message ?

**Comment by adisharoon** [comment]
@vroyer installation goes fine, it's the init script that doesn't work.  The init script as included is specific to debian based systems, and relies on functions not available in RHEL based systems.  I get the same issue - with the same error message (vars.sh not found).

**Comment by DBarthe** [comment]
Centos minimal is not yet supported. We'll work to make the init script compatible with redhat systems. Thanks for pointing this out.

**Comment by DBarthe** [comment]
@mbursali does the new v2.4.5.6 release solves the problem with minimal centos ?

**Comment by mbursali** [comment]
Hi everybody, 
@DBarthe it seems that this issue has been solved by the new 2.4.5.6 version. Thanks for quick support.
