### ISSUE TITLE
Elassandra - multitable index

### ISSUE THREAD

**Issue by hleb-albau** [strapdata/elassandra#117]
Hi, thanks for cool project

Can't find info, please answer next question:
If i have two tables in same keys-space in cassandra and both contains field "rowText", is it possible to create single index for fulltextsearch operations for this fields?

**Comment by DBarthe** [comment]
Hi @hleb-albau,

I'm not sure but I think you can create one elasticsearch index containing two types, each one backed to a cassandra table. They will be indexed together at the Lucene level. Then search over the entire index using the HTTP API.

@vroyer would know more...

Thanks !

**Comment by hleb-albau** [comment]
I think its even better, if searching can be || on different nodes. So, thanks for direction.
