### ISSUE TITLE
Should Cassandra 3.11.1 be merged due to CASSANDRA-13752 and CASSANDRA-13756 SSTable corruption bugs?

### ISSUE THREAD

**Issue by twoofy** [strapdata/elassandra#119]
This looks pretty worrisome, should C* 3.11.1 get merged?

https://issues.apache.org/jira/browse/CASSANDRA-13752

This seems related too:

https://issues.apache.org/jira/browse/CASSANDRA-13756

- Greg

**Comment by vroyer** [comment]
Yes, as soon as the C* 3.11.1 will be fully released (there is not yet cassandra-3.11.1 tag).

**Comment by vroyer** [comment]
Elassandra 5.5.0.4 is now based on Cassandra 3.11.1.
