### ISSUE TITLE
add full support for elastic hq

### ISSUE THREAD

**Issue by ChrisFeldmeier** [strapdata/elassandra#12]
Elastic HQ Plugin: http://www.elastichq.org/support_plugin.html works good. 
But some variables like CPU and Network.. are not correct / elassandra provide no information here. elasticsearch does.

**Comment by vroyer** [comment]
I get the same issue with elasticsearch 2.1.1, no CPU, Network... 
Did you get these variables with another version of elasticsearch ?

**Comment by ChrisFeldmeier** [comment]
yes native elasticsearch provide me these variables...

**Comment by vroyer** [comment]
With elasticsearch 2.1.1 ? I have done a test with elasticsearch 2.1.1 running on redhat 6.5, and i did not get any cpu or network graph. There are less than 100 source files modified from elasticsearch, and this part remains unchanged, so it seems to be an elasticsearch issue.

**Comment by ChrisFeldmeier** [comment]
I will double check this week.

Wir sind ihr spezieller Partner für IT Web-Applikationen, Internetseiten und Big-Data Anwendungen! 

Feldmeier Technology
Christoph Feldmeier
Riedstraße 2
94377 Steinach

Fon: 09428/3053895
Mail: info@feldmeier-technology.com
Web: www.feldmeier-technology.com
