### ISSUE TITLE
How to create table mapping  for match  _all field query

### ISSUE THREAD

**Issue by hleb-albau** [strapdata/elassandra#120]
Hi,

Suppose i have next cassandra table.
```
CREATE TABLE TEST (
     id varint PRIMARY KEY,
     number varint,
     block text,
     otherTextField text
)
```

All i need is just to have possibility to query such tables   for match  _all field query. I do not need index fields itself.
```
GET my_index/test/_search
{
  "query": {
    "match": {
      "_all": "john snow"
    }
  }
}

```

How mapping should looks like?
Thanks,

**Comment by vroyer** [comment]
Hi,

It’s not possible, _all means « all indexed fields » in Elasticsearch, not « all cassandra columns ».

Thanks.

**Comment by hleb-albau** [comment]
Hi, so i should index all columns to achieve needed behavior? Or maybe i miss something?
Also, one more question:
In Cassandra world your create tables for each your query. But, if we have custom second index, than we have another option to provide fast search.

So in Cassandra world, i usuals create denormalized tables like this:
```
CREATE TABLE TEST_BY_NUMBER (
     id varint,
     number varint,
     block text,
     otherTextField text,
   PRIMARY KEY(number, id)
)
CREATE TABLE TEST_BY_otherTextField (
     id varint,
     number varint,
     block text,
     otherTextField text,
   PRIMARY KEY(otherTextField, id)
)
```
 What approaches should i use for elassandra? How fast(compare to common cassandra patterns) elastic search ways is? May be you can give me link to some read.

Thanks in advance!

**Comment by vroyer** [comment]
Hi,
In order to index all column of a table, juste create an elasticsearch mapping to index all columns.
You can use an automatic discover mapping as described here http://elassandra.readthedocs.io/en/latest/mapping.html?highlight=discover#bidirectionnal-mapping <http://elassandra.readthedocs.io/en/latest/mapping.html?highlight=discover#bidirectionnal-mapping>

Elasticsearch is very fast for search (usually < 20ms), but newly indexed documents become visible for search after a refresh, and refresh occurs every seconds by default (see elasticsearch doc)
So, depending on our use case, search fit or not.

Cheers,
Vincent

**Comment by hleb-albau** [comment]
@vroyer 
Hi, Vincent. Sorry for dummy questions ;) i just try to figure out is it suitable for my strange case:

I have a table with 20columns. I need fulltextsearch on on raw document( just need some sort of scoring for user input), also i need execute 2-3 query (to find particular documents on single field ~up to 1000 documents in result). Data is few TB.

So, here i have 3 variants:

1. Store only raw data, index all columns use elastic for all search. This variant is great due to unlimited search possibilities on unexpected new requirements. 
2. Create cassandra table with 3-4 columns, one of them is a raw document, other fields to query documents. Index all in elastic, search all in elastic. Use term conditions for field-columns and fulltextsearch for raw document column. 
3. Create denormalized tables in Cassandra, use Cassandra to execute 2-3 query. Also, this tables will contain 2-3 columns,one of them is raw document, other is particular field used in pk(wide rows). Create mapping for elastic form raw document column from one table. Use elastic only for fulltextsearch.

What way is preferable? Will second variant out-beat first variant in term of index space? I must admit, that 2 and 3 ways seems like ad hoc.

Thanks,
Hleb Albau
