### ISSUE TITLE
Is it possible to map varint cassandra columns to elasstic?

### ISSUE THREAD

**Issue by hleb-albau** [strapdata/elassandra#122]
I have a column lock_time varint

When i try to map it to elastic using discover feature, all manually set to  type string or long, there is error of type mismatch.  
```
No type specified for field [lock_time],
Existing column lock_time mismatch type bigint",
Existing column lock_time mismatch type text",
```

Same question for decimal

Is there a way to map this types to string elastic type? Or lose some precisions and map to double?

**Comment by vroyer** [comment]
Would you have more details about your issue (elassandra version, CQL schema, error logs ) ?
Thanks.

**Comment by hleb-albau** [comment]
Hi, elassandra v:2.4.5.5.

Cql schema:
```
CREATE table IF NOT EXISTS markets.zaac_tx (
    address text,
    amount decimal,
    tx_id text,
    tx_out int
);
```
Mapping:
```
curl -XPUT "http://localhost:9200/markets/" -d '{
   "settings" : { "keyspace" : "markets" } },
}'
curl -XPUT "http://localhost:9200/market/_mapping/zaac_tx" -d '{
    "zaac_tx" : {
      "properties": {
        "address": {"type": "string", "index": "not_analyzed", "include_in_all": true, "cql_collection" : "singleton"},
        "amount": {"type": "string", "index": "no", "include_in_all": false, "cql_collection" : "singleton"},
        "tx_id": {"type": "string", "index": "not_analyzed", "include_in_all": true, "cql_collection" : "singleton"},
        "tx_out": {"type": "long", "index": "no", "include_in_all": false, "cql_collection" : "singleton"}
      }
    }
}'
``` 
Give me error for string amount     ->  Existing column amount mismatch type text
Give me error for double amount  ->  Existing column amount mismatch type double

Next mapping:
```
curl -XPUT "http://localhost:9200/market/_mapping/zaac_tx" -d '{
    "discover" : "amou.*",
    "zaac_tx" : {
      "properties": {
        "address": {"type": "string", "index": "not_analyzed", "include_in_all": true, "cql_collection" : "singleton"},
        "tx_id": {"type": "string", "index": "not_analyzed", "include_in_all": true, "cql_collection" : "singleton"},
        "tx_out": {"type": "long", "index": "no", "include_in_all": false, "cql_collection" : "singleton"}
      }
    }
}'
```

Give me error ->  No type specified for field [amount]

**Comment by hleb-albau** [comment]
decimal is java analogue for BigDecimal. Elastic doesn't have such types, so i just want to know, is it possible to map from cql to elastic with such types.

**Comment by hleb-albau** [comment]
In general tables is more wide (~20 columns), than elastic index(~5 columns). I use elastic to map certain fields to _all. When i search through elastic i want some sort of item preview( about 5-6 fields from original Cassandra entity). Elastic returns me a list, and then, if i want get full info, i use cql to retrieve full document.

**Comment by vroyer** [comment]
Sorry, CQL decimal is not currently supported by elassandra because elasticsearch does not support BigDecimal, you should find an error message like this in your logs "Ignoring unsupported type {} for column {} » ?
See https://github.com/elastic/elasticsearch/issues/17006 <https://github.com/elastic/elasticsearch/issues/17006>

**Comment by hleb-albau** [comment]
So, maybe you can add support to map such types as raw strings? It's not complicated as i see.
