### ISSUE TITLE
synchro from casandara  to elastisearch 

### ISSUE THREAD

**Issue by porlock** [strapdata/elassandra#124]
Sorry for this question, but there is only possibile to transfer real time data from elastisearch to casandara or in other way also ?

**Comment by DBarthe** [comment]
Hi @porlock,

In Elassandra, when you have an elastic index mapped to a cassandra table, data inserted with CQL are automatically indexed in elastic, and data indexed from the elastic API are automatically stored in cassandra.

Even more, if you create an index with elasticsearch, the underlying cassandra table and keyspace are automatically created. We call this bidirectional mapping.

**Comment by porlock** [comment]
Im trying to recreate folowing casandra keyspace

```
CREATE KEYSPACE newts WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE newts.resource_attributes (
    context text,
    resource text,
    attribute text,
    value text,
    PRIMARY KEY ((context, resource), attribute)
) WITH CLUSTERING ORDER BY (attribute ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE newts.terms (
    context text,
    field text,
    value text,
    resource text,
    PRIMARY KEY ((context, field, value), resource)
) WITH CLUSTERING ORDER BY (resource ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE newts.samples (
    context text,
    partition int,
    resource text,
    collected_at timestamp,
    metric_name text,
    attributes map<text, text>,
    value blob,
    PRIMARY KEY ((context, partition, resource), collected_at, metric_name)
) WITH CLUSTERING ORDER BY (collected_at ASC, metric_name ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE newts.resource_metrics (
    context text,
    resource text,
    metric_name text,
    PRIMARY KEY ((context, resource), metric_name)
) WITH CLUSTERING ORDER BY (metric_name ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
```

When i try to create index in ealasticsearch 

```
PUT newts
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
      "resource_attributes" : {
          "properties" : {
          "context" : { "type" : "text" },
				  "resource" : { "type" : "text" },
				  "attribute" : { "type" : "text" },
				  "value" : { "type" : "text" }
          }
        },
		  "terms" : {
          "properties" : {
          "context" : { "type" : "text" },
				  "field" : { "type" : "text" },
				  "value" : { "type" : "text" },
				  "resource" : { "type" : "text" }
          }
        },
		  "samples" : {
            "properties" : {
                "context" : { "type" : "text" },
				        "partition" : { "type" : "integer" },
				        "resource" : { "type" : "text" },
				        "collected_at" : { "type" : "integer" },
				        "metric_name" : { "type" : "text" },
				        "attributes map" : { "type" : "text" },
				        "value" : { "type" : "text" }
            }
        },
		  "resource_metrics" : {
            "properties" : {
                "context" : { "type" : "text" },				
				        "resource" : { "type" : "text" },				
				        "metric_name" : { "type" : "text" }						
            }
        }	
    }
}
```

I get an error 

>      "type": "i_o_exception",
>         "reason": "Cannot create index, underlying keyspace requires the NetworkTopologyStrategy."

What im missing ?

**Comment by vroyer** [comment]
Hi,

As said in the error message, you must use the NetworkTopologyStrategy for your cassandra keyspace.

Regards.

**Comment by porlock** [comment]
yes you right that helps, but i have a problem with value mapping i get error 

> Existing column [field] mismatch type  list text

But in keyspace there is clearly see that this filed is text type
```
CREATE TABLE newts.terms (
    context text,
    field text,
    value text,
    resource text,
```

**Comment by vroyer** [comment]
Don’t you have another table in the same keyspace with a column « field » and CQL type list<text> ?
In elasticsearch, a field is defined per index, so you can’t index 2 columns of 2 tables in the same keyspace with different types.
Regards.

**Comment by porlock** [comment]
Actually i have only one "filed" column, but i have other columns that have the same name in the diferent tables but they are the same type. So it shoudl work ? or there is a need to modified a keyspace in casandra ?

```
CREATE TABLE newts.resource_attributes (
    context text,
    resource text,
    attribute text,
    value text,

CREATE TABLE newts.terms (
    context text,
    field text,
    value text,
    resource text,

CREATE TABLE newts.samples (
    context text,
    partition int,
    resource text,
    collected_at timestamp,
    metric_name text,
    attributes map<text, text>,
    value blob,

CREATE TABLE newts.resource_metrics (
    context text,
    resource text,
    metric_name text,
```

**Comment by porlock** [comment]
i think this is some kind of bug.. 

even if i create a new index like bellow
```
PUT newts6
{
    "settings" : {
        "keyspace" : "newts"
    },
    "mappings" : {
      "samples" : {
          "properties" : {
            "context" : {
                "type" : "string"
            }
        }
      }
    }
}
```

i get an error 

> 
>      "type": "i_o_exception",
>       "reason": "Existing column [context] mismatch type list<text>"

**Comment by vroyer** [comment]
It work correctly with version 5.5.0.1 :

$ curl -XPUT $CREDENTIAL "$PROTOCOL://$NODE:9200/newts6" -d '{
>     "settings" : {
>         "keyspace" : "newts"
>     },
>     "mappings" : {
>       "samples" : {
>           "properties" : {
>             "context" : {
>                 "type" : "string"
>             }
>         }
>       }
>     }
> }'
{"acknowledged":true,"shards_acknowledged":true}

cassandra@cqlsh> desc KEYSPACE newts ;
CREATE KEYSPACE newts WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '1'}  AND durable_writes = true;
CREATE TABLE newts.samples (
    "_id" text PRIMARY KEY,
    context list<text>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = 'Auto-created by Elassandra'
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_samples_idx ON newts.samples () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';

...
"indices" : {
      "newts6" : {
        "state" : "open",
        "settings" : {
          "index" : {
            "keyspace" : "newts",
            "number_of_shards" : "1",
            "provided_name" : "newts6",
            "creation_date" : "1506522950839",
            "number_of_replicas" : "0",
            "uuid" : "ZVmN-faXRSeybanzgg-56Q",
            "version" : {
              "created" : "5050099"
            }
          }
        },
        "mappings" : {
          "samples" : {
            "properties" : {
              "context" : {
                "type" : "text"
              }
            }
          }
        },
        "aliases" : [ ],
        "primary_terms" : {
          "0" : 0
        },
        "in_sync_allocations" : {
          "0" : [ ]
        }
      },

….
