### ISSUE TITLE
error when play kibana with elassandra

### ISSUE THREAD

**Issue by xycloud** [strapdata/elassandra#125]
got error when play kibana's setting index-pattern with elassandra 
* version: 5.5
* erorr: 

```
Request to Elasticsearch failed: "[Not Found] [type_missing_exception] type[[index-pattern]] missing, with { index_uuid=\"_na_\" & index=\"_all\" }"
```

**Comment by vroyer** [comment]
Would you have more information about this issue, logs or any way to reproduce it ?
Thanks.
