### ISSUE TITLE
Cannot install x-pack on the latest pre-release version

### ISSUE THREAD

**Issue by jasleen1291** [strapdata/elassandra#126]
**Elasticsearch version**: 5.5.0

**Plugins installed**: Was trying to install x-pack

**JVM version**: java version "1.8.0_92", 64 bit

**OS version**: GNU/Linux

**Description of the problem including expected versus actual behavior**:
I was trying to install xpack on elassandra and i am getting a jar hell issue. I tried using both the elasticsearch-plugin and the zip file. Please see the logs below
**Steps to reproduce**:
 1.
 sudo ./elasticsearch-plugin install x-pack

**Provide logs (if relevant)**:
-> Downloading x-pack from elastic
[=================================================] 100%
16:52:05.528 [main] DEBUG org.elasticsearch.bootstrap.JarHell - java.home: /usr/java/jdk1.8.0_92/jre
16:52:05.533 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/owasp-java-html-sanitizer-r239.jar
16:52:05.534 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/libthrift-0.9.2.jar
16:52:05.535 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/jackson-core-2.8.6.jar
16:52:05.536 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/lucene-sandbox-6.6.0.jar
16:52:05.536 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/disruptor-3.0.1.jar
16:52:05.537 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/slf4j-api-1.7.25.jar
16:52:05.537 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/httpasyncclient-4.1.2.jar
16:52:05.538 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/ST4-4.0.8.jar
16:52:05.538 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/metrics-jvm-3.1.0.jar
16:52:05.539 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/transport-netty3-5.5.0.jar
16:52:05.539 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/cassandra-thrift-3.11.0.1.jar
16:52:05.541 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/ant-launcher-1.7.0.jar
16:52:05.542 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/httpcore-nio-4.4.5.jar
16:52:05.543 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/jna-4.4.0.jar
16:52:05.543 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/plugin-cli-5.5.0.jar
16:52:05.543 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/netty-3.10.6.Final.jar
16:52:05.545 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/jctools-core-1.2.1.jar
16:52:05.546 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/antlr-runtime-3.5.2.jar
16:52:05.546 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/validation-api-1.0.0.GA.jar
16:52:05.547 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/concurrent-trees-2.4.0.jar
16:52:05.547 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/netty-transport-4.1.11.Final.jar
16:52:05.548 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/logback-core-1.1.8.jar
16:52:05.549 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/log4j-api-2.8.2.jar
16:52:05.550 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/lucene-queries-6.6.0.jar
16:52:05.551 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/lucene-analyzers-common-6.6.0.jar
16:52:05.555 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/bcpkix-jdk15on-1.55.jar
16:52:05.558 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/jamm-0.3.0.jar
16:52:05.559 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/joda-time-2.9.5.jar
16:52:05.560 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/commons-cli-1.3.1.jar
16:52:05.560 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/javassist-3.20.0-GA.jar
16:52:05.561 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/java-version-checker-5.5.0.jar
16:52:05.561 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/snappy-java-1.1.1.7.jar
16:52:05.562 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/commons-math3-3.2.jar
16:52:05.564 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/lucene-spatial-extras-6.6.0.jar
16:52:05.564 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/jackson-dataformat-cbor-2.8.6.jar
16:52:05.565 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/jackson-core-asl-1.9.13.jar
16:52:05.565 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/commons-lang3-3.3.1.jar
16:52:05.566 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/ant-1.7.0.jar
16:52:05.568 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/jboss-logging-3.1.0.CR2.jar
16:52:05.568 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/ohc-core-0.4.4.jar
16:52:05.568 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/httpcore-4.4.5.jar
16:52:05.569 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/elasticsearch-5.5.0.jar
16:52:05.578 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/cassandra-all-3.11.0.1.jar
16:52:05.583 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/high-scale-lib-1.0.6.jar
16:52:05.583 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/javax.mail-1.5.3.jar
16:52:05.584 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/commons-codec-1.10.jar
16:52:05.585 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/httpclient-4.5.2.jar
16:52:05.586 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/lz4-1.3.0.jar
16:52:05.586 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/netty-buffer-4.1.11.Final.jar
16:52:05.587 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/lucene-grouping-6.6.0.jar
16:52:05.587 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/lucene-queryparser-6.6.0.jar
16:52:05.588 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/bcprov-jdk15on-1.55.jar
16:52:05.601 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/lib/commons-logging-1.2.jar
16:52:05.602 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/netty-handler-4.1.11.Final.jar
16:52:05.602 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/netty-common-4.1.11.Final.jar
16:52:05.603 [main] DEBUG org.elasticsearch.bootstrap.JarHell - examining jar: elassandra-5.5.0/plugins/.installing-3099544478878326004/httpclient-4.5.2.jar
Exception in thread "main" java.lang.IllegalStateException: jar hell!
class: org.apache.http.auth.KerberosCredentials
jar1: elassandra-5.5.0/lib/httpclient-4.5.2.jar
jar2: elassandra-5.5.0/plugins/.installing-3099544478878326004/httpclient-4.5.2.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:299)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:192)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:531)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:500)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:543)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by DBarthe** [comment]
Hello,

Try removing `elassandra-5.5.0/plugins/.installing-3099544478878326004/httpclient-4.5.2.jar`.

JarHell ensures there is no duplicate class in classpath. Obviously this may happen after installing plugins.

Elassandra developers didn't test x-pack with elassandra. you might encounter troubles. Also Strapdata is going to deliver an enterprise plugin for securing elasticsearch within elassandra.

**Comment by jasleen1291** [comment]
Sorry that did not work for me. I don't have any other plugins installed either. Could x-pack integration for monitoring be made available  in the next release

**Comment by DBarthe** [comment]
Can you provide output like you did before ?

Classpath conflicts can occur between plugins and core libraries. No matter you have other plugins installed or not. (in this case, httpclient is a dependency introduced by cassandra... x-pack does not expect to face this conflict)

Also I'm curious to know which x-pack features you wanted to use with elassandra ? Only monitoring ?

**Comment by vroyer** [comment]
Hi Jasleen,

X-pack is not open source and we can’t support-it, but strapdata will provide very shortly in October an alternate solution to monitor and secure elassandra.

Best regards.
Vincent.

**Comment by jasleen1291** [comment]
Ok thanks, will wait for it. I am mainly interested in monitoring

**Comment by vroyer** [comment]
The Elassandra Enterprise plugin is now available and provides JMX management and monitoring. Documentation is available at [http://doc.elassandra.io/en/latest/enterprise.html#jmx-managment-monitoring](http://doc.elassandra.io/en/latest/enterprise.html#jmx-managment-monitoring). You can request a trial license for free at [http://www.strapdata.com/trial/](http://www.strapdata.com/trial/).
