### ISSUE TITLE
Documentation around Elassandra upgrades

### ISSUE THREAD

**Issue by hkroger** [strapdata/elassandra#127]
Hi,

I was looking at the docs here:
http://doc.elassandra.io/en/latest/operations.html

I didn't spot the documentation around how to upgrade elassandra. Basically if it can be done on-the-fly with rolling upgrades, what are the considerations, etc.

Maybe those could be added there?

**Comment by DBarthe** [comment]
Hi,

Depends on versions. For a minor upgrade, rolling upgrade should be OK. But if you plan upgrading 2.x to 5.x you will need a full cluster restart.

In any case, best is to back-up your data before.

**Comment by hkroger** [comment]
One of the great things with Cassandra has always been that you can do almost everything while the cluster is running. So having to do a (non-rolling) restart the cluster or recreate indexes on upgrade is an important bit of information. And also might be something that prevents some users from using Elassandra.

**Comment by DBarthe** [comment]
Could be added to the known [limitations](http://doc.elassandra.io/en/latest/limitations.html#cassandra-limitations).

But, there is probably a way to keep your cassandra cluster alive and only have elasticsearch downtime. By closing elastic indexes, rolling upgrade elassandra, then rebuild the indexes. (meanwhile you'll have to manage elastic plugins upgrades)

Of course, this kind of upgrade is very rare.

**Comment by hkroger** [comment]
Yeah, I think those are great to be mentioned somewhere because these things don't come naturally to everyone. There are a lot of people with limited knowledge about Elassandra/Elasticsearch management in general.

**Comment by vroyer** [comment]
Hi,
This is an Elasticsearch upgrade limitation, see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html <https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html>, and upgrade involves changes in ES API in application side.

If you need hot upgrade, you could create a new datacenter for ES upgrade, as explained in http://elassandra.readthedocs.io/en/latest/integration.html#create-a-new-elassandra-datacenter <http://elassandra.readthedocs.io/en/latest/integration.html#create-a-new-elassandra-datacenter>, and then switch your application to the upgraded version. 
With the cassandra continuous replication, you could even run 2 versions of Elasticsearch in 2 datacenters for a while, and 2 versions of your application sharing the same.
So, Elassandra can provide a nice solution for major ES hot upgrades.

Cheers.
Vincent.
