### ISSUE TITLE
Elassandra 5.5 and ElasticSearch for Spark connector

### ISSUE THREAD

**Issue by jluzny** [strapdata/elassandra#129]
Elassandra 5.5 is now released as a stable version, but there is no corresponding upgrade of elasticsearch-hadoop connector released, so we cannot connect Spark to Elassandra (ElasticSearch 5.5.0). Is there any plan to release it? Or should the unmodified version of Eleasticsearch-hadoop connector (5.5.3) work just fine?

Thanks.

**Comment by vroyer** [comment]
Hi,
The spark connector for Elassandra 5.5+ will be released in a few weeks, it’s on going.
Thanks.

**Comment by vroyer** [comment]
You can find a pre-released of the elasticsearch-hadoop connector for elassandra 5.5+ available at https://github.com/strapdata/elasticsearch-hadoop. 
Thanks for your feedback.

**Comment by jluzny** [comment]
I cannot see any release package, there are just a source code archives there....

**Comment by vroyer** [comment]
5.5.0.4 packages are available at https://github.com/strapdata/elassandra/releases <https://github.com/strapdata/elassandra/releases>

**Comment by jluzny** [comment]
I mean pre-release package for https://github.com/strapdata/elasticsearch-hadoop

**Comment by vroyer** [comment]
run "grade assemble" to build it.

**Comment by vroyer** [comment]
The elasticsearch-hadoop-5.5.0.jar is now available on https://github.com/strapdata/elasticsearch-hadoop/releases <https://github.com/strapdata/elasticsearch-hadoop/releases>
Thanks for your feedback about it.

**Comment by jluzny** [comment]
The new release tested and some basic Spark use cases (SQL queries) run just fine :-)
However we tested it on single node setup only, so will let you know results from our clustered environment.
