### ISSUE TITLE
CQL Map types with map<timestamp, text> throws mapper_parsing_exception

### ISSUE THREAD

**Issue by masumsoft** [strapdata/elassandra#130]
**Elasticsearch version**: 5.5.0

**Plugins installed**: []

**JVM version**: 1.8.0_101

**OS version**: macos Sierra

**Description of the problem including expected versus actual behavior**:

Say I have a a cql map defined like this: `map<timestamp, text>`. If I try to use `discover` to create an index from the existing cassandra table with that map, then it throws a `mapper_parsing_exception`.

**Steps to reproduce**:
 1. In cqlsh:

```
CREATE KEYSPACE twitter WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': 1};
```

 2. Using curl:

```
curl -XPUT 'http://localhost:9200/twitter' -d '{
    "settings": { "keyspace":"twitter" }
}'
```

 3. In cqlsh:

```
CREATE TABLE twitter.user (
   name text,
   attrs map<timestamp, text>,
   PRIMARY KEY (name)
);
```

4. Using curl:

```
curl -XPUT "http://localhost:9200/twitter/_mapping/user" -d '{ "user" : { "discover" : ".*" }}'
```

5. An exception is thrown in the previous step:

```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No type specified for field [attrs]"}],"type":"mapper_parsing_exception","reason":"No type specified for field [attrs]"},"status":400}
```

**Comment by vroyer** [comment]
Dynamic Elasticsearch mapping only works for CQL maps having a text key (the CQL map key=ES doc field name, CQL value=ES field value)
In your case, key is a timestamp, so it can work.

I will improve the documentation about this feature.
http://doc.elassandra.io/en/latest/mapping.html#dynamic-mapping-of-cassandra-map <http://doc.elassandra.io/en/latest/mapping.html#dynamic-mapping-of-cassandra-map>

Thanks for reporting your issue.

**Comment by vroyer** [comment]
Doc is updated.
