### ISSUE TITLE
ES 5.6.x support.

### ISSUE THREAD

**Issue by fluiddmotion** [strapdata/elassandra#134]
Having issue with using Kibana 5.6 and Logstash 5.6 Modules on Elassandra. Is there a road map as to when ES 5.6.x will be supported?

**Elasticsearch version**: 5.5.0

**Plugins installed**: [] Netflow

**JVM version**: 8

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by vroyer** [comment]
Yes, it’s on the roadmap.
You need ELK 5.6 for a very specific feature ?
Thanks.

**Comment by fluiddmotion** [comment]
Hi Vincent,

We are trying to use the new Netflow Module in 5.6 this is the main piece we wish to utilise, the biggest problem is with Kibahna to be fair with certain dashboard’s.

I was more wondering what the roadmap / timeframe was as we wish to use Elassndra instead of native ES..

Kind Regards

Lee

**Comment by vroyer** [comment]
Hi Lee,
Netflow plugin was available in ELK 5.5 in version 3.4.
I guess you need a feature added in netflow 3.4+ (see https://github.com/logstash-plugins/logstash-codec-netflow/blob/v3.5.2/CHANGELOG.md <https://github.com/logstash-plugins/logstash-codec-netflow/blob/v3.5.2/CHANGELOG.md>), and version 3.5+ may work with ELK 5.5  (it’s a codec plugin).
Elassandra roadmap is mainly driven by my current customer needs, but is should be available by the end of 2017.
Sincerely,
Vincent.

**Comment by jasleen1291** [comment]
Any update on when 5.6 will be released?

**Comment by vroyer** [comment]
Why do you need version 5.6
Version 5.6 was mainly intended to tag deprecated features in release 6+, so there is no clear interest to do that job, unless you want a commercial support ?

**Comment by vroyer** [comment]
Version 6.2.3 has been released.
