### ISSUE TITLE
Materialised Properties Support

### ISSUE THREAD

**Issue by bevans88** [strapdata/elassandra#136]
It would be good if it was possible to add materialised properties(fields) to the Elasticsearch document that aren't present in the Cassandra row that the document is generated from. This could be from another table in Cassandra, or something that is calculated from elsewhere (Document creation date etc.). 

For example:

Cassandra Person Table:

|      Name      |      DOB      |      Place of Birth      | 
| ------------- | ------------ | -----------------------| 
| John | 01/01/90 | London |
| Sam | 05/09/12 | Paris | 

Cassandra Location Table: 
 
|      Name      |      Latitude      |     Longitude      | 
| ------------- | ------------ | -----------------------| 
| London | 51.5074 | 0.1278 |
| Paris | 48.8566 | 2.3522 | 

- Upon Indexing a Person into Elasticsearch we would want to calculate the Persons age and add this to the document, as well as retrieving the Locations latitude and longitude and then adding this. 

The resulting Person document would be:

```
{
  "name" : "John",
  "DOB" : 01/01/90,
  "Age" : 27,
  "Place of Birth" : "London",
  "Latitude" : 51.5074,
  "Longitude" : 0.1278
}
```

**Comment by vroyer** [comment]
Well, this would require join on write path, and join on read path to rebuild the _source document from cassandra tables.
