### ISSUE TITLE
Elasticsearch 6 Support

### ISSUE THREAD

**Issue by bevans88** [strapdata/elassandra#137]
Elasticsearch 6 has now hit GA. I was just wondering if there is currently any plan for Elassandra to upgrade to it? 

I understand that this won't be straightforward due to the removal of support for multi-type indexes which Elassandra seems to rely on (Elasticsearch Type --> Cassandra Table)

**Comment by vroyer** [comment]
Yes, elassandra will migrate to ES 6 in 2018, the removal of document type is not an issue, documents will be mapped to a default C* table, and a pseudo _type field will be kept to read or write from other C* tables if needed.

**Comment by fluiddmotion** [comment]
Is there a timeline for when this will release in 2018?

**Comment by zcourts** [comment]
@vroyer I've asked about the type thing before and back then thought it was a good approach to do as you've mentioned above but has it been considered to do just one type per keyspace?

I can see cases with hundreds, thousands or even tens of thousands of types and thus keyspaces but what kind of impact would that have on C*? I know Jonnathon Ellis a while back said 
`"A keyspace is basically just a Map entry to Cassandra... you can have as many as you have memory for. Millions, easily."` https://stackoverflow.com/a/11266007/400048

Do you know if that's still true or have any thoughts you could share on why one wouldn't want to do this? Assuming you were prepared to accept the storage overhead of each keyspace. 
**EDIT**
Nevermind, I forgot/ignored how ES requests end up being done. https://stackoverflow.com/a/13557780/400048

**Comment by ddorian** [comment]
If you have 30GB of java heap in plain ES, dont store more than 1000 indexes.

**Comment by z0mb1ek** [comment]
any news?

**Comment by vroyer** [comment]
Hi,
Elasticsearch version 6.x is planned for june 2018, and by default, an elasticsearch index will be mapped to a keyspace.table.
Regards.

**Comment by jsebrien** [comment]
Hello,

Is is possible to create a branch with ES6, even as a beta version?

Regards,

Julien

**Comment by vroyer** [comment]
Hi,
Elassandra 6.2.3.1-rc1 is available !
Regards.

**Comment by jsebrien** [comment]
Hello,

Under Windows, I get the following error upon startup (I'm using java version "1.8.0_05"):

2018-05-17 09:01:04,747 ERROR [main] org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:587) Exception
java.lang.IllegalStateException: failed to load plugin aggs-matrix-stats due to jar hell
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:475)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:420)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:307)
        at org.elasticsearch.node.Node.<init>(Node.java:246)
        at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:184)
        at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:550)

Regards,

Julien

**Comment by vroyer** [comment]
I currently don't support windows.
You should find some indication in your logs abouts what jar cause this jarhell exception.
