### ISSUE TITLE
Error when trying to update string to text or keyword

### ISSUE THREAD

**Issue by devnut** [strapdata/elassandra#145]
In 2.4.5 the mapping used something like "type":"string".  To make this easier (I guess) ElasticSearch has changed this to "type":"keyword" and "type":"text".

This is all fine - but when you try to post an updated JSON to a mapping which used to look like:

```
"link": { "type" : "string", "index": "not_analyzed", "store" : "yes", "cql_collection": "singleton" },
"title": { "type" : "string", "index": "analyzed", "store" : "yes", "cql_collection": "singleton"},

```
and now looks like:

```
"title": { "type" : "text", "index": true, "store" : "yes", "cql_collection": "singleton"},
"native_guid": { "type" : "keyword", "ignore_above" : 10922, "index": true, "store" : "yes", "cql_collection": "singleton"},
```

It complains with:

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Automatic downgrade from [keyword] to [string] failed because parameters [cql_collection] are not supported for automatic downgrades."}],"type":"illegal_argument_exception","reason":"Automatic downgrade from [keyword] to [string] failed because parameters [cql_collection] are not supported for automatic downgrades."},"status":400}
```

I suspect this is because the code which does the "automatic downgrades" is not knowledgable about the added parameters which Elassandra has added?  It seems to be around here:

https://github.com/strapdata/elassandra/blob/dee357d3ddcdca147634699020e9dda0efa4eb31/core/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java#L135

**Comment by vroyer** [comment]
Yes, you could try to add cql_collection (and all cql_xxxx) to SUPPORTED_PARAMETERS_FOR_AUTO_DOWNGRADE_TO_STRING in KeywordFieldMapper.java, but as explain in #144, i think it's safer to rebuild new indices, eventually with a temporary datacenter.
