### ISSUE TITLE
Convert project to gradle

### ISSUE THREAD

**Issue by funssoft** [strapdata/elassandra#15]
Hi,

you should give a try for gradle instead of maven.

http://gradle.org/

gradle is more powerfull than maven in many ways.

**Comment by vroyer** [comment]
Yes, as elasticsearch moved from maven to gradle in version 2.2, it will switch to gradle in the next elasticsearch upgrade.

**Comment by funssoft** [comment]
Cool

**Comment by loint** [comment]
+1 for Gradle. Maybe it will be included in this release: 

https://github.com/strapdata/elassandra/issues/88

**Comment by vroyer** [comment]
Done with Elassandra 5.5.0.0-beta1 (Based on Elasticsearch 5.5.0 + Cassandra 3.11.0)
