### ISSUE TITLE
cannot map geo_point field

### ISSUE THREAD

**Issue by measwel** [strapdata/elassandra#154]
I am using the cassandra-express driver together with elassandra and trying to map a geo_point field like this:

geopoint UDT:
```
      manageESIndex: true,
      udts: {
        geopoint: {
          lat: 'double',
          lon: 'double'
        }
      }
```
cassandra table elastic mapping:
```
    location: {
      type: 'frozen',
      typeDef: '<geopoint>'
    }
  ...
  es_index_mapping: {
    discover: '.*',
    properties: {
      "location": {
        "type": "geo_point"
      }
    }
  }
```
The resulting elastic mapping is:
```
                    "location": {
                        "type": "nested",
                        "cql_collection": "singleton",
                        "cql_udt_name": "geopoint",
                        "properties": {
                            "lat": {
                                "type": "double",
                                "cql_collection": "singleton"
                            },
                            "lon": {
                                "type": "double",
                                "cql_collection": "singleton"
                            }
                        }
                    }
```
As can be seen, the mapping does not produce a geo_point, but a lat / lon pair. This does not work when trying to do a distance search. It seems that when using 'discover' the mapping properties are ignored.

If I try to set the mapping by hand:
```
{
	"post" :
	{
	"properties":
		{
			"location" :
			{
				"type":"geo_point"
			}
		}
	}
}
```
This however results in the error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "i_o_exception",
                "reason": "Existing column [location] type [frozen<geopoint>] mismatch with inferred type [list<frozen<geo_point>>]"
            }
        ]
    "status": 500
}
```

Can somebody help out please?

**Comment by vroyer** [comment]
Hi,
Your CQL UDT should be geo_point (not geopoint).
Then, you should discover all columns but the location by using "discover":"^((?!location).*)", and defines the location field properly. This should give something like this:

es_index_mapping: {
    discover: '^((?!location).*)',
    properties: {
      "location": {
        "type": "geo_point",  "cql_collection":"singleton"
      }
    }
  }

**Comment by measwel** [comment]
Thank you! Before reading your answer, I fixed it by:

1. removing auto discover
2. defining geo_point UDT
3. adding the singleton setting to the mapping

      "location": {
        "type": "geo_point",
        "cql_collection": "singleton"
      }

PS What is the best way to specify only a subset of collumns for auto discovery?

**Comment by vroyer** [comment]
Ok, fine.
Four your information, Elassandra Enterprise supports elasticsearch query directly from the CQL driver (integrated load balancing, integrated SSL+authentication, share your DAO for both ES and C*, no JSON serialization overhead).
Thanks.

com> a écrit :

**Comment by measwel** [comment]
Thank you for the information!
What is the best way to exclude a list of collumns from the auto discovery mapping? I wonder what the regex should look like?

PS what does the elassandra enterprise pricing model look like?

**Comment by vroyer** [comment]
You can exclude some columns form being discovered with such regexp : ^((?!comment|address).*)
It exclude column comment and address.

Elassandra Enterprise pricing model is an annual subscription per server for production servers (non-production are free). 
Thanks.
