### ISSUE TITLE
ES index per table

### ISSUE THREAD

**Issue by measwel** [strapdata/elassandra#156]
I would like to create a separate ES index per cassandra table in order to prevent clashes between equally named fields in those tables. When I try to create an ES index ( using elasticsearch node driver module ) with a different name than the keyspace name, I get an error stating that the index_name.table_name table does not exist. I guess this is because the index_name is not the same as the keyspace.

Can somebody please explain if it is possible to define multiple ES indexes with different names all using the same underlying cassandra keyspace? How should this be done in elassandra?

**Comment by vroyer** [comment]
Hi,

You can create 2 indices backed by the same keyspace, index1 with  a mapping defined for table1, and for index2, a mapping for table2.
Just set the keyspace when creating your 2 indices like this :

PUT /index1 -d'{
  "settings":{ 
    "keyspace": "ksname" 
  },
  "mappings":{
    "table1":{
        "discover":".*"
    }
  }
}'

PUT /index2 -d'{
  "settings":{ 
    "keyspace": "ksname" 
  },
  "mappings":{
    "table2":{
        "discover":".*"
    }
  }
}'

**Comment by measwel** [comment]
Thank you very much vroyer, that is exactly what I need. I just need to find out how to do that via the elasticsearch driver, not by manual put request.

**Comment by vroyer** [comment]
In your CreateIndexRequest, set a « keyspace » property in your Settings :

Settings.builder().put("keyspace", "ksname").build();

**Comment by measwel** [comment]
Thank you again! It works fine now.
