### ISSUE TITLE
benchmarking using cassandra-stress

### ISSUE THREAD

**Issue by draskolnikova** [strapdata/elassandra#158]
**Elasticsearch version**:
5.5.0
**Plugins installed**: []

**JVM version**:
1.8.0_152
**OS version**:
CentOS 7
**Description of the problem including expected versus actual behavior**:
I need to benchmark existing installation and cluster, I tried run `/usr/share/cassandra/tools/bin/cassandra-stress` from elassandra rpm packages got an error.

**Steps to reproduce**:
 1. Execute `/usr/share/cassandra/tools/bin/cassandra-stress` from cwd
 2. Error message `Error: Could not find or load main class org.apache.cassandra.stress.Stress` appeared

Is there any documentation/advice how to benchmark elassandra cluster?
Many thanks.

**Comment by lmangani** [comment]
This also seems to be the case for the default `strapdata/elassandra` docker images

**Comment by DBarthe** [comment]
Fixed with a62d0494b5332f97eee7ecb26359daf8c0bf64c3

**Comment by abikoolin** [comment]
I am using docker image version: elassandra-6.2.3.7. When I try to run command ./cassandra-stress -h from the /tools/bin directory I get an 
Error: Could not find or load main class org.apache.cassandra.stress.Stress.

I am executing this from inside the pod after
kubectl exec -it elassandra-0 bash

**Comment by Gappa88** [comment]
I have the same problem 
`Error: Could not find or load main class org.apache.cassandra.stress.Stress`
in Elassandra 6.2.3.7 package version
