### ISSUE TITLE
Sync or Async Index Updates?

### ISSUE THREAD

**Issue by alvincjin** [strapdata/elassandra#159]
May I ask if we load data via Cassandra api on a base table, will the index on this table be updated synchronously or asynchronously?
Thanks.

**Comment by vroyer** [comment]
Hi,

Index update is synchronous in elassandra, in memory lucene indices are update when writing into C*, and periodically flushed to disk like SSTable (this is the lucene logic).
Indexed data become visible for search after a refresh, and by default, elasticsearch refresh every second.

Sincerely.

**Comment by alvincjin** [comment]
Thanks.
