### ISSUE TITLE
row deletion from cassandra and associated indices synchronization in elasticsearch

### ISSUE THREAD

**Issue by mbammar** [strapdata/elassandra#160]
**Elasticsearch version**: 5.5.0.5

**JVM version**: jdk 1.8

**OS version**: Centos 6.9

**Description of the problem including expected versus actual behavior**:
I have a probleme regarding  row deletion from cassandra and associated indices synchronization.
in fact when i delete a row from a cassandra table a with compound key, i have two behavior :
- if the data in cassandra is inserted before elasticsearch index creation, the corresponding document  is not removed, however the _source field is empty because it's no longer in Cassandra!
- if the data in cassandra is inserted after elasticsearch index creation, the corresponding document  is removed!

How can I force the second behavior for the already inserted data?
Thanks.

**Comment by vroyer** [comment]
Hi,
This was fixed in 5.5.0.9, please upgrade to 5.5.0.10.
thanks.

**Comment by mbammar** [comment]
Yes, the 5.5.0.10 version correct the problem.
Many thanks.
