### ISSUE TITLE
Invalid date mapping

### ISSUE THREAD

**Issue by comdiv** [strapdata/elassandra#163]
**Elasticsearch version**: 5.5.0

**Plugins installed**: []

**JVM version**: 8

**OS version**: 

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. create table with date field
```
create table date_elassandra_test (
	id int primary key,
	somedate date
);
```
2.
create mapping on it
``` 
PUT http://node:9200/myspace/date_elassandra_test/_mapping
{
			"date_elassandra_test": {
				"properties": {
					"somedate": {
						"type": "date",
						"cql_collection": "singleton"
					}
				}
			}
}
```
3. insert some data
`insert into date_elassandra_test (id,somedate) values (1,'2018-02-03');`

4. check search result
```
POST http://node:9200/myspace/date_elassandra_test/_search
```

{
...
"_source": {
	"somedate": "-5877593-07-26T00:00:00.000Z"
}
...
}

As you see - somedate is somehow offseted date for ElasticSearch.

But if TIMESTAMP cassandra type is used instead - all is well

**Comment by vroyer** [comment]
This was fixed in release 5.5.0.11
Thanks for reporting the issue.
