### ISSUE TITLE
Replication settings from Elasticsearch API Or have cluster wide replication settings 

### ISSUE THREAD

**Issue by jasleen1291** [strapdata/elassandra#164]
**Describe the feature**:
We have a specific requirement, we are running a multi DC elassandra cluster, I am able to create a keyspace first and then create elasticsearch index after. But we want to automatically create keyspaces using the Create Index API(Elasticsearch), but I cannot find a setting or config that i can pass in Elasticsearch create index API. Our replication settings are pretty consistent, so a cluster wide setting will be fine too.

**Comment by vroyer** [comment]
Hi,

You can use the ES create API, it automatically creates the underlying keyspace if not exists, and set the replication factor to the ES number_of_replicas +1, only for the local data center.

Here is an exemple :

curl -XPUT $CREDENTIAL "https://$NODE:9200/test" -d'{
    "settings": {
        "keyspace": "test",
        "number_of_replicas" : 2
    },
    "mappings": {
        ...
    }
}'

Then, you should alter your keyspace replication map to replicate on the 2nd DC.
