### ISSUE TITLE
Gradle 4.5.1 - build from Source - buildSrc - Gradle Logging Error

### ISSUE THREAD

**Issue by PenguinRage** [strapdata/elassandra#166]
**Elasticsearch version**:
The one which comes with Elassandra 5.5.0.10

**JVM version**:
java version "1.8.0_152"

**OS version**:
Any, but using 64bit Mac OS X 10.13.3.

**Description of the problem including expected versus actual behavior**:
Expected is straight forward, you would expect it to build.
Actual breaks due to dependencies for buildSrc. The links in the logs return 404.

**Steps to reproduce**:
 1. Install Gradle version 4.5.1
 2. Clone Elassandra
 3. [Follow Build from source install instructions ](http://elassandra.readthedocs.io/en/latest/installation.html)

**Provide logs (if relevant)**:
`gradle assemble --info
Initialized native services in: /Users/iancleasby/.gradle/native
Using 4 worker leases.
Starting Build

> Configure project :buildSrc
Evaluating project ':buildSrc' using build file '/Users/iancleasby/repos/elassandra/buildSrc/build.gradle'.

Selected primary task 'build' from project :
:compileJava (Thread[Task worker for ':buildSrc' Thread 3,5,main]) started.

> Task :buildSrc:compileJava
Resource missing. [HTTP GET: https://jcenter.bintray.com/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.pom]
Resource missing. [HTTP HEAD: https://jcenter.bintray.com/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.jar]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.pom]
Resource missing. [HTTP HEAD: https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.jar]

:compileJava (Thread[Task worker for ':buildSrc' Thread 3,5,main]) completed. Took 6.46 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':buildSrc:compileClasspath'.
> Could not find org.gradle:gradle-logging:4.5.1.
  Searched in the following locations:
      https://jcenter.bintray.com/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.pom
      https://jcenter.bintray.com/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.jar
      https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.pom
      https://repo.maven.apache.org/maven2/org/gradle/gradle-logging/4.5.1/gradle-logging-4.5.1.jar
  Required by:
      project :buildSrc

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
VCS Checkout Cache (/Users/iancleasby/repos/elassandra/.gradle/vcsWorkingDirs) has not been cleaned up in 0 days`

**Comment by vroyer** [comment]
It builds successfully with gradle 3.5, and elastic.co recommend gradle 3.3+ to build elasticsearch 5.5. Have you test elasticsearch + gradle 4.5.1 ?

**Comment by PenguinRage** [comment]
I got it to assemble in the end with Gradle version 4.0.1. The issue which I showed above is that the links above return 404 responses. That being said whilst building my docker image through Jenkins I came across Java dependency hell with a jar called jamm-0.3.0.jar. 😕
