### ISSUE TITLE
ES Date from Cassandra UUID

### ISSUE THREAD

**Issue by lmangani** [strapdata/elassandra#168]
I might be missing something, but it seems currently impossible to extract date/timestamps from Cassandra `timeuuid` fields to be used as dates in ES mapping. Ie function: ````toTimestamp(timeuuid)```` - The field only seems to be supported to string format at this time.

Is this already possible somehow and/or planned for future releases?

Thanks in advance!

**Comment by vroyer** [comment]
Hi Lorenzo,

timeuuid is mapped to string by default, but if you map it to a « date" in your elasticsearch mapping, you should get a date with the elasticsearch API.

Cheers,
Vincent.

**Comment by lmangani** [comment]
Hi Vincent,

I might be off track, this is what I've tried (and failed) with so far:
```
PUT custom_index
{
  "settings": {
    "keyspace": "my_keyspace"
  },
  "mappings": {
    "my_table": {
      "discover": ".*",
      "properties": {
        "uuid": {
          "type": "date"
        }
      }
    }
  }
}
```

UUIDs remain unchanged as strings, and are not eligible for use as timestamp by ES
```
 "uuid": "cc073f2e-110f-11e8-bf2e-000019432987",
```
Mind in Elassandra everything works as expected, only mapping is a challenge. Any suggestion as of how to trigger the `toUnixTimestamp` function and handle UUIDs as dates?

Thanks!

**Comment by vroyer** [comment]
Here is the unit test for that.
-You should have a cassandra column of type timeuuid
-Use a regex to discover all columns but that timeuuid one with something like "^((?!mytimeuuid).*)"


public void testTimes() throws Exception {
        createIndex("test");
        ensureGreen("test");
        
        process(ConsistencyLevel.ONE,"CREATE TABLE test.event_test (id text, start timeuuid, end timeuuid, day date, hour time, PRIMARY KEY (id));");
        assertAcked(client().admin().indices().preparePutMapping("test").setType("event_test")
                .setSource("{ \"event_test\" : { \"discover\" : \"^((?!end).*)\", \"properties\":{ \"end\":{\"type\":\"date\",\"cql_collection\":\"singleton\"}}}}").get());
        
        LocalDate localDate = LocalDate.parse("2010-10-10");
        Instant instant = Instant.from(localDate.atStartOfDay(ZoneId.of("GMT")));
        UUID end = UUIDGen.getTimeUUID(instant.toEpochMilli());
        UUID start = UUIDGen.getTimeUUID();
        
        process(ConsistencyLevel.ONE,"INSERT INTO test.event_test (id , start , end, day, hour) VALUES (?,?,?,?,?)", 
                "1", start, end, SimpleDateSerializer.dateStringToDays("2010-10-10"), 10*3600*1000000000L);
        
        SearchResponse resp = client().prepareSearch().setIndices("test").setTypes("event_test").setQuery(QueryBuilders.queryStringQuery("day:2010-10-10")).get();
        assertThat(resp.getHits().getTotalHits(), equalTo(1L));
        assertThat(resp.getHits().getHits()[0].getSource().get("day"), equalTo("2010-10-10T00:00:00.000Z"));
        assertThat(resp.getHits().getHits()[0].getSource().get("hour"), equalTo(36000000000000L));
        assertThat(resp.getHits().getHits()[0].getSource().get("start"), equalTo(start.toString()));
        assertThat(resp.getHits().getHits()[0].getSource().get("end"), equalTo("2010-10-10T00:00:00.000Z"));
    }
