### ISSUE TITLE
Question about project current state

### ISSUE THREAD

**Issue by dbalabka** [strapdata/elassandra#169]
Could you please clarify what exactly happened with the project in Juny 2017? I see significant decreasing of commits amount starting from that date:
![image](https://user-images.githubusercontent.com/1269372/36256782-0634f7c4-125d-11e8-8222-ce351fa91ac9.png)
Thank you in advance!

**Comment by chokosabe** [comment]
Further to this, any news on when a rc for elasticsearch 6.0 will come out?

**Comment by vroyer** [comment]
Hi,

Elassandra is a fork of Elasticsearch, with significant less commit than the elasticsearch project commits (elassandra is 10k lines of code, versus 1M for ES+C*).
So, you see the easticsearch commits before the fork in july 2017, and few elassandra commit after july 2017.
The next release of elassandra will be a fork of elasticsearch 5.6.6 with all commits of elasticsearch, plus few changes for elassandra….( and then version 6.x…)

Regards.

**Comment by dbalabka** [comment]
@vroyer thanks you very much for the clarification. Now clear about the model of project development.

Unfortunately, it is not visible at first glance, because it is not regular Github fork.
Also, it is not possible to see all main repository contributors, because of commits noise from elasticsearch repository, that gives mistaken impression that project has a lot commits and contributors from elasticsearch repository, but is mostly about how Github statistics :)  
Probably it would be better if elastisearch repo will be included as git submodule, but I'm not sure if it is possible.
