### ISSUE TITLE
Example in Document to insert a document doesn not work.

### ISSUE THREAD

**Issue by ajaybhatnagar** [strapdata/elassandra#173]
**Elassandra 5.5.0.13**:

**None**: []

**1.8.162**:

**Ubuntu 16.04**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.After initial setup and install cqlsh on the node, when example steps are tried Elasticsearch command to insert document worked but cqlsh example for insert fails with error
cqlsh> INSERT INTO twitter.doc ("_id", user, post_date, message) VALUES ( '2', ['Jimmy'], [dateof(now())], ['New data is indexed automatically']);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid list literal for post_date: value dateof(now()) is not of type text"
 2. Are there incompatibility between cqslh version (set to 3.4.4) and Elassandra ?
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by vroyer** [comment]
It seems that's a Cassandra limitation, you cannot use the dateof(now()) inside a list of text. 
Could you check your CQL schema ?
