### ISSUE TITLE
Impact of the search strategy and the consistency level + problem when searching for documents

### ISSUE THREAD

**Issue by prog-toolbox** [strapdata/elassandra#174]
Elassandra : 5.5.0.10

JDK : 1.8

Hello,

I am facing 2 problems in my cluster, which contains  5 nodes : 3 of them running as "Cassandra-Only" Nodes (located in a DataCenter) and the other 2 are running as "Cassandra+Elasticsearch" Nodes (located as well in another DataCenter).
The first problem : I am using **RamdomSearchStrategy** with SearchQueries in Elasticsearch and I am using **QUORUM** as a consistency level in Cassandra : The results of my SearchQueries return an inconsistent number of documents. 
Exemple : 
- First Node "Cassandra + Elasticsearch" : 25002 documents 
- Second Node "Cassandra + Elasticsearch" : 25000 documents 
When I used **LOCAL_ONE** as a consistency level in Cassandra  (with **RamdomSearchStrategy** in Elasticsearch), my problem disappeared and I obtained a consistent number of documents in both nodes.
Could you please explain this behavior ?

The second problem : I launched 2 mass actions simultaneously on a big number of documents, and after that when I searched for the documents which were the target of my mass action, I didn't get the currect result immediately. So after a certain period of time, I relaunched the SearchQuery and I got the correct number of documents, which were modified my mass action.
The scenario I followed :
a - Launching Double Mass Action simultaneously on 25001 documents 
b- Searching for the 25001 with the search criteria that matches my impact on the documents and expecting to have 25001
c- Having only 25000 documents instead 
d- Waiting 1-2 minutes 
e- Relaunching the search for the 25001 documents 
f- Having my 25001 documents which match my impact
I am guessing that this problem is related to the flush mechanism in Elasticsearch.
After a look in Elassandra documentation, I found that the flush mechanism in Cassandra invokes the flush in Elasticsearch, and the default value of **memtable_flush_period_in_ms** in Cassandra is **0**. So I am assuming that the flush in Cassandra Side is immediately invoked, so I am asking is there a way to manage the flush mechanism in Elasticsearch ?
If this problem is not related to the flush mechanism, could you please explain the cause of this latency ?

I appreciate your help.

**Comment by vroyer** [comment]
Hi,
With the default strategy (PrimaryFirst), search is distributed to all nodes in your DC.
With random strategy, your search is distributed to the minimum number of nodes according to your replication factor. So if you have cassandra replication inconsistency, your results may change. You should repair your datacenter and, if it does not fix the issue, rebuild your index on all nodes.

For your second issue, what do you mean by "Double Mass Action", is-it insert ? (how, over CQL or elasticsearch API) ? Could you check that you don't have any running compaction just after mass insert (nodetool compactionstats).
Thanks.

**Comment by prog-toolbox** [comment]
Hello,

Concerning my first question, I am using a **Replication Factor** equal to **2** in both Datacenters, so I was assuming that regardless the value of my consistency level (**QUORUM** or **LOCAL_ONE**), when I will invoke my Elasticsearch Search Query, I will obtain the same result in both nodes "Cassandra+Elasticsearch".

About my second question, my Double Mass Action is composed of update operations over CQL (to be precise : using Spring Data Cassandra). Currently, I am not at the office. Tomorrow, I will repeat the scenario, I will check the compaction and I will send you the results.
Mentioning Spring Data Cassandra opens another question about the **tombstones**. In fact, my colleagues and I found out that running update queries via Spring Data Cassandra creates **tombstones**. However, running Insert queries does not create this problem. The reason for these generated tombstones is when our query (with spring.data.cassandra) is translated to CQL , it will not unset the null values in the update query.
We searched for this issue in Spring community and we found it is mentioned, that it is fixed : 
- https://jira.spring.io/browse/DATACASS-420
- https://github.com/spring-projects/spring-data-cassandra/blob/master/src/main/resources/changelog.txt 
"DATACASS-420 - Literal null values in inserts/updates causing cell tombstones."

After doing our tests, we found out that it is fixed only in Insert operation.
In Elassandra, is there a way or a mechanism to support or to reduce the number of tombstones ? If so, is there any side effects on the performance ?

Thank you for your reply !

**Comment by prog-toolbox** [comment]
I did the test and there are no pending compaction tasks.

**Comment by vroyer** [comment]
Elassandra is cassandra, so inserting null generates tombstones in SSTables and Lucene files.
Be careful, insert becomes visible for search after an elasticsearch refresh, and by default, elasticsearch refresh every seconds, so you should trigger a refresh or wait at least one second.
But finally, what is your issue ?
