### ISSUE TITLE
Search over nested query not able to filter date properly. 

### ISSUE THREAD

**Issue by spendyala** [strapdata/elassandra#175]
**Elasticsearch version**:
```
{
  "name" : "<test>",
  "cluster_name" : "Test",
  "cluster_uuid" : "<test>",
  "version" : {
    "number" : "5.5.0",
    "build_hash" : "9973a5f",
    "build_date" : "2018-02-12T19:39:00.233Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
```

Cassandra: 3.11.1.2

**Plugins installed**: [No]

**JVM version**:
javac 1.8.0_152

**OS version**:
Linux  4.9.77-31.58.amzn1.x86_64 #1 SMP Thu Jan 18 22:15:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
Amazon AMI

**Description of the problem including expected versus actual behavior**:
I am seeing this issue with nested queries with date in elasticsearch.

```
# Type Created using the following
CREATE TYPE db.data_json_type (
    created_date timestamp,
    user_name_id text,
    updated_date timestamp,
    expires_date timestamp
);

# Table Created using the following
CREATE TABLE db.table_1 (
    load_date timestamp,
    user_name_id text,
    data_json frozen<data_json_type>,
    source text,
    date timestamp
)

# Inserted atleast million of records not happening with less than these many records. 
# With the elasticsearch query used to fetch results. 

curl -XPOST 'http://localhost:9200/db/table_1/_search?size=10&pretty' -d '{
    "query": {
        "filtered": {
            "query": {
                "term": {
                    "user_name_id": "<email_address>"
                }
            },
            "filter": {
                "nested": {
                    "path": "data_json",
                    "filter": {
                        "term": {
                            "created_date": "2018-03-12T00:00:00.000Z"
                        }
                    }
                }
            }
        }
    }
}'
```

I see results of users that were created in year 2016, 2017, sometimes even 2010 records. 

**Steps to reproduce**:
 1. Install the elassandra version https://github.com/strapdata/elassandra/releases/tag/v5.5.0.12
 2. Insert at least million of records and continue inserting another million records
 3. While the insertion is happening make the elasticsearch query that was used.

**Comment by vroyer** [comment]
Hi,

Filtered query is deprecated, you should use a bool query with a filter clause (elasticsearch doc says : INCORRECT - DEPRECATED SYNTAX, DO NOT USE)
I you still have an issue with a filtered bool query, please provide some test data in order to reproduce the issue.
Thanks.

**Comment by spendyala** [comment]
```
{
  "query": {
    "nested": {
      "query": {
        "bool": {
          "must": [
            {
              "term": {
                "data_json. user_name_id": "xyz@gmail.com"
              }
            },
            {
              "range": {
                "data_json.created_date": {
                  "gte": "2018-03-18T00:00:00.000+0000"
                }
              }
            }
          ]
        }
      },
      "path": "data_json",
      "score_mode": "avg"
    }
  },
  "size": 15000
}
``` 

Changed query to support boolean. Query without filter still giving wrong results. 

Test data can be user_name_id random emails and createddate timestamps.

**Comment by vroyer** [comment]
Your query was incorrect (erroneous field names) .
Here is the full test (with a correct CQL schema), giving the correct result:

CREATE TYPE db.data_json_type (
    created_date timestamp,
    user_name_id text,
    updated_date timestamp,
    expires_date timestamp
);

CREATE TABLE db.table_1 (
    load_date timestamp,
    user_name_id text primary key,
    data_json frozen<data_json_type>,
    source text,
    date timestamp
);

curl -XPUT "https://$NODE:9200/db/_mapping/table_1" -d '{
 "table_1" : {
 "discover" : ".*"
 }
}'

insert into table_1 (user_name_id, data_json, date, source) VALUES('vroyer',{ created_date:'2018-03-20T00:00:00.000Z', user_name_id:'xyz@gmail.com'}, dateof(now()), 'test');

```
curl -XGET "https://$NODE:9200/db/_search?pretty" -d'
> {
>   "query": {
>     "nested": {
>       "query": {
>         "bool": {
>           "must": [
>             {
>               "term": {
>                 "data_json.user_name_id": "xyz@gmail.com"
>               }
>             },
>             {
>               "range": {
>                 "data_json.created_date": {
>                   "gte": "2018-03-18T00:00:00.000+0000"
>                 }
>               }
>             }
>           ]
>         }
>       },
>       "path": "data_json"
>     }
>   }
> }'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.287682,
    "hits" : [
      {
        "_index" : "db",
        "_type" : "table_1",
        "_id" : "vroyer",
        "_score" : 1.287682,
        "_source" : {
          "date" : "2018-03-22T21:09:49.989Z",
          "user_name_id" : "vroyer",
          "source" : "test",
          "data_json" : {
            "user_name_id" : "xyz@gmail.com",
            "created_date" : "2018-03-20T00:00:00.000Z"
          }
        }
      }
    ]
  }
}
```

**Comment by spendyala** [comment]
Sorry, @vroyer  the error in query is a typo. If you have 1 or two records it works fine. We have 9 nodes and more than 350Million records in cassandra and still seeing this issue. Even though I request to give me records created after 2018-01-01 it throws me results of 2011, 2013, 2014 and 2016 this is random.

**Comment by vroyer** [comment]
Ok, i would be happy to reproduce this issue.
I have added some records not matching the query, and the request still returns correct results. 
 
You didn't mention your primary key in the db.table_1,  did you check that your stress-test does not update documents by re-using an existing primary key ? In this case, you could get matching results before update, but not after when fetching the updated result.

Otherwise, could you provide your CQL schema, the ES mapping,  100-200 rows including wrong results  and your exact query ? (you can use https://github.com/strapdata/cqlkit for a partial export)...

Thanks in advance.
