### ISSUE TITLE
Dynamically Adding Mappings for new Columns from CQL

### ISSUE THREAD

**Issue by LyndonArmitage** [strapdata/elassandra#177]
_This may be related to #52_ 

For my current use case I am evaluating several technologies as a replacement for some rather clunky dynamically created tables in a SQL database. We have a system that currently generates results tables with a varied set of columns based on user selected fields elsewhere in the system, so a column based NoSQL database like Cassandra made sense as a replacement. As a requirement *all* these columns need to support being filtered and sorted on, something Elasticsearch can do. Naturally these requirements led me to Elassandra.

With the current prototype I have based on Cassandra alone I initially create a simple table with some fixed columns used for partitioning and identifying rows.

Below is a simplified example to help illustrate:

```cql
CREATE KEYSPACE IF NOT EXISTS testing WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1' : 3};
CREATE TABLE test (type text, value1 text, PRIMARY KEY (type));
```
After doing this I notice an Elasticsearch is not created, which is normal according to the documentation, so I create one matching the keyspace name, and instruct it to discover the mapping:

```bash
curl -XPUT '172.17.0.3:9200/testing?pretty' -H 'Content-Type: application/json' -d'
{                         
    "settings" : {       
        "index" : {    
            "number_of_shards" : 3, 
            "number_of_replicas" : 2
        }
    }
}
'
```

```bash
curl -XPUT "http://172.17.0.3:9200/testing/_mapping/test" -d '{
    "test" : {
        "discover" : ".*"
    }
}'
```
Currently I have no documents in Elasticsearch or rows in the table so I insert one:

```cql
INSERT INTO testing.test (type, value1) VALUES ( 'test0', 'valuess');
```

This works fine and creates a new item in the table and index.

Now here comes my question: 
I now want to add a value with a new column in it, so I add the column in CQL:

```cql
ALTER TABLE testing.test ADD value2 int;
```

Now the column is in the table but not indexed in the Elasticsearch index, so when I come to add a new value in CQL:

```cql
INSERT INTO testing.test (type , value1 , value2 ) VALUES ( 'test1', 'a', 1);
```

The value1 and type columns are indexed in Elasticsearch but not value2 (as it is not mapped).

In order to get it mapped I would need to discover/add the mapping manually and recreate the index using the nodetool:

```bash
curl -XPUT "http://172.17.0.3:9200/testing/_mapping/test" -d '{
    "test" : {
        "discover" : ".*"
    }
}'

# Then on the Elassandra server:
nodetool rebuild_index --threads 2 testing test elastic_test_idx
```

Or add the mapping at the same time as adding the new column before adding the new data.

My question is:

Is there a way of getting Elassandra to do both when I execute the ALTER TABLE command? 
As it seems a bit cumbersome to have to both communicate with Elasticsearch and Cassandra to do this.

If the case is that you currently have to do both, is there any chance you could add it as a potential improvement?
I am not super familiar with Cassandra but some way of telling it to trigger Elasticsearch indexing of the new column would be great.

**Comment by vroyer** [comment]
Hi Lyndon,

You’ve done right ! If you want to update the elasticsearch mapping and the CQL schema at the same time, you could :
1. Explicitly set a « value2 » field in a full mapping update request, then elassandra automatically updates the underlying CQL schema.
2. Or, insert a JSON document with a « value2 » field, and the elasticsearch dynamic mapping automatically update the elasticsearch mapping and underlying CQL schema.
In both cases, index rebuild becomes useless because cassandra write including « value2 » happens after the mapping update, so field is indexed.
Hope this helps.

**Comment by LyndonArmitage** [comment]
Thank you for the quick and useful reply Vincent!

From the look of it, for my use case for ease of use I might want to consider creating the table using CQL and then do all the inserts using the Elasticsearch APIs due to the variable columns and how they'll be added as per your 2nd point. This seems sensible to me and also means that for some testing I can potentially not require an Elessandra instance to be running and instead use an in-process Elasticsearch instance with reduced and simple test data.

### Testing

I ran a test using my example and following your 2nd suggestions; I created the keyspace and table anew and added 2 pieces of test data to the table via CQL (after discovering the original mapping):

```cql
CREATE TABLE test (type text, value1 text, PRIMARY KEY (type));
-- Before doing the inserts I made sure the Elasticsearch index existed and was mapped
INSERT INTO test(type , value1 ) VALUES ( 'test1', 'abc');
INSERT INTO test(type , value1 ) VALUES ( 'test2', 'efg');
```
This added the 2 documents to Elasticsearch as expected. I then tested adding a result with a new field using the Elasticsearch API:

```bash
curl -XPOST 'http://172.17.0.3:9200/testing/test/?pretty' -H 'Content-Type: application/json' -d'
{
    "type" : "test3",
    "value1": "d",
    "value2": 43 
}
'
```

This worked and added the mapping as you said it would, and the result was present in the table:

```cql
SELECT * FROM test;

 type                 | value1 | value2
----------------------+--------+--------
 AWJSPvkTYWGjyeM5y0pm |      d |   [43]
                test2 |    efg |   null
                test1 |    abc |   null

(3 rows)
```

However as you can see it used a generated ID instead of the field value for type, is this intended behaviour? I know [Elasticsearch generates an ID](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-index_.html#_automatic_id_generation) for documents when performing the POST request I made. From a quick search and look at documentation it seems like this the value for the [_id field](http://nocf-www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-id-field.html) in Elasticsearch and in older version of Elasticsearch up to 1.7 you could map _id to a field on your document but this has been removed since 2.0. So will I need to strictly specify the id of my Elasticsearch documents? 

My current actual table has a composite primary key with 2 parts in it's partition key and 2 parts in it's clustering key like so: 

```cql
CREATE TABLE test2 (
  part1 text, 
  part2 text, 
  cluster1 text, 
  cluster2 text, 
  value1 text,
  PRIMARY KEY ((part1, part2), cluster1, cluster2)
);
```
Going through similar steps to above if create the table and make sure the mapping is correct, then add a value in CQL it works as expected:

```cql
INSERT INTO test2 (part1, part2, cluster1, cluster2, value1) VALUES ( 'a', 'b', 'c', 'd', 'value');
SELECT * FROM test2;

 part1 | part2 | cluster1 | cluster2 | value1
-------+-------+----------+----------+--------
     a |     b |        c |        d |  value
``` 
Then when I add a value via Elaticsearch:

```bash
curl -XPOST 'http://172.17.0.3:9200/testing/test2/?pretty' -H 'Content-Type: application/json' -d'
{
    "part1" : "1",
    "part2": "2",
    "cluster1": "1", 
    "cluster2": "2", 
    "value1": "abc"
}
'
```
Part of the partition key is replaced with a generated value:

```cql
SELECT * FROM test2;

 part1                | part2 | cluster1 | cluster2 | value1
----------------------+-------+----------+----------+--------
 AWJSbro3YWGjyeM5y0pr |     2 |        1 |        2 |    abc
                    a |     b |        c |        d |  value

(2 rows)
```

### Separate Suggestion

Another question; as a future enhancement would it be possible to have this kind of functionality in reverse? So an `ALTER TABLE` CQL statement for adding a new column would trigger a new field to be created in the Elasticsearch type mapping? Perhaps a setting on the table in CQL that would trigger a request to the index to discover the mapping for new fields?

I hope this project does well as it is definitely a good way of getting the best features of both Cassandra and Elasticsearch working together!

**Comment by vroyer** [comment]
Hi,
As explained [here](http://elassandra.readthedocs.io/en/latest/mapping.html?highlight=compound%20key#meta-fields), the elasticsearch _id can be a cassandra composite key. Moreover, by default, when _id is not a JSON array, _id is affected to the first partition key column as in your exemple. 

For the second question, triggering a mapping update from CQL is not currently possible, mainly because triggering a PAXOS transaction inside a CQL schema update could be very tricky.

**Comment by LyndonArmitage** [comment]
Thanks Vincent! Apologies for the delayed reply. 

It might be worth documenting that part of the `_id` and consequently part of the Cassandra primary key will use an Elasticsearch generated value when being indexed via Elasticsearch as this is potentially surprising behaviour. It might be covered elsewhere in the documentation but it would be worth a note there again.

For now, and anyone else reading this; if you manually set the `_id` of your documents during indexing everything works fine, for this example given you'd want to set it to a JSON array with the parts of the primary key in it in order. Similar to the get request @vroyer references in his above comment: https://elassandra.readthedocs.io/en/latest/mapping.html#meta-fields
