### ISSUE TITLE
TTL problem : Records deleted completely from Cassandra, partially from Elasticsearch

### ISSUE THREAD

**Issue by prog-toolbox** [strapdata/elassandra#180]
Elassandra : 5.5.0.10

JDK : 1.8

Hello,

I am facing a problem when deleting rows using TTL. In fact, data is deleted only in Cassandra, but in Elasticsearch, it is not completely deleted. Only the "_source" field is deleted, but the  "_id" field remains in the document.
This issue was already fixed by moving to Elassandra 5.5.0.10, which is my current version : 
https://github.com/strapdata/elassandra/issues/160

I appreciate your help.

**Comment by vroyer** [comment]
In elassandra, elasticsearch TTL service is disabled and elasticsearch document are removed only when compacting SSTables. You should use a partition function to index your cassandra rows in several time-framed indices. Then, remove obsolete indices before C* TTL expire.
