### ISSUE TITLE
Elassandra high CPU usage due to translog flush

### ISSUE THREAD

**Issue by krishkoneru** [strapdata/elassandra#184]
Elassandra version:
Elassandra 5.5.0.13
Plugins installed: [None]

JVM version:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

OS version:
Debian Jessie Docker Container running in CoreOs

**Description of the problem including expected versus actual behavior**:

Elassandra consumes around 50% CPU with very less load. After further investigation using Hot threads API, it looks like **flush** threads are using lots of CPU. Since elasticsearch translogs are disabled in elassandra, should these threads be running at all? 

[Output of hot threads](https://gist.github.com/krishna-koneru/6ce87a6a68504d0c1be63dcd3216baa0)

To support this theory, CPU usage goes down from ~50% to less than 10% if the index translog settings are changed to the following :
```
index.translog.durability: "async" 
index.translog.sync_interval: "300s"
```
Do you foresee any issues with using the above settings for all the indexes ?

**Steps to reproduce**:
 1. Start Elassandra Cluster
 2. Start writing indexing requests for ~20 minutes
 3. Check hot threads using Elasticsearch API: GET _nodes/hot_threads

**Comment by vroyer** [comment]
Hi,

There is running cassandra compactions in your thread output, and probably lucene merge (SSTTable compaction and Lucene merge are quite similar).
After 20 min writing, you had some running cassandra compactions (check with nodetool compactionstats) involving elasticsearch flush operations. 

Changing index.translog parameters should not have any impact, because translog write is disabled in elassandra (persistency is ensured by cassandra commitlogs), but of course, refresh and flush operations stil occurs to write lucene files.
Did you run exactly the same scenario with and without these index.translog parameters, or just change these after the compaction occurs ?

Regards.

**Comment by krishkoneru** [comment]
Hi Vincent, 

Yes, I ran the test with and without these settings several times on a cluster that has been running for more than a week and I always saw decrease in CPU usage when translog settings are changed.

However, I did not immediately see the CPU increase on new cluster. I saw the increase in CPU after 2-3 hours. And the cpu usage decreased immediately after I changed the translog settings. Do you have any idea what might be causing this ? 

I am attaching the graph of cpu usage. 

![screen shot 2018-04-13 at 10 47 08 am](https://user-images.githubusercontent.com/29242836/38711696-a3894992-3f0a-11e8-8377-9e37f575b604.png)

In this test two indexes are used. 

Before 00:00 writes were happening to **index-a** which had above translog settings already applied. (cpu around 15%) 

Starting at 00:00 all the writes (same load as on index-a) go to the new index **index-b** (index-a does not get writes anymore). This index does **not** have any translog settings modified. (cpu usage goes up 45% after ~10 mins at around 00:10). Slight increase in write latencies as well.

At around 00:35 , I have changed the translog settings of **index-b** (no change in load). 
```curl -XPUT localhost:9200/index-b/_settings -d '{ "index.translog.durability": "async" }' ```
I observed immediate drop in CPU usage and write latencies also dropped. CPU usage went back to 10%.

**Comment by vroyer** [comment]
Hi,
Thanks a lot for your report.
The translog sync() method is dummy but the translog flush thread is still running for nothing.
I have released a patch to disable the translog flush thread, available for pre-view at https://github.com/strapdata/elassandra5-rc/commit/293c8363000d0b3e1afb54002ea9d3034892df82 <https://github.com/strapdata/elassandra5-rc/commit/293c8363000d0b3e1afb54002ea9d3034892df82>
Could you check from https://github.com/strapdata/elassandra5-rc <https://github.com/strapdata/elassandra5-rc>  that it fixes your issue ?
Thanks.

**Comment by vroyer** [comment]
Hi,
I didn't managed to reproduce your issue in my environment (centos vm+elassandra 5.5.0.13).
Could you confirm that the RC release 5.5.0.14 resolv this CPU overhead ?
Thanks in advance.

**Comment by krishkoneru** [comment]
Hi , 

Thanks a lot for the patch ! 
I did not get a chance to test the patch yet. I will let you know if I test it.
