### ISSUE TITLE
map<text, udt> unable to query from elastic search

### ISSUE THREAD

**Issue by githubuser25** [strapdata/elassandra#185]
Can not query the map key or udt from elastic search. The document says a map must have a text key but does not specify the value type. It actually shows map<text, ?> so I assume this means udts are supported.

1. Create udt
2. Create table with map<text, udt>
3. index this in elastic search
4. the map data is displayed properly but unable to query
5. doing the same above with map<text, text> works properly as expected

**Comment by vroyer** [comment]
This is not currently supported, but a keep your request for further improvement.
Thanks.

**Comment by vroyer** [comment]
This comes with the next release 6.2.3.10.
Thanks for reporting the issue.
