### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by cevalogistics** [strapdata/elassandra#186]
Elassandra 5.5.0.13

I just read the Authentication section in your guide.  I am interested in using LDAP for authentication.  Can you recommend something that will work with what you support?

**Comment by vroyer** [comment]
As far as i know, there is no opensource ldap connector for cassandra, but that is something we could develop.

**Comment by cevalogistics** [comment]
Thanks.  We will probably work on something.  If we do we will contribute.
