### ISSUE TITLE
row removed in cassandra, but the the corresponding document not removed from Elasticsearch

### ISSUE THREAD

**Issue by RachidKraiem** [strapdata/elassandra#187]
**Elassandra version**: 5.5.0.10

**JVM version**: JDK 1.8

**OS version**: CentOS release 6.5 (Final)

**Description of the problem including expected versus actual behavior**:
I have two data center elassandra which 3 nodes started as "bin/cassandra" and 2 other nodes started as "bin/cassandra -e"

I have the following random problem: sometimes when deletion a row within cql command the row seems deleted successfully from cassandra , but when executing elasticsearch search query the deleted document already exists without _source document  as documents "xxxxx" and "yyyyy" as follow:

QUERY GET : my_index/_search
RESULT:
{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 6,
    "max_score": 1,
    "hits": [
      {
        "_index": "my_index",
        "_type": "my_type",
        "_id": "test_1",
        "_score": 1,
        "_source": {
          "field_id": "test_1",
          "field2": "description 1"
        }
      },
      {
        "_index": "my_index",
        "_type": "my_type",
        "_id": "test",
        "_score": 1,
        "_source": {
          "field_id": "test"
        }
      },
      {
        "_index": "my_index",
        "_type": "my_type",
        "_id": "test_3",
        "_score": 1,
        "_source": {
          "field_id": "test_3",
          "field2": "description 3"
        }
      },
      {
        "_index": "my_index",
        "_type": "my_type",
        "_id": "test_4",
        "_score": 1,
        "_source": {
          "field_id": "test_4",
          "field2": "description 4"
        }
      },
      {
        "_index": "my_index",
        "_type": "my_type",
        "_id": "xxxxx",
        "_score": 1
      },
      {
        "_index": "my_index",
        "_type": "my_type",
        "_id": "yyyyy",
        "_score": 1
      }
    ]
  }
}

**Comment by vroyer** [comment]
Could you share your CQL schema and ES mapping to reproduce your issue.
Thanks.

**Comment by RachidKraiem** [comment]
Thanks for reply.

**CQL schema::**

cqlsh:my_keyspace> desc table "my_table"

CREATE TABLE my_keyspace.my_table (
    field_id text PRIMARY KEY,
    field2 text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_my_table_idx ON my_keyspace.my_table () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';


**ES mapping::**

curl 'http://host:9200/my_index' -S -X PUT -H 'Content-Type: application/json' --data-binary '{"settings" : { "index.search_strategy_class":"RandomSearchStrategy" , "keyspace" : "my_keyspace","analysis": {"analyzer": {"analyzer_whitespace_separator": {"type": "custom","filter": ["lowercase"],"tokenizer": "whitespace"}}}  } }'

curl 'http://host:9200/my_index/_mapping/my_type' -S -X PUT -H 'Content-Type: application/json' --data-binary @mapping.json

**the content of mapping.json file as follow:**

{
	"my_type": {
		"properties": {
			"field2": {
				"type": "text",
				"index": "analyzed",
				"analyzer": "analyzer_whitespace_separator",
				"cql_collection": "singleton"
			},
			"field_id": {
				"type": "text",
				"index": "analyzed",
				"analyzer": "analyzer_whitespace_separator",
				"cql_collection": "singleton",
				"cql_partition_key": true,
				"cql_primary_key_order": 0
			}
		}
	}
}

**Finally:**

curl 'http://host:9200/_aliases' -S -X POST -d  '{"actions" : [{ "add" : { "index" : "my_index", "alias" : "my_table" } }]}'

**Comment by RachidKraiem** [comment]
Moreover, anormal behaviour when executing a post query search under elasticsearch-cassandra node, we have a follow result. However "field_id" is not exists in the last two documents ! (documents without _source)

**QUERY POST :** my_index/_search
{
    "query": {
        "exists" : { "field" : "field_id" }
    }
}

**RESULT :** 

{
"took": 5,
"timed_out": false,
"_shards": {
"total": 1,
"successful": 1,
"failed": 0
},
"hits": {
"total": 6,
"max_score": 1,
"hits": [
{
"_index": "my_index",
"_type": "my_type",
"_id": "test_1",
"_score": 1,
"_source": {
"field_id": "test_1",
"field2": "description 1"
}
},
{
"_index": "my_index",
"_type": "my_type",
"_id": "test",
"_score": 1,
"_source": {
"field_id": "test"
}
},
{
"_index": "my_index",
"_type": "my_type",
"_id": "test_3",
"_score": 1,
"_source": {
"field_id": "test_3",
"field2": "description 3"
}
},
{
"_index": "my_index",
"_type": "my_type",
"_id": "test_4",
"_score": 1,
"_source": {
"field_id": "test_4",
"field2": "description 4"
}
},
{
"_index": "my_index",
"_type": "my_type",
"_id": "xxxxx",
"_score": 1
},
{
"_index": "my_index",
"_type": "my_type",
"_id": "yyyyy",
"_score": 1
}
]
}
}


Do you have an explanation for this behavior ?

**Comment by vroyer** [comment]
For some reason, the delete documents are still indexed in elasticsearch, so the exists query also returns docs xxxx and yyyyy, but cannot fetch the documents from the cassandra table, and _source is empty.
Could you upgrade to 5.5.0.14 and reproduce the issue ?
Thanks.

**Comment by vroyer** [comment]
Hi Rachid,
I did not succeed to reproduce your issue, and in my environment, this works fine (2 nodes in 2 datacenters DC1+DC2). You have probably deleted docs xxxx and yyyy while elasticsearch was disabled and re-enabled it later does not replay deletion for elasticsearch. 

Insert/Delete can be eventually replayed if present in the commitlogs when you restart your node, but you'll get a random behavior depending on flush events. 

So, to fix this kind of situation, delete your index, re-create-it and rebuild-it (nodetool rebuild_index).
Thanks.

**Comment by RachidKraiem** [comment]
Hi Vincent,

The issue seems critical mainly in pre-production environment of my client, and i cannot systematically delete the index, re-create-it and rebuild-it in order to fix this random behavior.
Can you delivery a patch for 5.5.0.14 ?

**To note that elasticsearch node was not disabled and re-enabled.**
Thanks.

**Comment by vroyer** [comment]
Hi Rachid,
I would be happy to reproduce it and to fix it.
Do you have any WARN or ERROR messages in the logs of the 2 nodes running elasticsearch ?
Do you close/open indexe or had a file system full ?
Would you have the full CQL schema including the keyspace definition and the full elasticsearch cluster state ?
Thanks.

**Comment by vroyer** [comment]
Hi Rachid.
Here is a new release candidate 5.5.0.16 https://github.com/strapdata/elassandra5-rc/releases with some refactoring of delete operations. It could solve your issue or at least add traces about failed document delete.
Otherwise, would you accept to do an hangout call conf or provide a temporary ssh access to audit your configuration ?
Thanks.

**Comment by RachidKraiem** [comment]
Hi Vincent,
Thanks for your involvement and your prompt reply.
We will try this new version and hoping it solves the problem. Moreover i join the configuration of my cluster elassandra.
To note that we deleted **cassandra-topology.properties** file from each node in order to use **GossipingPropertyFileSnitch**.

The log file seems clean except for some warnings (you will find them attached).

Best regards.
[configuration&logs.zip](https://github.com/strapdata/elassandra/files/1991759/configuration.logs.zip)

**Comment by vroyer** [comment]
Thanks for your logs and configuration files. 
It seems than several system requirements are not correct (JNA, jemalloc, rlimit).
I would need your CQL schema `cqlsh>DESC KEYSPACE my_keyspace;` and your elasticsearch cluster state `curl -XGET http://<ip>:9200/_cluster/state/?pretty=true`.
Thanks.

**Comment by vroyer** [comment]
Hi Rachid,
I have generated a new elassandra 5.5.0.16 release-candidate including some improvements that could explain your issue.  Thanks in advance for your feed-back with that release.
Regards.
