### ISSUE TITLE
Missing Transport Client Dependencies

### ISSUE THREAD

**Issue by LyndonArmitage** [strapdata/elassandra#192]
When attempting to use the Shaded Elasticsearch Transport client provided by the following dependency:

```xml
<dependency>
    <groupId>com.strapdata.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>5.5.0</version>
</dependency>
```

You encounter the following when trying to perform a `mvn clean package`:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building elassaandra-bug 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.strapdata.elasticsearch.plugin:transport-netty3-client:jar:5.5.0 is missing, no dependency information available
[WARNING] The POM for com.strapdata.elasticsearch.plugin:transport-netty4-client:jar:5.5.0 is missing, no dependency information available
[WARNING] The POM for com.strapdata.elasticsearch.plugin:reindex-client:jar:5.5.0 is missing, no dependency information available
[WARNING] The POM for com.strapdata.elasticsearch.plugin:lang-mustache-client:jar:5.5.0 is missing, no dependency information available
[WARNING] The POM for com.strapdata.elasticsearch.plugin:percolator-client:jar:5.5.0 is missing, no dependency information available
[WARNING] The POM for com.strapdata.elasticsearch.plugin:parent-join-client:jar:5.5.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.599 s
[INFO] Finished at: 2018-05-10T10:35:11+01:00
[INFO] Final Memory: 14M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project elassaandra-bug: Could not resolve dependencies for project com.example.elassandra:elassaandra-bug:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: com.strapdata.elasticsearch.plugin:transport-netty3-client:jar:5.5.0, com.strapdata.elasticsearch.plugin:transport-netty4-client:jar:5.5.0, com.strapdata.elasticsearch.plugin:reindex-client:jar:5.5.0, com.strapdata.elasticsearch.plugin:lang-mustache-client:jar:5.5.0, com.strapdata.elasticsearch.plugin:percolator-client:jar:5.5.0, com.strapdata.elasticsearch.plugin:parent-join-client:jar:5.5.0: Failure to find com.strapdata.elasticsearch.plugin:transport-netty3-client:jar:5.5.0 in http://nexus.technotomy.com/content/groups/allrepos was cached in the local repository, resolution will not be reattempted until the update interval of home has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Upon inspection it appears that the following compile dependencies are not included in the central maven repository:
![image](https://user-images.githubusercontent.com/2650636/39863492-ac0262ea-543e-11e8-9b1a-7246b6cf2fdb.png)

Is this intentional?

If you want to perform operations using the Elasticsearch transport client on Elassandra which client library should you be using? The shaded one or the original from Elasticsearch? Or should we be excluding those dependencies and be using original Elasticaearch versions?

There isn't any mention of how to use a Transport client outside of the [Enterprise section](https://elassandra.readthedocs.io/en/latest/enterprise.html#secured-transport-client) within the documentation, which mentions a secured Transport client being provided by Strapdata, with the class of `com.strapdata.elasticsearch.plugins.ssl.PreBuiltSslTransportClient`. The client provided by the shaded transport client dependency matches Elasticsearch's original `org.elasticsearch.client.transport.TransportClient`.

Previously when using the Transport client I have run into issues to do with binary incompatibilities between server and client when minor/patch versions differed (admittedly this was with the Elasticsearch 2.X.X versions), and assumed that the shaded client was provided because of potential issues with any changes you have made.

**Comment by vroyer** [comment]
Yes, the issue is that we cannot append a digit to the elasticsearch version number in order to publish our releases because plugins' version must match elasticsearch version.

The workaround is to install locally strapdata artifacts in your maven repository to build your projects. Just clone the elassandra project (with --recurse-submodules), and run:

` gradle publishToMavenLocal -Dbuild.snapshot=false -Dmaven.repo.local=/Users/xxxxx/.m2/repository `
