### ISSUE TITLE
Delete and search issue 

### ISSUE THREAD

**Issue by prog-toolbox** [strapdata/elassandra#194]
**Elassandra : 5.5.0.10**

**JDK : 1.8**

Hello, 

I am facing 2 problems in my cluster, which contains 5 nodes : 3 of them running as "Cassandra-Only" Nodes (located in a DataCenter) and the other 2 are running as "Cassandra+Elasticsearch" Nodes (located as well in another DataCenter).
The first issue: 
I was searching for specific documents with Elasticsearch and I am trying to delete them with Cassandra.
I was able to delete 25020 of my 25021 documents. The structure of the last document was odd. In fact, I found out that the  **null** value was set into the **second part of its primary key** (a Compound key with 2 fields) and other fields as well, including the field that I am using to search for the documents.
So now, I cannot delete this row.

The second issue (continuously with the first one):
I tried to execute another Elasticsearch query combining **must_not** and **exists**, in order to retrieve that document (the remaining one from the first issue) and eventually to delete it. My request did not return anything.
I tried the same request with an ordinary Elasticsearch cluster and it worked properly:
 
{
  "query":
	{ 
  	   "bool" : { 
   		 "must_not" : 
            {
            "exists" : {
            "field" : "my_field"
            }
        }
     }
   }
}

What are the causes of these problems ?

I appreciate your help.

**Comment by vroyer** [comment]
Hi,

Could you please update to 5.5.0.16, there are improvements related to row deletion.
You can quickly update your nodes by copying the 5.5.0.16 lib/elasticsearch-5.5.0.jar to your current elassandra lib directory and restart.

Then, if you still face an issue, please describe how you have deleted your rows and provide both the output of a CQL select and ES search queries.
Thanks in advance.
