### ISSUE TITLE
Strange problems while inserting via REST

### ISSUE THREAD

**Issue by cevalogistics** [strapdata/elassandra#195]
**Elassandra version**:
5.5.0.16
**Plugins installed**: []

**JVM version**:
8
**OS version**:
Kubernetes
**Description of the problem including expected versus actual behavior**:

Today I enabled the fluentd logging in Kubernetes and pointed it to elassandra.  It is logging an incredible number of records and seems to be working properly.

While that is running we connected with a different client and started receiving log messages like the one below.  If I stop the fluentd and restart the client, it still fails until we drop/recreate the keyspace.  I am not 100% sure on this but we tried it twice with the same result.  We saw something in the client and it mentioned the bulk queue is full when we researched on Google.  I am thinking it might be a tune as opposed to it's some kind of bug.  Any Ideas?

 
--

  | May 21st 2018, 18:09:29.000 | - | 2018-05-21 22:09:29,018 WARN  [elasticsearch[10.233.97.160][bulk][T#1]] org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishWithUnexpectedFailure(TransportReplicationAction.java:859) unexpected error during the primary phase for action [indices:data/write/bulk[s]], request [BulkShardRequest [[matrixuser][0]] containing [index {[matrixuser][matrixuser][201602kjonesx], source[{"Pkey":"201602kjonesx","Date":"2016-02-01","Business_Unit_ID":155,"Business_Unit_Name":"Honda Shared Network","Segment":"TMS","User_ID":"kjones","Role_Type":" n\/a","Cluster":"North America","Country":"UNITED STATES"}]}]]

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.primary(TransportReplicationAction.java:738)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retry(TransportReplicationAction.java:827)

  | May 21st 2018, 18:09:29.000 | - | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

  | May 21st 2018, 18:09:29.000 | - | at java.lang.Thread.run(Thread.java:748)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:70)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:112)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:104)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1183)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onFailure(TransportReplicationAction.java:349)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:667)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:140)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:112)

  | May 21st 2018, 18:09:29.000 | - | org.elasticsearch.index.IndexNotFoundException: no such index

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:104)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1079)

  | May 21st 2018, 18:09:29.000 | - | at java.lang.Thread.run(Thread.java:748)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onFailure(TransportReplicationAction.java:349)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:293)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleException(TransportReplicationAction.java:806)

  | May 21st 2018, 18:09:29.000 | - | org.elasticsearch.index.IndexNotFoundException: no such index

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.primary(TransportReplicationAction.java:738)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleException(TransportReplicationAction.java:806)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:293)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)

  | May 21st 2018, 18:09:29.000 | - | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:667)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:140)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:252)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:667)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:140)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:104)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:70)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1161)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:252)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)

  | May 21st 2018, 18:09:29.000 | - | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:312)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleException(TransportReplicationAction.java:806)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1079)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1183)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.cluster.routing.RoutingTable.shardRoutingTable(RoutingTable.java:141)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)

  | May 21st 2018, 18:09:29.000 | - | at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656)

  | May 21st 2018, 18:09:29.000 | - | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by vroyer** [comment]
Hi,
This happen in a race condition with cluster state update and has already been fixed in version 6.2.3.1. This fix is currently tested on version 5.5.0 and is available in on the master branch of [https://github.com/strapdata/elassandra5-rc](https://github.com/strapdata/elassandra5-rc) for non-regression tests. 
Thanks.

**Comment by cevalogistics** [comment]
Vincent,

Is it built on 5.5.0.16 or do I need to build it?

Best regards,

Bob Liotta
SVP IT Enterprise Architect

CEVA Logistics / 10751 Deerwood Park, Blvd, Jacksonville, FL 32256 / www.cevalogistics.com<http://www.cevalogistics.com>
O: +1 904.928.2322 / E: robert.liotta@cevalogistics.com<mailto:robert.liotta@cevalogistics.com>

Making business flow

**Comment by vroyer** [comment]
Hi Bob,

Yes, the build and publication process currently on going  to release the next version 5.5.0.17 for tomorrow, but right now, you should rebuild from the master branch of https://github.com/strapdata/elassandra5-rc to include the last fix.

git clone --recurse-submodules https://github.com/strapdata/elassandra5-rc
cd elassandra5-rc
gradle distribution:tar:assemble -Dbuild.snapshot=false

Then, for a light-weight deployment, you can copy the built file core/build/distributions/elasticsearch-5.5.0.jar to the <elassandra>/lib directory of your running nodes, and restart.

**Comment by vroyer** [comment]
Hi Bob,

Release 5.5.0.17 including the fix is now available for download on github.
Thanks.

Vincent.

**Comment by cevalogistics** [comment]
Vincent,

Great.  I will let you know….

BTW.  Regarding the license, I sent a reply, can you please comment?

Best regards,

Bob Liotta
SVP IT Enterprise Architect

CEVA Logistics / 10751 Deerwood Park, Blvd, Jacksonville, FL 32256 / www.cevalogistics.com<http://www.cevalogistics.com>
O: +1 904.928.2322 / E: robert.liotta@cevalogistics.com<mailto:robert.liotta@cevalogistics.com>

Making business flow
