### ISSUE TITLE
Closing instance with nodetool 

### ISSUE THREAD

**Issue by charles-paperman** [strapdata/elassandra#196]
**Elassandra version**: 5.5.0.15

**Plugins installed**: []

**JVM version**: openjdk version "1.8.0_151"

**OS version**: Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Closing elassandra instance with 
`bin/nodetool stopdaemon`
is not closing cassandra instances. Access ports to cassandra and elasticsearch are unbind.

**Steps to reproduce**:
 1. bin/cassandra -e
 2. bin/nodetool stopdaemon  (no output)
 3. bin/cassandra -e (seems to work)
 4. bin/nodetool status 
get: 
Failed to connect to '127.0.0.1:7199' - NotSerializableException: 'javax.management.remote.rmi.RMIJRMPServerImpl'.
 

**Provide elasticsearch cluster state**:

**Provide user CQL schema**:

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by vroyer** [comment]
Hi Charles,
If you stop your cassandra instance like step 2, it may take a while to properly stop your node, and when stopped, step 4 works as expected (it fails to connect to your stopped node).

Finally, you should find these messages in your cassandra logs:
2018-05-25 11:39:19,263 INFO  [RMI TCP Connection(4)-127.0.0.1] CassandraDaemon.java:549 stop Cassandra shutting down...
2018-05-25 11:39:19,268 INFO  [RMI TCP Connection(4)-127.0.0.1] Server.java:176 close Stop listening for CQL clients

Thanks.
Vincent.
