### ISSUE TITLE
Support ElasticSearch Range data types

### ISSUE THREAD

**Issue by ccackerman** [strapdata/elassandra#201]
### New Feature Request: Support ElasticSearch Range  data types
I have a use case that would benefit from efficient indexing of date ranges (trajectory histories of moving objects). I see that ElasticSearch provides this as one of its **Range data types**, see <https://www.elastic.co/guide/en/elasticsearch/reference/5.5/range.html>.
Since Cassandra does not have an equivalent type for direct mapping, would it be possible to support range types via specific Cassandra UDTs in a way similar to **geo_point**?

**Comment by vroyer** [comment]
Yes, it is possible, in a similar way to **geo_point**.  I keep your request for a future release.

**Comment by vroyer** [comment]
Range fields are now supported by Elassandra in release 6.2.3.18.
