### ISSUE TITLE
How disk space is used and how data are distributed between nodes?

### ISSUE THREAD

**Issue by Gappa88** [strapdata/elassandra#205]
hi,

I'm using **Elassandra 6.2.3.1**.

I have set a cluster of 3 nodes and created a keyspace, via cqlsh, and indexed it into Elasticsearch.

I need to know how Elassandra uses disk space and distributes data along the cluster's nodes. I started from [here](https://github.com/strapdata/elassandra/issues/27#issuecomment-229510232) 

> For write, elassandra write throughput is roughly half the throughput of cassandra if you index all columns. In this scenario, Cassandra and Elasticsearch files with be roughly the same size, for example 100Gb of cassandra data generates 100Gb of elasticsearch index files if you map all columns, but again, write throughput and elasticsearch disk usage will depend on your elasticsearch mapping.

but I cannot have a match in my case.

In details, how can I find out :
1. How much disk space is occupied by Elassandra within a node? May I use `du -sh /var/lib/cassandra` to find this out?
2. `nodetool status keyspace` tells me how much disk space is used only by Cassandra or by Elassandra? I mean, `nodetool `has been modified in order to provide the amout of disk usage of **cassandra+elasticsearch** or it gives only the amount of disk usage of **cassandra**?
3. as the previous question: `GET _cat/allocation?v` tells me how much disk space is used only by **Elasticsearch** or by **Elassandra**?

I have also a strange behaviour about data distribution:
```
$ nodetool status mykeyspace
Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.8.0.14  12.47 GiB  8            49.6%             c5a17dbd-40ef-4f58-b132-0d977a92f1a1  r1
UN  10.8.0.1   17.55 GiB  8            64.2%             f088d009-bd97-4e35-9f20-60006a68b363  r1
UN  10.8.0.6   33.49 GiB  8            86.1%             e82191ad-9d9f-459f-9da0-2b0457ad6611  r1
```
**Why one node has the double of the disk usage than other 2 nodes?**

Here some information about the structure:

`CREATE KEYSPACE mykeyspace WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '2'}  AND durable_writes = true;`

```
DESC mykeyspace;
CREATE TABLE mykeyspace.mytable(
    f1 text,
    f2 timestamp,
    f3 text,
    f4 text,
    f5 int,
    PRIMARY KEY (f1, f2)
) WITH CLUSTERING ORDER BY (f2 DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_mytable_idx ON mykeyspace.mytable () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';
```

any other information that allow me to understand how data are distributed and how are stored by Elassandra are very appreciated.

Thank you

EDIT:
```
GET _cat/allocation?v
shards disk.indices disk.used disk.avail disk.total disk.percent host      ip        node
     1        5.5gb   478.4gb    430.7gb    909.1gb           52 10.8.0.14 10.8.0.14 10.8.0.14
     1       12.7gb    64.6gb       11gb     75.7gb           85 10.8.0.6  10.8.0.6  10.8.0.6
     1        6.8gb    40.5gb     21.2gb     61.7gb           65 10.8.0.1  10.8.0.1  10.8.0.1
```

**Comment by vroyer** [comment]
Hi,
By default, elassandra keeps cassandra data in /var/lib/cassandra and elasticsearch data in /var/lib/cassandra/elasticsearch.data (containing lucene files).

**nodetool status keyspace** still show cassandra occupied space (without lucene file space).

**GET _cat/allocation?v** reports for elasticsearch only occupied space, it's an elasticsearch overview.

Finally, if your use **GET _cat/indices?v**, the total number of documents includes replica, so for exemple if you have 10 docs with RF = 2 in cassandra, you'll get a total number of docs = 20 for elasticsearch.

**Comment by Gappa88** [comment]
perfect, thank you @vroyer !
in fact,  the **du -sh /var/lib/cassandra** output, for each node, is the rounded value of **nodetool status** output **+** **GET _cat/allocation** output for the node I'm considering.


Why the load of the nodes is not evenly distributed? the **nodetool status** output shows that the load is mainly on a single node. Data wouldn't be distributed among all nodes in the cluster?
```
$ nodetool status mykeyspace
Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.8.0.14  12.47 GiB  8            49.6%             c5a17dbd-40ef-4f58-b132-0d977a92f1a1  r1
UN  10.8.0.1   17.55 GiB  8            64.2%             f088d009-bd97-4e35-9f20-60006a68b363  r1
UN  10.8.0.6   33.49 GiB  8            86.1%             e82191ad-9d9f-459f-9da0-2b0457ad6611  r1
```

Thanks again!

**Comment by DBarthe** [comment]
Hello,
There is two partitions A and B replicated x2 each.
So I guess:

   - 10.8.0.1 holds A
   - 10.8.0.6 holds B + a replica of A
   - 10.8.0.14 holds a replica of B

Finally 10.8.0.6 holds twice

Is this OK ?

**Comment by Gappa88** [comment]
@DBarthe, thanks for the answer. It could be like you say but I don't have tools to confirm that.

last thing, here the ring:

```
$ nodetool ring mykeyspace

Datacenter: DC1
==========
Address    Rack        Status State   Load            Owns                Token
                                                                          8046893569169204194
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              -7885825037800730315
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              -7261086042602187969
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              -7247943966600989463
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              -7228717159480176131
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              -6939207504674930480
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              -6158757762234956967
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              -4699623277895141955
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              -4269715227726417275
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              -3148156422280710025
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              -2567971232125784764
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              -2187229040967677675
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              -2058807466377445130
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              -1181919914747129817
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              695306942662545127
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              1989050017548537421
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              2881433693910708029
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              3454959670543032324
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              3833350227892101457
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              4855735318033934682
10.8.0.6   r1          Up     Normal  30.77 GiB       86.15%              6288034337780481749
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              6495870875989416002
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              6853344637592889364
10.8.0.14  r1          Up     Normal  7.36 GiB        49.61%              6911496393497851249
10.8.0.1   r1          Up     Normal  17.55 GiB       64.24%              8046893569169204194
```

**Comment by vroyer** [comment]
Data distribution depends on cassandra, the more you have vnodes, the smaller is your distribution variance, see  [virtual nodes](https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/config/configVnodes.html).

**Comment by Gappa88** [comment]
ok, I imagined that! thanks again
