### ISSUE TITLE
Possible data corruption / indexes size are differs  (do not sure how to check)

### ISSUE THREAD

**Issue by evgeniagusakova** [strapdata/elassandra#206]
Hi Team!

I have unexpected behaviour of elassandra cluster. 
I had cluster of 3 nodes and I added 3 more nodes in new datacenter. 
After cluster is added I started data replication to new cluster 

```
ALTER KEYSPACE "my_keyspace" WITH REPLICATION =
	{'class’: 'NetworkTopologyStrategy', 'ExistingDC':3, 'NewDC':3};
```
```
nodetool rebuild --keyspace my_keyspace -- ExistingDC
```
```
nodetool rebuild_index my_keyspace my_table elastic_my_table_idx
```

For some reason which is not clear for me I have different data and indexes sizes:

```
nodetool status
Datacenter: NewDC
========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  10.0.20.119     5.62 GiB   256          ?       a740211f-ffdb-4fff-a9db-3d0c67a770f7  rack1
UN  10.0.20.104     3.54 GiB   256          ?       adb46050-6af1-4ca0-bade-afdb9f19a30d  rack1
UN  10.0.20.88      3.28 GiB   256          ?       86ba33f8-ee66-4f90-af0c-bed22f4b7df4  rack1
Datacenter: ExistingDC
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  192.168.20.9    3.93 GiB   256          ?       2accf8e6-d670-48c4-ac0c-c3ce1912d3e2  rack1
UN  192.168.20.123  3.91 GiB   256          ?       11f8a94a-9ea2-42e4-a4df-ef296f463513  rack1
UN  192.168.20.143  4.12 GiB   256          ?       474f8c1e-7006-4af0-83e2-ebc0eb2c8c33  rack1
```

I checked indexes sizes
On node from `ExistingDC`:
```
curl "http://192.168.20.123:9200/_cat/indices?v"|grep my_keyspace_2018_06_28

green  open   my_keyspace_2018_06_28 a3C2FPswRs6WQWmAZvoCQQ   3   2       2529           35      4.9mb          4.9mb
```
On node from `NewDC`
```
curl "http://10.0.20.119:9200/_cat/indices?v"|grep my_keyspace_2018_06_28
green  open   my_keyspace_2018_06_28 a3C2FPswRs6WQWmAZvoCQQ   3   2       2548           10      4.4mb          4.4mb
```
Above is just example, I have different indexes sizes for all partitioned indexes, not only for ` my_keyspace_2018_06_28`. 

So it looks like indexes differs for some reason and I do not have any idea how to verify it.
It may be because of data corruption I guess but do not know how to check.

- are any tools to check are indexes correct?
- any other options to verify data replicated w/o errors?

Please let me know if it is wrong place for this question and I'll move it.

To be honest I spent much time googling before ask question here but did not find any community of elassandra where I can ask for help.

**Elasticsearch version**
```
curl "http://192.168.20.123:9200/"
{
  "name" : "192.168.20.123",
  "cluster_name" : "my_cluster_name",
  "cluster_uuid" : "11f8a94a-9ea2-42e4-a4df-ef296f463513",
  "version" : {
    "number" : "5.5.0",
    "build_hash" : "44a3c9e",
    "build_date" : "2017-10-18T12:29:54.934Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Plugins installed**: []

**JVM version** (`java -version`):
```
# java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
uname -a
Linux cfsc-as1-elassandra-node-1 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by Gappa88** [comment]
if data are corrupted you should see corrupted messages in the elassandra's system.log.

I think something like this:


**$ cat /var/log/cassandra/system.log | grep CorruptBlockException**
`
Caused by: org.apache.cassandra.io.compress.CorruptBlockException: (/var/lib/cassandra/data/mykeyspace/mytable-c16d5bc0738e11e89509f1cacb8bcd7e/mc-1638-big-Data.db): corruption detected, chunk at 2030478750 of length 23553.
`

**Comment by evgeniagusakova** [comment]
@Gappa88 Thank you for your reply.


I checked logs and have not found any messages like **CorruptBlockException**  so it looks  like data was not corrupted.

But I still do not understand why nodes have different data sizes, from my point of view with RF=3 and 3 nodes in ring each node should have full data set, so size should be exactly the same.

Also I still see different indexes sizes:
NewDC:
```
curl "http://10.0.20.119:9200/_cat/allocation?v"
shards disk.indices disk.used disk.avail disk.total disk.percent host        ip          node
   256        3.8gb       8gb     90.2gb     98.3gb            8 10.0.20.88  10.0.20.88  10.0.20.88
   256        3.7gb     7.9gb     90.3gb     98.3gb            8 10.0.20.119 10.0.20.119 10.0.20.119
   256        3.9gb     6.1gb     42.9gb       49gb           12 10.0.20.104 10.0.20.104 10.0.20.104
```
ExistingDC:
```
curl "http://192.168.20.123:9200/_cat/allocation?v"
shards disk.indices disk.used disk.avail disk.total disk.percent host           ip             node
   256        4.2gb    14.3gb    182.3gb    196.7gb            7 192.168.20.123 192.168.20.123 192.168.20.123
   256        4.5gb    14.6gb    182.1gb    196.7gb            7 192.168.20.9   192.168.20.9   192.168.20.9
   256        4.3gb    14.4gb    182.2gb    196.7gb            7 192.168.20.143 192.168.20.143 192.168.20.143
```

No idea how  can I understand is it normal behavior or  do I have some kind of **data consistency** issue?

**Comment by Gappa88** [comment]
@evgeniagusakova I have similar question, posted [here](https://github.com/strapdata/elassandra/issues/205) but my problem is about 3 nodes and a replication factor of 2.

maybe is better to wait for **vroyer** for a the correct reply but your problem it could not be a problem
and it could be related to [this](https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/config/configVnodes.html).

**Comment by vroyer** [comment]
Hi,
In this case, you can have a cassandra data consistency issue, or an indexing issue:
1. Run a cassandra repair --full for your indexed keyspaces, and check if number of document is corrects beetween your 2 dc.
2. When repair is OK, rebuild elasticsearch indexes with a nodetool rebuild_index.

When a row is properly replicated to cassandra node, but not properly index in elasticsearch, you could have one of these warning messages in your logs :

No Elasticsearch index ready ....
No Elasticsearch index configured for ...
