### ISSUE TITLE
Difficulty setting replication settings for keyspace

### ISSUE THREAD

**Issue by hgascoigne** [strapdata/elassandra#207]
**Elassandra version**: 6.2.3.2

I am unable to set default replication settings for newly created indexes. 

I have tried various methods:
1. Setting a default template with `number_of_replicas`:
```
PUT _template/default

{
  "index_patterns": ["*"],
  "order": 0,
  "settings" : {
    "number_of_replicas": 2,
  }
}
```
This will create a replications of `{'class': 'NetworkTopologyStrategy', 'DC1': '1'}`. Interestingly, if I create a new index and pass the following directly during index creation I will get the correct replication settings:
```
PUT /myindex

"settings" : {
  "number_of_replicas": 2,
}
```
The above translates to `{'class': 'NetworkTopologyStrategy', 'DC1': '2'}`. Does Elassandra not honor template `number_of_replicas` setting?

2. I tried setting the `replication` setting in my index template but I'm not exactly sure the format it's expecting. Passing as an object gives me an error that the setting is not recognized:

```
"settings" : {
  "replication": {
    "class": "NetworkTopologyStrategy",
    "DC1": "2"
  }
}
```

Passing as a string tells me the replication expression is not valid:
```
"settings" : {
  "replication": "{'class': 'NetworkTopologyStrategy', 'DC1': '2'}"
}
```

Could you please provide a simple example on how to set this properly? The docs are light on information about this. Thank you! I'm sure I'm just missing one small step.

**Comment by Gappa88** [comment]
`Cassandra's replication_factor = ES' number_of_replicas + 1 ` 
or
`ES' number_of_replicas  = Cassandra's replication_factor - 1`
`[https://github.com/strapdata/elassandra/issues/167#issuecomment-365189680](https://github.com/strapdata/elassandra/issues/167#issuecomment-365189680)

**Comment by vroyer** [comment]
Yes, you're right !
