### ISSUE TITLE
Limitation of column size

### ISSUE THREAD

**Issue by filthz** [strapdata/elassandra#213]
Is there a limitation on column size?

My cassandra table:

```
CREATE TABLE deviceinfo (
    commission_number text,
    test_results frozen <list<frozen <test_result>>>,
    PRIMARY KEY (commission_number)
)

```

When i insert elements in cassandra, I see this error in the logs:

```
Caused by: org.apache.cassandra.exceptions.InvalidRequestException: Expected 10 values for frozen<test_result> column, but got more
        at org.apache.cassandra.db.marshal.TupleType.split(TupleType.java:190)
```

Is it somehow possible to store (and index) a list of elements?

**Comment by vroyer** [comment]
Yes, by default, elasticsearch fields are multivalued and stored in a list<X>.
So your schema cloud be as followed :
> CREATE TABLE deviceinfo (
>     commission_number text,
>     test_results list<test_result>,
>     PRIMARY KEY (commission_number)
> )
