### ISSUE TITLE
Add a new Analyzer to ES' index

### ISSUE THREAD

**Issue by Gappa88** [strapdata/elassandra#214]
using Elassandra 6.2.3.1.

I need to change or add an **analyzer** for my index. 
Can I follow [these](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#update-settings-analysis) instructions or I need to delete ES' data, change the index's configuration and rebuild the index?

thanks

**Comment by vroyer** [comment]
Yes, you can close your index, update settings and reopen, put previously indexed document remain indexed with the old settings.
Then, if you need it, you can rebuild your index with the new settings.

**Comment by Gappa88** [comment]
ok thanks
