### ISSUE TITLE
data inconsistency in elasticsearch nodes of Elassandra 5.5.0.20

### ISSUE THREAD

**Issue by RachidKraiem** [strapdata/elassandra#215]
**Elassandra version: 5.5.0.20**

**JVM version: JDK 1.8.0_66**

**OS version: CentOS release 6.5 (Final)** 

**VM: 5 VM , each one have 16GB RAM and 8CPU**

**Description of the problem including expected versus actual behavior:**
In fact, I have a **cluster elassandra with two data center which 3 nodes started as "bin/cassandra" and 2 other nodes started as "bin/cassandra -e".**
In order to more clarify, in join the configuration (cassandra.yaml and jvm.options)
In pre-production environment of my client, i have a data inconsistency after the following scenario (that seems very critical):

**1- i launch intensive update with cql query on a table
2- i stop one node elassandra (that started with ./cassandra -e)
3- i continue my updates and i stop again the other node elassandra (started with ./cassandra -e)
4- i'm waiting for the end of the process that updated 4079 records.
5- i restart the two nodes.
6- so, i see 4079 records updated in the first node, and only 4075 in the other node !
I have systematically this issue.**

To note that we deleted cassandra-topology.properties file from each node in order to use GossipingPropertyFileSnitch.

**The difference between my current configuration and default as follow:**

_num_tokens: 256
concurrent_writes: 64
concurrent_counter_writes: 64
file_cache_size_in_mb: 4096
compaction_throughput_mb_per_sec: 0
write_request_timeout_in_ms: 60000
counter_write_request_timeout_in_ms: 60000
auto_bootstrap: false_
[configurations.zip](https://github.com/strapdata/elassandra/files/2214151/configurations.zip)

**Comment by vroyer** [comment]
It can be a cassandra replication issue (maybe you have hinted handoff), or an elasticsearch indexing error.

So, could you provide your CQL schema, your elasticsearch mapping, the command used to ingest your data and to check the number of document, and the logs of the node where some documents are missing. Thanks in advance.

**Comment by DBarthe** [comment]
2f88425f047910ddcc04920aab37ac63824d09d2 should have fix the issue.
