### ISSUE TITLE
Problem with time-framed indices

### ISSUE THREAD

**Issue by prog-toolbox** [strapdata/elassandra#218]
**Elassandra : 5.5.0.20**

**JDK : 1.8.0_181**

**Cluster : contains 5 nodes : 3 of them running as "Cassandra-Only" Nodes (located in a DataCenter) and the other 2 are running as "Cassandra+Elasticsearch" Nodes (located as well in another DataCenter).**

Hello,

I am facing a problem with time-framed indices. In fact, rows in Cassandra are not synhronized with the time-framed indice and I cannot even create documents directly in Elasticsearch.
The log file shows the following exception : 
`2018-08-06 11:52:00,997 ERROR [MutationStage-1] ElasticSecondaryIndex.java:2038 write Unexpected error
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$ImmutablePartitionFunction.indexName(ElasticSecondaryIndex.java:1120)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo.targetIndices(ElasticSecondaryIndex.java:1365)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.index(ElasticSecondaryIndex.java:2046)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer$Rowcument.write(ElasticSecondaryIndex.java:2033)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer$WideRowcument.write(ElasticSecondaryIndex.java:1419)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$WideRowcumentIndexer.flush(ElasticSecondaryIndex.java:1510)
        at org.elassandra.index.ElasticSecondaryIndex$ImmutableMappingInfo$RowcumentIndexer.finish(ElasticSecondaryIndex.java:1754)
        at org.apache.cassandra.index.SecondaryIndexManager$WriteTimeTransaction.commit(SecondaryIndexManager.java:983)
        at org.apache.cassandra.db.partitions.AtomicBTreePartition.addAllWithSizeDelta(AtomicBTreePartition.java:181)
        at org.apache.cassandra.db.Memtable.put(Memtable.java:282)
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1342)
        at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:631)
        at org.apache.cassandra.db.Keyspace.applyFuture(Keyspace.java:438)
        at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:222)
        at org.apache.cassandra.db.MutationVerbHandler.doVerb(MutationVerbHandler.java:68)
        at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134)
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:109)
        at java.lang.Thread.run(Thread.java:748)`

My table's schema is : 

`CREATE TABLE my_keyspace.my_entity_template (
		my_id text,
		my_date timestamp,
		my_service text,
		my_data map<text, text>,
		PRIMARY KEY (my_id, my_date, my_service)
	) WITH read_repair_chance = 0.0
	   AND dclocal_read_repair_chance = 0.1
	   AND gc_grace_seconds = 864000
	   AND bloom_filter_fp_chance = 0.01
	   AND caching = { 'keys' : 'ALL', 'rows_per_partition' : 'NONE' }
	   AND comment = ''
	   AND compaction = { 'class' : 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold' : 32, 'min_threshold' : 4 }
	   AND compression = { 'chunk_length_in_kb' : 64, 'class' : 'org.apache.cassandra.io.compress.LZ4Compressor' }
	   AND default_time_to_live = 0
	   AND speculative_retry = '99PERCENTILE'
	   AND min_index_interval = 128
	   AND max_index_interval = 2048
	   AND crc_check_chance = 1.0;`

My template's structure is : 

`curl 'http://elassandra_node_ip:9200/_template/my_entity-template' -X PUT -H 'Content-Type: application/json' --data-binary '{"template": "my_entity-partitioned-index-*" , "settings" : { "index.partition_function": "toDayIndex partitioned-index-test-{0,date,yyyy.MM.dd} timefield" , "index.partition_function_class": "org.elassandra.index.StringPartitionFunction", "index.search_strategy_class":"RandomSearchStrategy" , "keyspace" : "my_keyspace","analysis": {"analyzer": {"analyzer_whitespace_separator": {"type": "custom","filter": ["lowercase"],"tokenizer": "whitespace"}}}  }, "mappings":{"my_entity_template":{"dynamic_templates":[{"my_data_template":{"match":"my_data.*","mapping":{"type":"text","index":"analyzed","analyzer":"analyzer_whitespace_separator"}}}],"properties":{"my_date":{"type":"date","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":1,"format":"strict_date_optional_time||epoch_millis"},"my_service":{"type":"text","index":"analyzed","analyzer":"analyzer_whitespace_separator","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":2},"my_id":{"type":"text","index":"analyzed","analyzer":"analyzer_whitespace_separator","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":0},"my_data":{"type":"nested","cql_struct":"map","cql_collection":"singleton"}}}} }'`

And I didn't succeed to create properly the following document directly in Elasticsearch : 

`curl -X POST "http://elassandra_node_ip:9200/my_entity-partitioned-index-2018.08.01/my_entity_template/123" -H 'Content-Type: application/json' -d'{"my_id":"123456","my_service":"simple_service","my_date":"2018-07-19T12:57:43.496Z"}'`

In fact, when I searched for my new document with a GET operation on "my_entity-partitioned-index-2018.08.01/my_entity_template/123", it shows me only the **"my_id"** field:
`{
  "_index" : "my_entity-partitioned-index-2018.08.01",
  "_type" : "my_entity_template",
  "_id" : "123",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "my_id" : "123"
  }
}`

 Besides that, I noticed that the replicas number aren't the same between nodes : In the my first ES node, it is equal to **1** , and in the second one, it is equal to **3**, and the **"docs.count"** is always **0** in both nodes.

What is the cause of this issue and do you have a solution ?

I appreciate your help.

**Comment by vroyer** [comment]
Hi,

Yes, timefield used in your partition function is not a column from the underlying CQL table.
You should use my_date i guess.

Thanks.

**Comment by prog-toolbox** [comment]
Hello,

The exception disappeared, but the problem remains.
Again, when I try to insert the following document : 
`curl -X POST "http://elassandra_node_ip:9200/my_entity-partitioned-index-2018.08.01/my_entity_template/123" -H 'Content-Type: application/json' -d'{"my_id":"123456","my_service":"simple_service","my_date":"2018-07-19T12:57:43.496Z"}'`

I obtain : 
`{ "_index" : "my_entity-partitioned-index-2018.08.01", "_type" : "my_entity_template", "_id" : "123", "_version" : 1, "found" : true, "_source" : { "my_id" : "123" } }`

So as you see here, the **_id**'s value is inserted in **my_id** field, and the document is not inserted.
This time, the replicas number is the same between nodes (equal to 1 as usual), but the "docs.count" is always 0 in both nodes.

Log : 
`read_repair_chance=0.0,dclocal_read_repair_chance=0.1,bloom_filter_fp_chance=0.01,crc_check_chance=1.0,gc_grace_seconds=864000,default_time_to_live=0,memtable_flush_period_in_ms=0,min_index_interval=128,max_index_interval=2048,speculative_retry=99PERCENTILE,caching={'keys':'ALL','rows_per_partition':'NONE'},compaction=CompactionParams{class=org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,options={max_threshold=32,min_threshold=4}},compression=org.apache.cassandra.schema.CompressionParams@911d3ce5,extensions={},cdc=false},comparator=comparator(),partitionColumns=[[]|[metadataownerversion]],partitionKeyColumns=[cluster_name],clusteringColumns=[],keyValidator=org.apache.cassandra.db.marshal.UTF8Type,columnMetadata=[owner,version,cluster_name,metadata],droppedColumns={},triggers=[],indexes=[]]Toorg.apache.cassandra.config.CFMetaData@7fab9bad[cfId=3d3ac740-9263-11e8-bd8d-9114cedc42b7,ksName=elastic_admin,cfName=metadata,flags=[COMPOUND],params=TableParams{comment={"meta-data":{"version":266,"cluster_uuid":"261feda6-522d-4823-bd5c-1ddee862b37e","templates":{"my_entity-template":{"order":0,"template":"my_entity-partitioned-index-*","settings":{"index":{"keyspace":"my_keyspace","analysis":{"analyzer":{"analyzer_whitespace_separator":{"filter":["lowercase"],"type":"custom","tokenizer":"whitespace"}}},"partition_function":"toDayIndexpartitioned-index-test-{0,date,yyyy.MM.dd}my_date","partition_function_class":"org.elassandra.index.StringPartitionFunction","search_strategy_class":"RandomSearchStrategy"}},"mappings":[{"my_entity_template":{"dynamic_templates":[{"my_data_template":{"match":"my_data.*","mapping":{"type":"text","index":"analyzed","analyzer":"analyzer_whitespace_separator"}}}],"properties":{"my_date":{"type":"date","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":1,"format":"strict_date_optional_time||epoch_millis"},"my_service":{"type":"text","index":"analyzed","analyzer":"analyzer_whitespace_separator","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":2},"my_id":{"type":"text","index":"analyzed","analyzer":"analyzer_whitespace_separator","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":0},"my_data":{"type":"nested","cql_struct":"map","cql_collection":"singleton"}}}}],"my_entity-partitioned-index-2018.08.02":{"version":1,"state":"open","settings":{"index.analysis.analyzer.analyzer_whitespace_separator.filter.0":"lowercase","index.analysis.analyzer.analyzer_whitespace_separator.tokenizer":"whitespace","index.analysis.analyzer.analyzer_whitespace_separator.type":"custom","index.creation_date":"1533798265714","index.keyspace":"my_keyspace","index.partition_function":"toDayIndexpartitioned-index-test-{0,date,yyyy.MM.dd}my_date","index.partition_function_class":"org.elassandra.index.StringPartitionFunction","index.provided_name":"my_entity-partitioned-index-2018.08.02","index.search_strategy_class":"RandomSearchStrategy","index.uuid":"aA4meFlrTxiDq48niU8aqA","index.version.created":"5050099"},"mappings":[{"my_entity_template":{"dynamic_templates":[{"my_data_template":{"match":"my_data.*","mapping":{"analyzer":"analyzer_whitespace_separator","index":"analyzed","type":"text"}}}],"properties":{"my_data":{"type":"nested","cql_struct":"map","cql_collection":"singleton"},"my_date":{"type":"date","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":1},"my_service":{"type":"text","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":2,"analyzer":"analyzer_whitespace_separator"},"my_id":{"type":"text","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":0,"analyzer":"analyzer_whitespace_separator"}}}}],"aliases":{}},"my_entity-partitioned-index-2018.08.01":{"version":1,"state":"open","settings":{"index.analysis.analyzer.analyzer_whitespace_separator.filter.0":"lowercase","index.analysis.analyzer.analyzer_whitespace_separator.tokenizer":"whitespace","index.analysis.analyzer.analyzer_whitespace_separator.type":"custom","index.creation_date":"1533725411662","index.keyspace":"my_keyspace","index.partition_function":"toDayIndexpartitioned-index-test-{0,date,yyyy.MM.dd}my_date","index.partition_function_class":"org.elassandra.index.StringPartitionFunction","index.provided_name":"my_entity-partitioned-index-2018.08.01","index.search_strategy_class":"RandomSearchStrategy","index.uuid":"lgqvnaXbQ3iYB5EJ7gxTLQ","index.version.created":"5050099"},"mappings":[{"my_entity_template":{"dynamic_templates":[{"my_data_template":{"match":"my_data.*","mapping":{"analyzer":"analyzer_whitespace_separator","index":"analyzed","type":"text"}}}],"properties":{"my_data":{"type":"nested","cql_struct":"map","cql_collection":"singleton"},"my_date":{"type":"date","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":1},"my_service":{"type":"text","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":2,"analyzer":"analyzer_whitespace_separator"},"my_id":{"type":"text","cql_collection":"singleton","cql_partition_key":true,"cql_primary_key_order":0,"analyzer":"analyzer_whitespace_separator"}}}}],"aliases":{}},"index-graveyard":{"tombstones":[{"index":{"index_name":"my_entity-partitioned-index-2018.08.04","index_uuid":"sqmr8-AkQxKFklWFrvEpuQ"},"delete_date_in_millis":1533552430211},{"index":{"index_name":"my_entity-partitioned-index-2018.08.02","index_uuid":"jCsaP7inQleOXn3V90tZbg"},"delete_date_in_millis":1533552489521},{"index":{"index_name":"my_entity-partitioned-index-2018.08.03","index_uuid":"FIn5LoRQQHWBUoAL2ThNHQ"},"delete_date_in_millis":1533552500995},{"index":{"index_name":"my_entity-partitioned-index-2018.08.01","index_uuid":"4iFFshB3TQi1NmZBIOfm6A"},"delete_date_in_millis":1533650477992},{"index":{"index_name":"my_entity-partitioned-index-2018.08.02","index_uuid":"BExoWjAVQ_mpM9kgR6Nd2w"},"delete_date_in_millis":1533650484956}]}}},read_repair_chance=0.0,dclocal_read_repair_chance=0.1,bloom_filter_fp_chance=0.01,crc_check_chance=1.0,gc_grace_seconds=864000,default_time_to_live=0,memtable_flush_period_in_ms=0,min_index_interval=128,max_index_interval=2048,speculative_retry=99PERCENTILE,caching={'keys':'ALL','rows_per_partition':'NONE'},compaction=CompactionParams{class=org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,options={max_threshold=32,min_threshold=4}}`

Thank you for your help.

**Comment by vroyer** [comment]
Hi Ghazi,

When you created a partition function, you should write in the underlying CQL table, not directly in a partitioned index.
If you want to do than with the elasticsearch API, you need to define a dummy index that does not index at all but match the underlying table name.
Then, when writing to the underlying CQL table through the ES API, data are indexed in the partitioned index.

Best regard,
Vincent.

**Comment by prog-toolbox** [comment]
Hello Vincent,

I was based on the following issue to write my own partitioned indice : https://github.com/strapdata/elassandra/issues/178
It shows that we should put "index.partition_function_class" in the Elasticsearch template.`

Could you please show me the appropriate location to put the partition function in CQL : 
`CREATE TABLE my_keyspace.my_entity_template ( my_id text, my_date timestamp, my_service text, my_data map<text, text>, PRIMARY KEY (my_id, my_date, my_service) ) WITH read_repair_chance = 0.0 AND dclocal_read_repair_chance = 0.1 AND gc_grace_seconds = 864000 AND bloom_filter_fp_chance = 0.01 AND caching = { 'keys' : 'ALL', 'rows_per_partition' : 'NONE' } AND comment = '' AND compaction = { 'class' : 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold' : 32, 'min_threshold' : 4 } AND compression = { 'chunk_length_in_kb' : 64, 'class' : 'org.apache.cassandra.io.compress.LZ4Compressor' } AND default_time_to_live = 0 AND speculative_retry = '99PERCENTILE' AND min_index_interval = 128 AND max_index_interval = 2048 AND crc_check_chance = 1.0;`

I appreciate your help.

**Comment by vroyer** [comment]
Here is a unit test demonstrating how to write in a dummy index to split data into partitioned indices.

```
public void basicStringPartitionFunctionWithDummyIndexTest() throws Exception {
        process(ConsistencyLevel.ONE,String.format(Locale.ROOT, "CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', '%s': '1'}",DatabaseDescriptor.getLocalDataCenter()));
        process(ConsistencyLevel.ONE,"CREATE TABLE ks.t1 (name text, age int, primary key (name))");
        
        XContentBuilder mappingt1 = XContentFactory.jsonBuilder().startObject()
                    .startObject("properties")
                       .startObject("name").field("type", "keyword").field("cql_collection", "singleton").field("index", false).endObject()
                       .startObject("age").field("type", "integer").field("cql_collection", "singleton").field("index", false).endObject()
                    .endObject()
              .endObject();
        assertAcked(client().admin().indices().prepareCreate("ks").addMapping("t1", mappingt1).get());
        
        for(long i=20; i < 30; i++) {
            createIndex("ks_"+i, Settings.builder().put("index.keyspace","ks")
                    .put("index.partition_function", "byage ks_%d age")
                    .put("index.partition_function_class", "org.elassandra.index.StringPartitionFunction")
                    .build(),"t1", discoverMapping("t1"));
            ensureGreen("ks_"+i);
        }
        for(long i=20; i < 30; i++) {
            for(int j=0; j < i; j++) {
                String name = String.format("name%d-%d", i, j);
                XContentBuilder doc = XContentFactory.jsonBuilder().startObject()
                        .field("name", name)
                        .field("age", i)
                        .endObject();
                client().prepareIndex("ks", "t1", name).setSource(doc).get();
            }
        }
        
        for(long i=20; i < 30; i++)
            assertThat(client().prepareSearch().setIndices("ks_"+i).setTypes("t1").setQuery(QueryBuilders.matchAllQuery()).get().getHits().getTotalHits(), equalTo(i));
    }
```

**Comment by vroyer** [comment]
stale issue
