### ISSUE TITLE
Elassandra Shield integration

### ISSUE THREAD

**Issue by albroscani** [strapdata/elassandra#22]
Hi Vincent,
I would like to protect Elasticsearch with the Shield Plugin but when I try to configure it I receiver this error:

`You must set the ES_CLASSPATH var`

After setting the ES_CLASSPATH var I receive another error:

`Error: Could not find or load main class org.elasticsearch.shield.authc.esusers.tool.ESUsersTool`

Probably I'm doing something wrong; can you tell me how to configure the Shield plugin over Elassandra?

Thank you

Alberto

**Comment by vroyer** [comment]
Hi Alberto,

Set your ES_CLASSPATH like this and follow install instruction from  https://www.elastic.co/downloads/shield

export ES_CLASSPATH=""
for jar in "$CASSANDRA_HOME"/lib/*.jar; do
    ES_CLASSPATH="$ES_CLASSPATH:$jar"
done

I have never used shield, but this seems to work.
Thanks,
Vincent.

**Comment by albroscani** [comment]
Hi Vincent, sorry for the delay, 
I've not tried your solution yet but I wil do it ASAP. Can you explain me what solution you know and use to protect Elasticsearch?
Thanks,
Alberto

**Comment by vroyer** [comment]
Hi Alberto,

I plan to develop a security plugin like shield or searchguard probably for september. It will rely on cassandra for authentication (with an LDAP connector), role management and SSL keystore, so both cassandra and elasticsearch will be secured with the same rules.

Thanks,
Vincent.

**Comment by thelordoftheboards** [comment]
@vroyer is it still your intention to develop a security plugin (or it is already developed?), or this with the move to ES 5.x? I have very little knowledge, but from the limited research I was able to do it seems ES 5.x has new options when it comes to security (X-Pack vs. Shield).

**Comment by vroyer** [comment]
Yes, security plugins are developed and will be released in September with Elassandra based on ES 5.x.

**Comment by thelordoftheboards** [comment]
Thank you! I recently started playing with Elassandra and I have to say you've done an amazing job. It is as easy to set up as Cassandra, but we get both ES and Cassandra, not to mention the architectural improvements.
