### ISSUE TITLE
Support "alias" data type for fields

### ISSUE THREAD

**Issue by jadbalja** [strapdata/elassandra#221]
Elasticsearch 6.4 now supports adding field aliases to an index, say to map "familyName" to "family_name" in mappings.  This feature would make working with Spring Boot Elasticsearch much easier.

**Comment by DBarthe** [comment]
This would be available as soon as the elassandra 6.4.x.x will be released

**Comment by vroyer** [comment]
Ok, we keep your request for the next upgrade.
Thanks.

**Comment by vroyer** [comment]
Elassandra 6.8.4.0 is out, with support for field alias.
Thanks in advance for your feed back.
