### ISSUE TITLE
Map inside UDT prevents indexing

### ISSUE THREAD

**Issue by Piersen** [strapdata/elassandra#223]
**Elasticsearch version**: 6.2.3

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_181"

**OS version** (`uname -a` if on a Unix-like system): 05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Map inside UDT prevents cassandra rows from being indexed. In the example below, the search returns no result. (Problem doesn't occur when the map inside the UDT is removed).

**Steps to reproduce**:

 1. In cqlsh:
```cql
CREATE KEYSPACE example WITH REPLICATION = { 'class':'NetworkTopologyStrategy', 'DC1':2 };

CREATE TYPE example.vars (
  str frozen<map<text, text>>
);

CREATE TABLE example.sessions (
  id timeuuid PRIMARY KEY ,
  meta frozen<vars>
);

INSERT INTO example.sessions (id, meta)

VALUES (
    now(),
	{ 
		str: { 'nickname': 'someuser' }
	}
);
```
 2. `curl -H "Content-Type: application/json" -XPUT "http://localhost:9200/example?pretty"`
 3. `curl -XPUT "http://localhost:9200/example/_mapping/sessions" -H 'content-type: application/json' -d '{ "sessions" : { "discover" : ".*" }}'`
4. In browser, search `http://localhost:9200/example/sessions/_search?&q=*:*&error_trace=true`

**Provide logs (if relevant)**:

**Comment by vroyer** [comment]
Hi,
This is currently not supported because it would involve a dynamic mapping update of a nested object. As a workaround, use a map in a column rather than in an UDT.

**Comment by vroyer** [comment]
Next release 6.2.310 solve this !
Thanks for reporting the issue.
