### ISSUE TITLE
How to migrate entire Data from DataStax Cassandra to Elassandra in aks-cluster

### ISSUE THREAD

**Issue by njsandilya** [strapdata/elassandra#227]
**Describe the feature**:

**Elasticsearch version**:

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by njsandilya** [comment]
Hi,

We are trying to move our data total of 41TB from DataStax cassandra (DSE version 5.1.11) to elassandra.

Brief: We have a existing cassandra setup on DSE where we have 12 streaming nodes with 8 TB each node. Currently we are trying to migrate entire 41TB of data from cassandra to elassandra which is there is aks-cluster in Azure.
We are unable to find any tool or other mechanism to do this migration. 
Kindly advice here.

**Comment by vroyer** [comment]
Hi,

Basically, you can migrate from cassandra 3.11.x to elassandra 5.5+ or 6.2+ with your current CQL schema and SSTables (like a backup restore) or replace C* binaries by elassandra ones and restart. You can contact [strapdata here](https://www.strapdata.com/services/)  to get more details.

Thanks.
