### ISSUE TITLE
Port Forward is getting stopped very frequently when running python script to get data from remote to local

### ISSUE THREAD

**Issue by jansee233** [strapdata/elassandra#229]
**Elasticsearch version**:
"number" : "6.2.3",
"build_hash" : "e605ecd",
"build_date" : "2018-07-18T19:19:00.787857Z",
"build_snapshot" : false,
"lucene_version" : "7.2.1",
"minimum_wire_compatibility_version" : "5.6.0",
"minimum_index_compatibility_version" : "5.0.0"

**JVM version** (`java -version`):
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux elassandra-0 4.15.0-1023-azure #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
 Tried on All elassandra instances. E0924 12:32:34.310290  244680 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:9042->127.0.0.1:57857: write tcp4 127.0.0.1:9042->127.0.0.1:57857: wsasend: An established connection was aborted by the software in your host machine.   E0924 12:31:01.288127 250812 portforward.go:316] error copying from local connection to remote stream: read tcp4 127.0.0.1:9042->127.0.0.1:57844: wsarecv: An existing connection was forcibly closed by the remote host. E0924 12:31:01.771293 250812 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:9042->127.0.0.1:57844: write tcp4 127.0.0.1:9042->127.0.0.1:57844: wsasend: An existing connection was forcibly closed by the remote host.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by vroyer** [comment]
This is probably related to your kubernetes environment ?
