### ISSUE TITLE
Error in elassandra pod "org.apache.cassandra.exceptions.UnavailableException: 

### ISSUE THREAD

**Issue by jansee233** [strapdata/elassandra#230]
**Elasticsearch version**:

"number" : "6.2.3",
"build_hash" : "e605ecd",
"build_date" : "2018-07-18T19:19:00.787857Z",
"build_snapshot" : false,
"lucene_version" : "7.2.1",
"minimum_wire_compatibility_version" : "5.6.0",
"minimum_index_compatibility_version" : "5.0.0"

**JVM version** (`java -version`):

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux elassandra-0 4.15.0-1023-azure #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Error in elassandra logs Cannot achieve consistency level SERIAL and LOCAL_QUORUM
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by DBarthe** [comment]
It means half of your nodes is unavailable.

Did you try `nodetool status` on each node ?

**Comment by vroyer** [comment]
You probably have some node down and mapping update failed because the LOCAL_QUORUM is not reached. Please check that more than 50% of your nodes are up and normal.

**Comment by Trigno97** [comment]
There are 3 nodes in cluster, and 2 of them are down and not able to communicate to the master node, how can I remove those node from cluster and create index without error.
