### ISSUE TITLE
Error with nodetool status - "unexpected EOF"

### ISSUE THREAD

**Issue by eoinreilly93** [strapdata/elassandra#231]
**Java Version**
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Elassandra Version**
elassandra-6.2.3.6

**Environment**
CentOS Linux release 7.5.1804 (Core)

**Problem description**
I'm currently installing Elassandra on my Centos 7 server. I've followed the basic installation guide, unzipped the tar.gz file and set my CASSANDRA_HOME environment variable. I've also edited the cassandra-env.sh file and uncommented 

`JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=<public name>"` 

and changed it to my ip address. 

I start cassandra with `bin/cassandra -e` and I can see the java process running fine. I can also connect to the database via cqlsh using `bin/cqlsh` and create tables/keyspaces etc.
 
However when I go to check the status of my cluster using `bin/nodetool status` [as per the documentation](https://elassandra.readthedocs.io/en/latest/installation.html),  I get the following error:

/home/reillye/elassandra/conf/cassandra-env.sh: line 324: unexpected EOF while looking for matching `"'
/home/reillye/elassandra/conf/cassandra-env.sh: line 335: syntax error: unexpected end of file

I can't seem to find any solution to this. Can anyone help with this?

**Comment by DBarthe** [comment]
Hello,

It seems to be a syntax error in your cassandra-env.sh, can you show us the
file content ?
