### ISSUE TITLE
Indexing certain fields and retrieving all fields

### ISSUE THREAD

**Issue by dbapramod882** [strapdata/elassandra#235]
How can index only certain fields/columns instead of passing regular expression and retrieve all fields.
Example: I have table with columns (alpha, beta, gamma, delta) and i want to index only (alpha, gamma) but when retrieving i need all the fields (alpha, beta, gamma, delta).

SOF: https://stackoverflow.com/questions/53159197/cannot-indexing-discover-multiple-fields-in-elassandra

**Comment by vroyer** [comment]
Hi,

You can configure a subset of your cassandra columns as elasticsearch fields by setting your elasticsearch mapping. See [elassandra documentation](http://doc.elassandra.io/en/latest/mapping.html#bidirectionnal-mapping) to configure which columns are known by elasticsearch. 

Then among the mapped elasticsearch fields, you can have indexed and not indexed fields. For not indexed column, just set "index":false in your mapping. You will then be able to retreive these fields from the _source document.

In the elassandra enterprise version, you can also retreive any Cassandra columns (and even use CQL functions) when requesting elasticsearch from your CQL driver, as shown [here](http://doc.elassandra.io/en/latest/enterprise.html#search-through-cql).

**Comment by dbapramod882** [comment]
Thanks for the update.
Thought that if there is any other option I am missing, as I have about 25 columns and where i need to index only 2 columns, where i cannot pass a regular expression i guess, as the column names were different and retrieve all/some columns (other wise i need to set manually false to all other columns in mapping).

Other question: Do i need to set "store:true" if i need to index and retrieve with 2 columns that i indexed.

Please advise, Thanks.

**Comment by vroyer** [comment]
"(columnA|columnB)" should match your 2 columns.
You don't need to set store:true to retreive a field, because it's stored in cassandra.

**Comment by dbapramod882** [comment]
I am getting this error, 

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"unknown setting [index.mappings.tablename.discover] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"}],"type":"illegal_argument_exception","reason":"unknown setting [index.mappings.tablename.discover] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"},"status":400}`

**Comment by vroyer** [comment]
index.mappings.tablename.discover is not a valid setting.

**Comment by dbapramod882** [comment]
Thanks.
