### ISSUE TITLE
sstablemetada exception

### ISSUE THREAD

**Issue by dbapramod882** [strapdata/elassandra#238]
Elassandra version: Elassandra 6.2.3.4 = Elasticsearch 6.2.3 + Cassandra 3.11.2
When I am trying sstablemetadata I am getting below error.

Command used:
 /usr/share/cassandra/tools/bin/sstablemetadata /filepath/mc-6-big-Data.db

`Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Expecting URI in variable: [cassandra.config]. Found[cassandra.yaml]. Please prefix the file with [file:///] for local files and [file://<server>/] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
org.apache.cassandra.exceptions.ConfigurationException: Expecting URI in variable: [cassandra.config]. Found[cassandra.yaml]. Please prefix the file with [file:///] for local files and [file://<server>/] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
        at org.apache.cassandra.config.YamlConfigurationLoader.getStorageConfigURL(YamlConfigurationLoader.java:80)
        at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:100)
        at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:262)
        at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:180)
        at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:151)
        at org.apache.cassandra.tools.Util.initDatabaseDescriptor(Util.java:38)
        at org.apache.cassandra.tools.SSTableMetadataViewer.main(SSTableMetadataViewer.java:82)
`
Please advise, Thanks

**Comment by vroyer** [comment]
The explanation is in the error message, prefix cassandra.config by file:/// ...

**Comment by dbapramod882** [comment]
Sorry, Didn't understood.
Can you please elaborate with an example.

**Comment by vroyer** [comment]
Please prefix the file with [file:///] for local files and [file://<server>/ <file:///]%20for%20local%20files%20and%20[file://%3Cserver%3E/>] for remote files
Your cassandra.config is cassandra.yaml, should file://cassandra.yaml or something like that...

**Comment by dbapramod882** [comment]
I am confused, is it like a command line argument as below.

`/usr/share/cassandra/tools/bin/sstablemetadata file:///etc/cassandra/cassandra.yaml mc-38-big-Data.db
`
Or, is it some thing that needs to be set as environment variable or in cassandra-env.sh file( as in some forums mentioned like `java -Dcassandra.config=file:///etc/cassandra/cassandra.yaml -jar /usr/share/cassandra/lib/cassandra-all-3.11.2.jar`)

**Comment by dbapramod882** [comment]
I have set the below parameter in jvm.options file, but still the same issue.

`# The directory location of the cassandra.yaml file.
-Dcassandra.config=file:///etc/cassandra/cassandra.yaml`

**Comment by dbapramod882** [comment]
Can some one help on this.
