### ISSUE TITLE
cqlsh help pages result in 404 errors

### ISSUE THREAD

**Issue by laran** [strapdata/elassandra#241]
The two help topics I tried took me to pages that were 404s.

```
> bin/cqlsh
cqlsh> help create_type <-- goes to https://cassandra.apache.org/doc/cql3/CQL-3.2.html#createTypeStmt
cqlsh> help insert <-- goes to https://cassandra.apache.org/doc/cql3/CQL-3.2.html#insertStmt
```

**Comment by vroyer** [comment]
Hi,
This is a wrong URL in cqlsh.py coming from the cassandra project.
The good URL is https://cassandra.apache.org/doc/cql3/CQL-3.0.html
This fix will be included in next elassandra release
Thanks.
