### ISSUE TITLE
ES' _source field not present and data mismatch between Cassandra and ES

### ISSUE THREAD

**Issue by Gappa88** [strapdata/elassandra#244]
I have a cluster of 3 nodes with Elassandra 6.2.3.7.
I have created keyspace and table in Cassandra and then created the respective index in ES via **PUT API**. 

After inserted some data into Cassandra, using NodeJS cassandra-driver, I noticed that into the ES index there are too many documents respects Cassandra's. This is caused by some documents in ES that are in some way "empty", the only fields present are `_id`, `_index`, `_type` and `_score` and there is no `_source` field that contains my data.

Example of document without `_source` field
```
....
"hits": {
    "total": 4,
    "max_score": 10.738641,
    "hits": [
      {
        "_index": "myindex",
        "_type": "mytype",
        "_id": """["p1",1543540357000]""",
        "_score": 10.738641
      },
...
```

I have also queried Cassandra for that `_id` and the result is correct, there are no strange entries in there.

The problem is similar to [#226](https://github.com/strapdata/elassandra/issues/226)

What can cause this behaviour?

**Comment by Gappa88** [comment]
After a `rebuild_index` those empty documents disappeared but, after a night of work, empty documents came back.

I did't mention that I have modified `gc_grace_seconds` to 21600, here the structure:

```
CREATE KEYSPACE mykeyspace WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '1'}  AND durable_writes = true;

CREATE TABLE mykeyspace .mytable(
    event_datetime timestamp,
    agent text,
    f1 text,
    ....
    PRIMARY KEY (f1, event_datetime)
) WITH CLUSTERING ORDER BY (event_datetime DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 21600
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_mytable_idx ON mykeyspace .mytable () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';
```

@vroyer could be possible that this behaviour is caused by the compaction process?

**Comment by vroyer** [comment]
Hi,
This happen when a document is indexed in elasticsearch, by can't be retreive from the underlying cassandra table. Elassandra parse the document _id to rebuild its primary key, but in your case, there is strange triple quote around your _id. Check with CQL the document exists. This may also happen when the row is remove from cassandra because deleted or expired.
Thanks.

**Comment by Gappa88** [comment]
thanks @vroyer for the answer.
The strange triple quotes I don't know why they are there. In Cassandra the primary key is: 
`PRIMARY KEY (f1, event_datetime)`

where `f1` is an url. I didn't insert any quotes by myself but they appear by their own.
In Cassandra there are no strange quotes, everything seems ok.


> Check with CQL the document exists

In Cassandra I cannot find that documents because probably my programs deleted it. 
In Cassandra there are no wrong documents, they appear only in Elasticsearch.

> This may also happen when the row is remove from Cassandra because deleted or expired.

This was my guess, but how can I handle this? this causes many issues by my side because when I try to retrieve documents from Elasticsearch I get also these wrong documents.

Why does Elasticsearch is not removing Cassandra's deleted documents? Is there some sort of problem with the synch process?




EDIT:
I just discovered another problem. There are records in Cassandra that are not present into Elasticsearch. They have the same `partition key` but different `clustering column` (because is a timestamp)

**Comment by vroyer** [comment]
If you still face an issue, i would be please to be able to reproduce it with your help.
Thanks.

**Comment by Gappa88** [comment]
hi @vroyer ,
I don't have the exact steps to reproduce this, it isn't happening at any write/delete operation. I can only show you how I have created the keyspace and the ES' Index and how I write and delete records into Cassandra.

here the keyspace, it could differ from the previous one posted because I have changed some configurations, but the problem is still the same:

	CREATE KEYSPACE my_keyspace WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3'}  AND durable_writes = false;
	CREATE TABLE my_keyspace.my_table (
		pkey text,
		event_datetime timestamp,
		f1 text,
		f2 text,
		f3 text,
		f4 text,
		f5 int,
		f6 bigint,
		f7 bigint,
		f8 text,
		f9 text,
		PRIMARY KEY (pkey, event_datetime)
	) WITH CLUSTERING ORDER BY (event_datetime DESC)
		AND bloom_filter_fp_chance = 0.01
		AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
		AND comment = ''
		AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
		AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
		AND crc_check_chance = 1.0
		AND dclocal_read_repair_chance = 0.1
		AND default_time_to_live = 0
		AND gc_grace_seconds = 90000
		AND max_index_interval = 2048
		AND memtable_flush_period_in_ms = 0
		AND min_index_interval = 128
		AND read_repair_chance = 0.0
		AND speculative_retry = '99PERCENTILE';

here the ES index:

	PUT my_keyspace
	 {
	  "mappings": {
		"my_table": {
		  "properties": {
			"f1": {
			  "type": "keyword",
			  "cql_collection": "singleton"
			},
			"f2": {
			  "type": "keyword",
			  "cql_collection": "singleton"
			},
			"event_datetime": {
			  "type": "date",
			  "cql_collection": "singleton",
			  "cql_primary_key_order": 1
			},
			"f3": {
			  "type": "text",
			  "cql_collection": "singleton"
			},
			"f4": {
			  "type": "text",
			  "cql_collection": "singleton"
			},
			"f5": {
			  "type": "long",
			  "cql_collection": "singleton"
			},
			"f8": {
			  "type": "keyword",
			  "cql_collection": "singleton"
			},
			"pkey": {
			  "type": "keyword",
			  "cql_collection": "singleton",
			  "cql_partition_key": true,
			  "cql_primary_key_order": 0
			},
			"f6": {
			  "type": "integer",
			  "cql_collection": "singleton"
			},
			"f7":{
			  "type": "long",
			  "cql_collection": "singleton"
			},
			"f9": {
			  "type": "keyword",
			  "cql_collection": "singleton"
			}
		  }
		}
	  }
	}

`pkey` is an **url**.

here, how I write and delete data in Cassandra:

    insert into my_keyspace.my_table (event_datetime, pkey, f1, f2, f3, f4,f5,f6,f7,f8,f9) values (?,?,?,?,?,?,?,?)
    delete from my_keyspace.my_table where pkey = ? and event_datetime = ?

everyday I delete 1M data and I write another 1M data. 
I found into system.log  logs like the following:

    [MemtableFlushWriter:732] ElasticSecondaryIndex.java:2433 lambda$getBlockingFlushTask$6 Elasticsearch index=[my_keyspace] type=[my_table] flushed, duration=221167ms

that is pretty high time for flushing. 
May this be the cause of the problem?

Thank you very much. 
If you need other information I will be glad to provide it to you.

**Comment by vroyer** [comment]
Inactive ticket (if this is still an issue, please reopen it).
