### ISSUE TITLE
Cluster is broken after upgrade Elassandra version

### ISSUE THREAD

**Issue by evgeniagusakova** [strapdata/elassandra#246]
Hi Team!

In order to fix issue with partitioned indexes (https://github.com/strapdata/elassandra/issues/219) I tried to upgrade Elassandra version from 5.5.0.4 to 5.5.0.24

1. Partitioned indexes issue looks fixed (tested with docker image)
2.  3-nodes Cluster can't join after upgrade and it is in non-operational state

**Elassandra versions**
Before upgrade: 
```
$ dpkg -l | grep elas
ii  elassandra                       5.5.0.4
```
After upgrade:
```
$ dpkg -l | grep elas
ii  elassandra                         5.5.0.24 
```

**JVM version** (`java -version`):
```
java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system)
Sane OS on all nodes:
```
$ uname -a
Linux cf2 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
**Description**:
Elassandra cluster is down after upgrade
**Steps to reproduce**:

1. Install and configure cluster of 3 nodes Elassandra version 5.5.0.4 (not tested with other versions)
(I did my tests on local Virtual Box VMs)
My 3 nodes are 
 - cf1
 - cf2
 - cf3

2. Stop all Elassandra processes  on all nodes
`systemctl stop cassandra`

3. Install new package
` dpkg -i elassandra-5.5.0.24.deb`

4 Start Elassandra
`systemctl start cassandra`

5. Now Cluster is broken:
- on node cf1 Elassandra process is running
```
$ nodetool  status
Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID                               Rack
DN  192.168.56.101  ?          256          100.0%            86c471f8-4cae-4fa9-b25a-f3212fbd7a02  r1
DN  192.168.56.102  319.75 KiB  256          100.0%            90f2456f-7b94-4c84-824e-daf2a87151bb  r1
UN  192.168.56.103  240.91 KiB  256          100.0%            4ab54a6a-f902-4554-bf60-a0421ebaed9d  r1
```
- on nodes cf2 and cf3 process are down

All log/config files are having node name in file name/

Please see servers configuration
[cassandra.yaml.cf1.txt](https://github.com/strapdata/elassandra/files/2660871/cassandra.yaml.cf1.txt)
[cassandra.yaml.cf2.txt](https://github.com/strapdata/elassandra/files/2660872/cassandra.yaml.cf2.txt)
[cassandra.yaml.cf3.txt](https://github.com/strapdata/elassandra/files/2660873/cassandra.yaml.cf3.txt)

And got the following error:
[system.log.cf1.txt](https://github.com/strapdata/elassandra/files/2660878/system.log.cf1.txt)
[system.log.cf2.txt](https://github.com/strapdata/elassandra/files/2660879/system.log.cf2.txt)
[system.log.cf3.txt](https://github.com/strapdata/elassandra/files/2660880/system.log.cf3.txt)

**Important Note**:  I'm not able to update Elassandra to **6.X.X.X** version because upgrade Elasticsearch to 6 version is unacceptable for us at this time. So I need latest Elassandra with fixed partitioned indexes but 100% compatible with 5.X.X.X

Please let me know if you need any additional log or need to reproduce issue with changed configuration and I will set-up tasting lab.

**Comment by evgeniagusakova** [comment]
@vroyer Also this issue has reproduced for 5.5.0.21 version that was suggested as release that will fix  NullPointerException on CassandraDiscovery.updateClusterGroupsFromGossiper (https://github.com/strapdata/elassandra/issues/219#issuecomment-414467607)

**Comment by vroyer** [comment]
Hi,
This is because your internal IP is null, this cause an NPE.
nodetool gossipinfo should confirm that (see INTERNAL_IP).
In your cassandra-rackdc.properties, please try with prefer_local=true on all nodes and restart.
Thanks.

**Comment by sirmax123** [comment]
@vroyer 
I just faced with the same issue and reproduced it with 
```
 elassandra                         5.5.0.21
```
Error looks like described above:
```
 ERROR [main] ElassandraDaemon.java:588 main Exception
java.lang.NullPointerException: null
        at org.elassandra.discovery.CassandraDiscovery.updateClusterGroupsFromGossiper(CassandraDiscovery.java:286)
        at org.elassandra.discovery.CassandraDiscovery.doStart(CassandraDiscovery.java:172)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69)
        at org.elasticsearch.node.Node.start(Node.java:757)
        at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:232)
        at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:551)
```
That is confusing: I use **PropertyFileSnitch** but error looks like related to the **Gossip** protocol  which should not be used with PropertyFileSnitch. (I have not checked source code, but it is  nothong about Gossip in **PropertyFileSnitch**  documentation)

So it looks like PropertyFileSnitch does not work anymore with Elassandra.

As a workaround, I switched from **PropertyFileSnitch** to the **GossipingPropertyFileSnitch**
(only 1 line changed on all nodes)
/etc/cassandra/cassandra.yaml
```
# endpoint_snitch: PropertyFileSnitch
endpoint_snitch: GossipingPropertyFileSnitch
```
 and configured it with the same DC/Rack as all nodes were configured before
/etc/cassandra/cassandra-rackdc.properties
```
dc=DC-which-was-configured-before-in-cassandra-topology.properties
rack=RACK-which-was-configured-before-cassandra-topology.properties
```
and now Elassandra is able to start and nodes can join each other.

From my point of view, it looks like a lack of documentation if **PropertyFileSnitch**  should not be used anymore.

Or it is a critical issue if **PropertyFileSnitch**   is still supported.

**Comment by evgeniagusakova** [comment]
@vroyer 
This workaround works for me.

Thank you.
