### ISSUE TITLE
Install Elassandra on Windows 10 Enterprise

### ISSUE THREAD

**Issue by ltfi** [strapdata/elassandra#247]
How can I run the current version of "elassandra" in "windows 10 entreprise", I can't reach "elasticsearch"
Elasticsearch Port: I'm getting "This site can’t be reached" error.

**Comment by ltfi** [comment]
"cassandra.bat" and "cassandra.ps1"  does not consist any elasticsearch running command.

**Comment by vroyer** [comment]
There is some work to run elassandra on windows, modification form the linux cassandra should be reported to cassandra.bat and cassandra.ps1. Contribution is welcome.

**Comment by vroyer** [comment]
Not currently supported .
