### ISSUE TITLE
The index is still keeping dynamic update even that index mapping has configured dynamic: false

### ISSUE THREAD

**Issue by figo-yu** [strapdata/elassandra#257]
**Elassandra version**: elassandra:5.5.0.24

**Plugins installed**: NONE

**JVM version**: 
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version**:
3.10.0-862.9.1.el7.x86_64  x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
We setup a small elassandra cluster(3 nodes)
**Problem**: Elassandra dynamically updates the index mapping when inserted a new row with more new keys in a map field, even the index mapping has set the **dynamic** flag to **false**
**Expected behavior**: Elassandra keeps the index mapping as it once created.
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/dynamic.html

**Steps to reproduce**:

 1. create the key space 'mytest' and table 'mymaptable':
<pre>
CREATE KEYSPACE mytest WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'DC1': '2'};
use mytest;
CREATE TABLE mymaptable (
    id text,
    name text,
    counters map<text, int>,
    PRIMARY KEY ( id ) 
);
</pre>
 2. create index 'dyntest '
`curl -XPUT http://localhost:9200/dyntest -d @/dyn_mapping_check.json`
the **dyn_mapping_check.json** content:
<pre>
{
    "settings": {
        "keyspace": "mytest"
    },
    "mappings": {
        "mymaptable": {
            "dynamic": false,
            "properties": {
                "id": {
                    "type": "keyword",
                    "cql_partition_key" : true,
                    "cql_collection": "singleton",
                    "cql_primary_key_order": 0
                },
                "name": {
                    "type": "keyword",
                    "cql_collection": "singleton"
                },
                "counters": {
                    "dynamic": false,
                    "type": "nested",
                    "cql_struct": "map",
                    "cql_collection": "singleton",
                    "properties": {
                        "retry": {
                            "type": "integer"
                        },
                        "fail": {
                            "type": "integer"
                        }
                   }
               }
            }
        }
    }
}
</pre>
 3. use cqlsh tool to insert 2 rows:
<pre>
insert into mytest.mymaptable (id, name, counters) values ('john.d', 'john', {'tps':1000, 'retry':1});
</pre>
<pre>
insert into mytest.mymaptable (id, name, counters) values ('Kelly.S', 'kelly', {'tps':1200, 'fail':2, 'pending':100}); 
</pre>

4. check whether the index mapping keep as it:
curl -XGET http://localhost:9200/dyntest?pretty
<pre>
{
  "dyntest" : {
    "aliases" : { },
    "mappings" : {
      "mymaptable" : {
        "dynamic" : "false",
        "properties" : {
          "counters" : {
            "type" : "nested",
            "cql_struct" : "map",
            "cql_collection" : "singleton",
            "dynamic" : "false",
            "properties" : {
              "fail" : {
                "type" : "integer"
              },
              "pending" : {
                "type" : "integer"
              },
              "retry" : {
                "type" : "integer"
              },
              "tps" : {
                "type" : "integer"
              }
            }
          },
          "id" : {
            "type" : "keyword",
            "cql_collection" : "singleton",
            "cql_partition_key" : true,
            "cql_primary_key_order" : 0
          },
          "name" : {
            "type" : "keyword",
            "cql_collection" : "singleton"
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "keyspace" : "mytest",
        "number_of_shards" : "3",
        "provided_name" : "dyntest",
        "creation_date" : "1545887324964",
        "number_of_replicas" : "1",
        "uuid" : "XaWOdvh9STa--IIk6PcNFA",
        "version" : {
          "created" : "5050099"
        }
      }
    }
  }
}
</pre>
We saw that all the keys in the map field have been updated to the index mapping. The expected behavior is it shall keep as **only having "retry" and "fail"**

@vroyer If there is any more information required, please let me know, thanks.

**Comment by vroyer** [comment]
Thanks for reporting this issue, it fixed in the next release 6.2.3.10.

**Comment by figo-yu** [comment]
@vroyer , good to know it will fix in 6.2.3.10. Will the fix be merged back to 5.5.0.x version?
