### ISSUE TITLE
No draining of Cassandra node before killing it in init script

### ISSUE THREAD

**Issue by AlexisWilke** [strapdata/elassandra#259]
**Describe the feature**:

Not too sure whether to describe this one as a bug since all versions of Cassandra do it wrong, so I'll mark it as a feature.

The `stop` command of the init.d script (at least in the RPM, but probably all of them), just runs:

    killproc -p $pidfile -d 86400 $prog

which means that the node gets killed immediately.

I would like to propose to run `nodetool` as follow to first drain the node:

    for cmd in disablegossip disablethrift disablebinary drain
    do
            nodetool $cmd
    done

This makes the `stop` a bit slower but `start` pretty much instantaneous because it won't have to reply all the journals.

**Plugins installed**: [none]

**JVM version** (`java -version`):

    $ java -version
    java version "1.8.0_192"
    Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

    $ uname -a
    Linux ip-172-31-24-11.ec2.internal 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

When just killing the app it leaves journals open which then need to be worked on after a restart.

**Steps to reproduce**:

 1. `sudo systemctl start`
 2. add data
 3. quickly afterward: `sudo systemctl stop`
 4. `sudo systemctl start`

Step (4) is very slow as it has to replay a large part of (2).

**Please provide the following information:

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)

n.a.

* elasticsearch cluster state (curl http://localhost:9200/_cluster/state)

n.a.

* cassandra schema (cqlsh>DESC KEYSPACE <your_keyspace>)

n.a.

* cassandra gossip state (run: nodetool gossipinfo)

n.a.

**Comment by DBarthe** [comment]
Hello,
This is true but we try to make elassandra behave like cassandra for compatibility with existing cassandra tooling.
You should do it manually or write a script to do this automatically.
Thanks
