### ISSUE TITLE
upgrade to cassandra 3.x

### ISSUE THREAD

**Issue by ghost** [strapdata/elassandra#26]
Hi,
Do you plan an upgrade to Cassandra 3 ?
Because the [storage engine has been refactored](https://issues.apache.org/jira/browse/CASSANDRA-8099) and also the new feature [Materialized Views](http://www.datastax.com/dev/blog/new-in-cassandra-3-0-materialized-views).
A lot of improvement are here too.
Thanks a lot.

**Comment by vroyer** [comment]
Hi,
Yes, cassandra 3 will be supported in few months.
Thanks'.

**Comment by igama** [comment]
👍

**Comment by yhilem** [comment]
Hi,
Is there a timeline for cassandra 3 ?
Thanks

**Comment by dxps** [comment]
Hi,

Any news about Production release and Cassandra 3?
[This](http://www.slideshare.net/DataStax/elassandra-elasticsearch-as-a-cassandra-secondary-index-rmi-trouville-vincent-royer-independent-c-summit-2016) is a recent presentation touching a little these subjects.

Thanks

**Comment by vroyer** [comment]
Hi,

I have released elassandra 2.4.2-4 based on cassandra 3.0.10 and Elasticsearch 2.4.2.
Thanks.
Vincent.
