### ISSUE TITLE
cassandra-stress not working

### ISSUE THREAD

**Issue by Gappa88** [strapdata/elassandra#261]
Elassandra version:
6.2.3.7 installed from .deb package

JVM version:
1.8.0_191

I need to benchmark existing installation and cluster, I tried run 

**/usr/share/cassandra/tools/bin/cassandra-stress** from elassandra got an error.

**Steps to reproduce:**

Execute /usr/share/cassandra/tools/bin/cassandra-stress fails with the following message:

**Error: Could not find or load main class org.apache.cassandra.stress.Stress**

@vroyer , is there any patch to fix this?

**Comment by mimarpe** [comment]
Hi,

I ran into the same issue but found that the lib folder is missing for the tools in the installation. Namely the stress.jar.
For me it just worked to copy the tools/lib folder of the stock cassandra into $CASSANDRA_HOME/tools/lib

Why it was excluded from the installation, I don't know...

Regards

**Comment by DBarthe** [comment]
Hello,

Sorry, this is because when packaging elassandra, we did not build the stress.jar from cassandra...

This is already fixed but not yet released...

If you need it now, you can use the stress-tool from the official cassandra distribution.

**Comment by Gappa88** [comment]
ok thanks @mimarpe  @DBarthe
