### ISSUE TITLE
why elassandra uninstall the elastic search default plugins?

### ISSUE THREAD

**Issue by ravikoda** [strapdata/elassandra#263]
elastic search 6.2.3 comes with following plugins by default

GpsIUzc ingest-geoip       6.2.3
GpsIUzc ingest-user-agent  6.2.3
GpsIUzc x-pack-core        6.2.3
GpsIUzc x-pack-deprecation 6.2.3
GpsIUzc x-pack-graph       6.2.3
GpsIUzc x-pack-logstash    6.2.3
GpsIUzc x-pack-ml          6.2.3
GpsIUzc x-pack-monitoring  6.2.3
GpsIUzc x-pack-security    6.2.3
GpsIUzc x-pack-upgrade     6.2.3
GpsIUzc x-pack-watcher     6.2.3

but when I start elassandra not able to see none of the plugins, therefore my kibana won't start properly.

please suggest.

**Comment by vroyer** [comment]
Hi,

Before elasticsearch 6.3, x-pack was not included in elasticsearch code, see https://www.elastic.co/products/x-pack/open

Elassandra currently rely on 6.2.3, so x-pack is not included, and ingest plugin should be installed separately, 
see https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-geoip.html

Thanks.
