### ISSUE TITLE
ES to Cassandra update Delete

### ISSUE THREAD

**Issue by writeaditya** [strapdata/elassandra#265]
As we know we use elassandra to create sync from cassandra to ES. Now my query is can we do this vice versa like whenever I update any statement from ES, will it get updated/deleted on cassandra as well ? if Yes, how ? can you please share an example.

Thanks,
Aditya

**Comment by vroyer** [comment]
Yes, if you insert, update or delete an Elasticsearch document through the REST API, this also update the underlying cassandra row.

Here is 2 insert that update the same cassandra row (keyspace=test, table=doc, row pk="1"):

curl -H 'Content-Type: application/json' -XPUT "$PROTOCOL://localhost:9200/test/doc/1" -d'{"foo":"bar"}'

curl -H 'Content-Type: application/json' -XPUT "$PROTOCOL://localhost:9200/test/doc/1" -d'{"foo":"bar2"}'

**Comment by writeaditya** [comment]
ok I understood. Thanks for solution. closing this issue.
