### ISSUE TITLE
Lucene hard limit on number of docs

### ISSUE THREAD

**Issue by dbapramod882** [strapdata/elassandra#267]
Lucene is having a hard limit on number of docs.

So in Elassandra, will the doc limit be per partition or per node.
Example: If I enable num_tokens:64, Does it imply each 64 partitions will have 2billion limit (1st partition= 2B values, 2nd Partition=2B values etc)

or

that node will have a total limit of 2B values regardless of number of partitions.

Thanks

**Comment by vroyer** [comment]
Hi,

Lucene hard limit is per index shard.
By default, Elassandra has one shard per index and per node (not per cassandra partition).
You can override this limit by partitioning your index (see http://doc.elassandra.io/en/latest/mapping.html#partitioned-index ), split the index shard into 2 or more shards on each Elassandra node.

In cassandra, num_token is not a number of tokens, but a number of token ranges per nodes.
For example, with 3 nodes and num_token=8,  the 2^128 ring is divided into 24 token ranges, and each node have 8 token ranges.
