### ISSUE TITLE
Is it possible to replace c* part with ScyllaDB?

### ISSUE THREAD

**Issue by sokoow** [strapdata/elassandra#268]
It'd be fun to see if ScyllaDB can be used as a swap on for java based c* ? Would this be possible ? Any pointers on how to test that ?

**Comment by DBarthe** [comment]
Hi, Elasticsearch and Cassandra are both Java and that's why the merge is feasible. Doing so with ScyllaDB (c++) would be much harder at first sight.

**Comment by sokoow** [comment]
So these two parts are not separate ? You basically included cassandra as a java library, and didn't connect it up on an API basis ?

**Comment by DBarthe** [comment]
Yes basically elasticsearch code is embedded in the same jvm running
Cassandra.

Cassandra allows users to implement their own `CustomSecondaryIndex` (java
api). Elassandra has implemented an `ElasticsearchSecondaryIndex`. That's
where most of the intersection code resides. Elasticsearch is integrated
like a plugin for Cassandra.

Scylla probably has the same feature but for c++.

**Comment by vroyer** [comment]
No sorry !  ScyllaDB is not developed in java and is based on a TPC (thread-per-core) architecture, so elasticsearch integration is not a piece of cake.
