### ISSUE TITLE
Performance issues with many appends to big collection types (list or set) in underlying CQL structure.

### ISSUE THREAD

**Issue by Derya** [strapdata/elassandra#269]
We have a schema with a CQL collection (we've tried both list and set) of a UDT like so:
```
list<FROZEN <event>>
```
(I have the full schema at the bottom of this post)
This CQL collection becomes a nested type in the Elasticsearch index. We query via Elasticsearch but the only changes to data happen via CQL updates. These CQL update requests involve appending to this collection. This works fine normally but when we have thousands of them happening in quick succession, our Elassandra node runs into issues. The node memory/CPU usage skyrocket and further requests start to time out, rendering the node unusable. When this happens we see a lot of GC warnings:

```
2019-02-23 01:16:23,690 WARN [elasticsearch[10.0.4.91][scheduler][T#1]] org.elasticsearch.monitor.jvm.JvmGcMonitorService.logGcOverhead(JvmGcMonitorService.java:316) [gc][8701] overhead, spent [626ms] collecting in the last [1.1s]
```

I can insert the data into CQL directly via the same query and at the same volume with Elassandra running when there is NO Elasticsearch index configured without any of the requests timing out. Only if I create the index beforehand do I see the behaviour with timeouts occurring. I can even create the index after the data is in place, and it works fine. I can also create the index beforehand and insert the data in one go (rather than appending each entry to the collection one by one) and it still works fine.

Software versions: This is the docker image `elassandra:6.2.3.4`
Cluster setup: We're running this via docker on 3x m4xlarge machines on AWS, however running a single node locally on my machine (via docker or via the regular binary) yields the same behaviour. Meaning that without any Elasticsearch index configured, the CQL writes to Elassandra work fine, but with the index set up for our table, the node still gets destroyed.

CQL schema:
```
CREATE KEYSPACE IF NOT EXISTS foo WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1' : 1} AND durable_writes = true;

CREATE TYPE foo.prop (
   name varchar,
   value varchar
);

CREATE TYPE foo.event (
  session_id varchar,
  name varchar,
  date timestamp,
  x_coord double,
  y_coord double,
  z_coord double,
  props list<FROZEN <prop>>
);

CREATE TABLE IF NOT EXISTS foo.by_session (
  session_id varchar,
  date timestamp,
  events list<FROZEN <event>>,
  session_props list<FROZEN <prop>>,
  PRIMARY KEY((session_id))
);
```

Elasticsearch index mapping:
```
{
  "by_session": {
    "properties": {
      "date": {
        "type": "date",
        "cql_collection": "singleton"
      },
      "events": {
        "type": "nested",
        "cql_udt_name": "event",
        "properties": {
          "date": {
            "type": "date",
            "cql_collection": "singleton"
          },
          "name": {
            "type": "keyword",
            "cql_collection": "singleton"
          },
          "props": {
            "type": "nested",
            "cql_udt_name": "prop",
            "properties": {
              "name": {
                "type": "keyword",
                "cql_collection": "singleton"
              },
              "value": {
                "type": "keyword",
                "cql_collection": "singleton"
              }
            }
          },
          "session_id": {
            "type": "keyword",
            "cql_collection": "singleton"
          },
          "x_coord": {
            "type": "double",
            "cql_collection": "singleton"
          },
          "y_coord": {
            "type": "double",
            "cql_collection": "singleton"
          },
          "z_coord": {
            "type": "double",
            "cql_collection": "singleton"
          }
        }
      },
      "session_id": {
        "type": "keyword",
        "cql_collection": "singleton",
        "cql_partition_key": true,
        "cql_primary_key_order": 0
      },
      "session_props": {
        "type": "nested",
        "cql_udt_name": "prop",
        "properties": {
          "name": {
            "type": "keyword",
            "cql_collection": "singleton"
          },
          "value": {
            "type": "keyword",
            "cql_collection": "singleton"
          }
        }
      }
    }
  }
}
```

We tried the same setup with a set instead of a list for our collection type, and the behaviour seems to be the same.

Is it possible to set Elassandra up so that high frequency appends to a collection work?

**Comment by vroyer** [comment]
Hi,

When updating a cassandra collections (set, list, map), Cassandra update (or add) just cell in the row. When indexing such a row, elassandra reads all the row to index an elasticsearch document. So each time you ad (or update) a cassandra cell in a collection, it involves a read-before-write to build the full elasticsearch document. At a high rate, this cause contention on the row due to concurrent reads and updates on the same B-Tree (same row).

You should probably change you schema to store events in a cassandra wide row (session_id = partition key, event_id = clustering_key) and many elasticsearch documents having the same session_id. Thus, read-before-write would be a "small" with no contention (and date field could be indexed as a static column, see this [blog](https://medium.com/@vroyer/kubernetes-logs-analysis-with-elassandra-fluent-bit-and-kibana-4f827854e5c8) about storage optimization)

Moreover, if you only append events (no updates), you could enable index.index_insert_only=true (in version 6.2.3.11) to disable the read-before-write and get better write throughput.

To upgrade from 6.2.3.4 to 6.2.3.11, read update instruction from the README.
Thanks.

**Comment by Derya** [comment]
Many thanks for the help.

We are, in fact, only appending to `events`. So we upgraded to 6.2.3.11 and with the `index_insert_only` setting performance is great even for very large collections. That's some ludicrously good timing for us, with that release from 2 weeks ago!

**Comment by Derya** [comment]
@vroyer Hi again! Actually it seems that I've misinterpreted you on the usage of `index_insert_only` setting. You meant that if we had our events in a separate table, we could use that setting for increased performance. That setting does solve our performance issues but it otherwise breaks our use case, which probably isn't a surprise to you but I'll detail what I mean exactly just in case.

So for example if I append my first event: 
```
UPDATE foo.by_session SET events = events + [{session_id: 'sessionid', name: 'event1', date: 5, x_coord: 0, y_coord: 0, z_coord: 0, props: null}] WHERE session_id = 'sessionid';
```
This shows up in Elasticsearch just fine as expected but once we append another event:
```
UPDATE foo.by_session SET events = events + [{session_id: 'sessionid', name: 'event2', date: 5, x_coord: 0, y_coord: 0, z_coord: 0, props: null}] WHERE session_id = 'sessionid';
```
Our indexing is messed up due to this improper usage of `index_insert_only`. If we query the index in ES like this:
```
{
  "query": {
    "bool": {
      "must": [{
        "nested": {
          "path": "events",
          "query": {
            "term": { "events.name": { "value": "event1" } }
          }
        }
      }]
    }
  }
}
```
We see 0 hits. That ES response:
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```
However if we either remove the query entirely or change it match the latest record appended to the collection (in this example, this means just changing the "event1" to "event2" and leaving the rest the same), we do actually see all the events in the ES document. That ES response:
```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0.2876821,
    "hits": [
      {
        "_index": "sessions_by_version",
        "_type": "by_session",
        "_id": "sessionid",
        "_score": 0.2876821,
        "_source": {
          "date": "1970-01-01T00:00:00.005Z",
          "session_id": "sessionid",
          "events": [
            {
              "date": "1970-01-01T00:00:00.005Z",
              "x_coord": 0.0,
              "name": "event1",
              "session_id": "sessionid",
              "y_coord": 0.0,
              "z_coord": 0.0
            },
            {
              "date": "1970-01-01T00:00:00.005Z",
              "x_coord": 0.0,
              "name": "event2",
              "session_id": "sessionid",
              "y_coord": 0.0,
              "z_coord": 0.0
            }
          ]
        }
      }
    ]
  }
}
```

We don't want to update our schema for a few reasons, but the main one is that we don't just have an events collection but a few other collections too. We want to be able to make ES queries of the form "show me the bars in foos where there was any 'event1' event". Where those "bar"s are a collection column just like the events column. Since Elasticsearch only allows joining on one field per index, we wouldn't be able to make that kind of query if we had a separate table for our events and a separate table for our "bar"s.

I think most likely the answer here is that we're out of luck and can't expect to abuse `index_insert_only` in this way, but I'm asking to make sure there isn't some angle we're missing here. I find it interesting that the Elasticsearch documents end up with the correct values, but just aren't indexed correctly for queries and aggregations. Is there some way we could get the collection column indexing properly? Something like a `collection_column_insert_only` would be great, though I have no idea if it's possible. Could there be some way to read and build that index periodically indepedently of the rate of appends to that column?

Thank you so much for the help as always.

**Comment by vroyer** [comment]
Yes, index_insert_only options means no UPDATE, and you do UPDATE to add events ;-)
Again, updating an Elasticsearch document each time you add an event require a costly read-before-write, and this would be the same with the vanilla elasticsearch.

As suggested in my previous post, you should use wide rows with static columns to do such thing, and you'll be able to query for sessions having event X... To go further, if you want to work under NDA and share more info about your needs and data, we can provide remote consulting.
Thanks.

**Comment by Derya** [comment]
Understood. Thanks for the advise and assistance.
