### ISSUE TITLE
Unable to create 2 node cluster for elassandra

### ISSUE THREAD

**Issue by writeaditya** [strapdata/elassandra#270]
Hi vroyer,

I'am trying to create a 2 node cluster of elassandra, but it is not making connection. Same thing I tried using cassandra it works fine, but for elassandra , configuration does not seems to work.

/etc/cassandra/cassandra.yaml
. . .

cluster_name: 'CassandraDOCluster'

. . .

seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
         - seeds: "your_server_ip,your_server_ip_2,...your_server_ip_n"

. . .

listen_address: your_server_ip

. . .

rpc_address: your_server_ip

. . .

endpoint_snitch: GossipingPropertyFileSnitch

. . .

Whats the issue ? Can you please help.
Thanks

**Comment by vroyer** [comment]
Hi,

Elassandra is cassandra, you cassandra config file should be the same for cassandra and elassandra.
Please provide logs or output of your issue.
Thanks.

**Comment by writeaditya** [comment]
Hi vroyer,

I changed parameters as mentioned in Question. that is I put IP of both nodes in Seeds block , then IP of particular node in listen_address &  rpc_address and snitching was set to this endpoint_snitch: GossipingPropertyFileSnitch. Now after start up when I checked nodetool status, it is not showing other node. Both machines showing only their respectic nodes. Rest everything kept as default. 
Which logs should I provide you ? Elassandra startup log ? Can you please try at your end and check or should I also provide you my config files but, I don't know how to add them.
 
*Node - Both nodes are on LAN and can be ping from each other.

**Comment by DBarthe** [comment]
Hello,
For the logs you can provide `/var/log/cassandra/system.log` (might be elsewhere depending on your installation).
Have you tried disabling the firewall on both node ?

**Comment by writeaditya** [comment]
[system.log](https://github.com/strapdata/elassandra/files/2970409/system.log)
[cassandra.yaml.txt](https://github.com/strapdata/elassandra/files/2970427/cassandra.yaml.txt)
[cassandra-env.sh.txt](https://github.com/strapdata/elassandra/files/2970430/cassandra-env.sh.txt)
[cassandra-rackdc.properties.txt](https://github.com/strapdata/elassandra/files/2970431/cassandra-rackdc.properties.txt)
[cassandra-topology.properties.txt](https://github.com/strapdata/elassandra/files/2970432/cassandra-topology.properties.txt)

In logs, there is not handshaking thing, as we generally get handshaking at the time of start up but in this case I'am not getting handshaking.

I'am also attaching my other config files, may be if that can help to replicate the issue for you.

Yes, Firewall is disabled thats why I'am able to create a cluster with Vanilla Cassandra but not with Elassandra.

**Comment by writeaditya** [comment]
any update vroyer ?

**Comment by writeaditya** [comment]
Hi Vroyer/ DBarthe,

Have you checked or able to replicate the issue at your end ? I'm really looking for a solution at earliest.

**Comment by vroyer** [comment]
Sorry for this late response.
You had IP binding issues in your logs.
