### ISSUE TITLE
Performance optimization of Elassandra 5.5.0.24 cluster

### ISSUE THREAD

**Issue by evgeniagusakova** [strapdata/elassandra#276]
Elassandra : 5.5.0.24

JDK : 1.8.0_181

Hello,
We have production cluster which contains 9 Elassandra nodes with RF=3 and faced with high CPU usage on all nodes which leads to the  high responce time from the application.
Currently we are using default settings(PrimaryFirstSearchStrategy and index.token_ranges_bitset_cache is disabled). So we've decided to follow performance improvement suggestions from the documentation :

1. Change **PrimaryFirstSearchStrategy** to **RandomSearchStrategy** if RF>1. We have tested it on staging environment (3 nodes and RF=3) and noticed that CPU usage during requests was decreased and response time was decreased too in 10% on the average. 

**The question is what is expected result for cluster with 9 nodes and RF =3?**

2. Enable **index.token_ranges_bitset_cache**. We've enable index.token_ranges_bitset_cache but seems it's not working. When we checked the in-memory size of the token ranges bitset cache with the Elasticsearch stats API we always see that counter for token_ranges_bit_set_memory_in_bytes doesn't grow up :`"token_ranges_bit_set_memory_in_bytes": 0` (checked by query `curl "http://XX.XX.XX.XX:9200/IndexNameHere/_stats?pretty=true" `)

**The question is how we can check if it works or not?**

The query that we used to change search strategy and enable index.token_ranges_bitset_cache for existing indexes.

`$ curl -XPUT "http://XX.XX.XX.XX:9200/*/_settings" -d '{ "settings" : { "index.search_strategy_class":"RandomSearchStrategy", "index.token_ranges_bitset_cache" : "true" } }'`

The example of index settings after changes were applied 

```
$ curl  "http://XX.XX.XX.XX:9200/IndexNameHere/_settings" | jq .

{
  "IndexNameHere": {
    "settings": {
      "index": {
        "keyspace": "KeyspaceNameHere",
        "number_of_shards": "3",
        "partition_function_class": "org.elassandra.index.StringPartitionFunction",
        "provided_name": "IndexNameHere",
        "creation_date": "1554980834198",
        "partition_function": "d_byymd IndexNameHere_%1$tY_%1$tm_%1$td publish_date",
        "number_of_replicas": "2",
        "uuid": "1QEfn0_yQEqv9gvVEPgYgw",
        "version": {
          "created": "5050099"
        },
        "search_strategy_class": "RandomSearchStrategy",
        "token_ranges_bitset_cache": "true"
      }
    }
  }
}

```

**Comment by vroyer** [comment]
Your settings are fine, using RF=3 with the RandomSearchStrategy should lower the CPU. You should also upgrade to version 6.x, because lucene 7.x has improvement on numeric range search used by Elassandra to filter on cassandra tokens. Then look at your system and GC settings to improve perfs.
