### ISSUE TITLE
Availability of copy fields in elassandra 

### ISSUE THREAD

**Issue by chakri-stark** [strapdata/elassandra#277]
Hi @vroyer / @DBarthe  ,

Can you please confirm on availability of copy fields in elassandra? If available, please let me know any reference.
Secondly, If a table already exists in elassandra, can we create a elastic search index on it? If yes, how?

**Comment by DBarthe** [comment]
Hi @chakri-stark,

Copy_to is not supported by Elassandra (see [elasticsearch unsupported features](http://doc.elassandra.io/en/latest/limitations.html#elasticsearch-unsupported-features)).
It is a TODO that may be addressed soon.

To answer you second question, if you create an ES index with a name matching a keyspace and a type matching a table, it will index the table. The ES mapping must be compatible with the underlying CQL schema. To simplify the task there is a `discover: ".*"` option added to the ES mapping DSL, which infers automatically the ES mapping based on the CQL schema.

This [quickstart](http://doc.elassandra.io/en/latest/quickstart.html) shows how to.

**Comment by chakri-stark** [comment]
Thanks @DBarthe , closing this issue. Looking forward to have copy fields in elassandra. :)

**Comment by Galdanwing** [comment]
Just a quick question: I no longer see copy to in that last of unsupported features and I see some small mentions of it in your codebase, is this now supported? and if so: How? I tried to create a mapping like this:
```
"properties" : {
               "first_name" : { "type":"keyword", "cql_collection":"singleton", "copy_to": "full_name" },
               "last_name": { "type":"keyword", "cql_collection":"singleton", "copy_to": "full_name" },
               "full_name":{ "type":"text", "cql_collection":"none"}

            }
```
But I had no luck with that approach.
