### ISSUE TITLE
Elasticsearch doesnt replicate when we use index_opaque_storage setting

### ISSUE THREAD

**Issue by chethan1985** [strapdata/elassandra#281]
Steps to reproduce
---------------------
1. Setup an K8 cluster
2. Setup a 3 node elassandra cluster using the attached yamls - The Elassandra image being used has the following settings set in jvm.options
es.index_opaque_storage=true
es.delete_on_drop_index=true
3. Create an index using ES API
5. Now run search on that index

Observed
The search returns 0 results 

Expected
The search return the data that was just created
[ElassandraYamls.zip](https://github.com/strapdata/elassandra/files/3125997/ElassandraYamls.zip)

**Comment by vroyer** [comment]
Thanks for reporting the issue.
This is fixed in the last release 6.2.3.14.
