### ISSUE TITLE
Unable to create geo_shape index

### ISSUE THREAD

**Issue by ngulyaev** [strapdata/elassandra#282]
Elassandra version: 6.2.3.13-14
jvm: openjdk version "1.8.0_212"
OS: Linux 631697ed6903 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
docker image: strapdata/elassandra:latest

Hello, i'm trying to create geo_shape index for field with following request:
PUT http://localhost:9200/weather
`{
    "settings": {
    	"keyspace":"weather"	
    },
    "mappings": {
	    "weather_data" : {
	    	"_source": {
	    		"enabled": true
	    	},
	        "properties": {
	        	"geom": {
	        		"type":"geo_shape"
	        	}
	        }
	    }
    }
}`

got the error:

`{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "Failed to execute query:null : Existing column [geom] type [text] mismatch with inferred type [list<text>]"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Failed to execute query:null : Existing column [geom] type [text] mismatch with inferred type [list<text>]",
        "caused_by": {
            "type": "configuration_exception",
            "reason": "Existing column [geom] type [text] mismatch with inferred type [list<text>]"
        }
    },
    "status": 400
}`

The weather table:
`CREATE TABLE weather.weather_data (
    id text,
    updated_at timestamp,
    alt int,
    created_at timestamp,
    es_options text,
    es_query text,
    geom text,
    predict tinyint,
    radius int,
    time timestamp,
    type tinyint,
    version bigint,
    weather text,
    x int,
    y int,
    PRIMARY KEY (id, updated_at)
) WITH CLUSTERING ORDER BY (updated_at DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';`

Why geo_shape index needs list<text> type?

And if add 'cql_collection' parameter to index request:
`{
    "settings": {
    	"keyspace":"weather"	
    },
    "mappings": {
	    "weather_data" : {
	    	"_source": {
	    		"enabled": true
	    	},
	        "properties": {
	        	"geom": {
	        		"type":"geo_shape",
	        		"cql_collection":"singleton"
	        	}
	        }
	    }
    }
}`

I got the following error:
`{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "Mapping definition for [geom] has unsupported parameters:  [cql_collection : singleton]"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Failed to parse mapping [weather_data]: Mapping definition for [geom] has unsupported parameters:  [cql_collection : singleton]",
        "caused_by": {
            "type": "mapper_parsing_exception",
            "reason": "Mapping definition for [geom] has unsupported parameters:  [cql_collection : singleton]"
        }
    },
    "status": 400
}`

How can I create geo_shape index with field type 'text'?

**Comment by vroyer** [comment]
By default, elasticsearch field are multi-valued, so field are backed by a Cassandra list<X>.
cql_collection : singleton allow to back fields by X (where X is text, int, long etc....), but the elasticsearch geo_shape type parser does not inherits from all usual properties including the cql_collection, so it fails.

As a workaround, you could use geom list<text>. 
We have fixed that, and the next release will accept cql_collection: singleton for geo_shape.

Thanks.

**Comment by ngulyaev** [comment]
Thanks, when i change geom filed type to 'list', i get the error in cassandra logs:
`ElasticSecondaryIndex.java:2198 buildContext error
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: $POLYGON ((0 0, 0 5000, 5000 0, 0 0));`

**Comment by vroyer** [comment]
There is bad characters in your json polygon.

**Comment by vroyer** [comment]
Stale issue
