### ISSUE TITLE
Replication problem in elasticsearch in multi datacenter elassandra 

### ISSUE THREAD

**Issue by pramodShehan5** [strapdata/elassandra#284]
I have setup multi data center elassandra cluster. Created keyspace with RF=3 and a table connects

CREATE KEYSPACE IF NOT EXISTS test
WITH replication = {
    'class':'NetworkTopologyStrategy',
     'DC1':'3',
     'DC2':'3'
};

CREATE TABLE IF NOT EXISTS test.address (
    street TEXT,
    number TEXT,
    country TEXT,
    PRIMARY KEY(number)
);
Then created elastic index with the connects table from DC1 node.

curl -XPUT "http://myelassandra1:9200/connects" -d '{
    "settings":{
          "keyspace": "test"
     },
    "mappings": {
        "connects" : {
             "discover" : ".*"
         }
     }
}
'
When I'm looking at the elastic index replications, in one data center it gives 5 and other data center it gives nothing. Only there is one primary shards. Is this the known behavior of elassandra?

DC1

 "settings" : {
      "index" : {
        "keyspace" : "test",
        "number_of_shards" : "3",
        "provided_name" : "address",
        "creation_date" : "1556768554654",
        "number_of_replicas" : "5",
        "uuid" : "OeU_NGh9RBS-EurNFfb3Ig",
        "version" : {
          "created" : "6020399"
        }
      }

DC2

"settings" : {
      "index" : {
        "keyspace" : "test",
        "creation_date" : "1556768554654",
        "uuid" : "OeU_NGh9RBS-EurNFfb3Ig",
        "version" : {
          "created" : "6020399"
        },
        "provided_name" : "address"
      }
    }

Is there any way to have the same elastic replication on each data center?

**Comment by vroyer** [comment]
Please see #283 (same issue).

**Comment by pramodShehan5** [comment]
Hi vroyer, 

In my case, it is only created one primary shards in DC2. No replication shards. It should be created 3 primary shards and 5 replication shards.

Is this also issue?

**Comment by vroyer** [comment]
No, number of replica are just informational. 
In elassandra, there is always a shard per index on each nodes.

**Comment by vroyer** [comment]
Stale issue, please reopen it if it's still an issue.
