### ISSUE TITLE
Issue in Writes/PUT due to Privileges after setting Active-Active Data Centers

### ISSUE THREAD

**Issue by ackarande** [strapdata/elassandra#285]
Hi,
After setting up Active-Active setup - I am facing issues in writing data to one for the node in cluster due to privileges.

Steps I followed:
1. Setup Datacenter 1 with data center group as datacenter_group.
2. Inserted roles in elastic_admin_datacenter_group.privileges.
3. Setup Datacenter 2 with data center group as datacenter_group.
4. Inserted roles in elastic_admin_datacenter_group.privileges.
5. Add seeds node in datacenter 1 and datacenter 2.
6. Restarted the cluster.
7. Issued a PUT index request.

I checked the elastic_admin_datacenter_group.privileges table in all the nodes and found the in few nodes the data was missing. Wondering how this can happen.

Could you please help?

**Comment by DBarthe** [comment]
Hello,

Can you provide the output of the write operation that failed, and the
output of 'nodetool status' ?

Thanks

**Comment by ackarande** [comment]
Hi,

nodetool status provides output having all the nodes of both the DCs and UN, which is normal. 
However, I see that when I login to cqlsh and check the index tables on one DC, I see topology as below

In DC1
{'class' : 'NetworkTopologyStrategy', 'DC2' : 2}

Due to this I see state of index as red in GET _/indices. 

Thanks

**Comment by vroyer** [comment]
Yes, keyspace must be replicated on DC1 to be indexed in ES.

**Comment by ackarande** [comment]
Thanks for reply. 
Could you please let me know exact steps that are needed here? 
Considering my index name is sampleindex and datacenters I have DC1 and DC2

**Comment by vroyer** [comment]
Sorry for this late response (we serve our customer first), but it seems you want a secured elassandra cluster on 2 datacenters DC1 and DC2, having the same or distinct elasticsearch mapping on DC1 and DC2 ?

**Comment by ackarande** [comment]
Hi,

We want same mapping on both DCs, i.e. replication. The steps which I mentioned causes issue. How can I recover from such situation 


Thanks

**Comment by vroyer** [comment]
So, you don't need any datacenter_goups, just cassandra replication between your DCs.
If you want more help, strapdata provides professionnel support and consulting services.

**Comment by vroyer** [comment]
Closing inactive ticket
