### ISSUE TITLE
Can not delete specific ES index until deleted all the indices created for the same table

### ISSUE THREAD

**Issue by figo-yu** [strapdata/elassandra#286]
**Elassandra version**: elassandra:6.2.3.14

**Plugins installed**: NONE

**JVM version** (`java -version`):
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
3.10.0-862.9.1.el7.x86_64  x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
We setup a small elassandra cluster(3 nodes)
**Problem**: Elassandra does not delete target ES indices until all the indices created for the same table have been deleted(from REST API) in cluster.
**Expected behavior**: Elassandra shall support to delete any ES indices from REST API

**Steps to reproduce**:
 1. create table mytest_s.mymaptable in cassandra with cqlsh tool:
<pre>
CREATE KEYSPACE mytest_s WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'DC1': '2'};
CREATE TABLE mytest_s.mymaptable (
    starttime timestamp,
    name text,
    PRIMARY KEY ( starttime ) 
);
</pre>

 2. Insert 1 row with cqlsh tool:
<pre>
INSERT INTO mytest_s.mymaptable ( starttime, name) values (toTimestamp(now()),'Matt');
</pre>

 3.create ES indices:
<pre>
curl -XPUT -H 'Content-Type: application/json'  localhost:9200/tp_20190505 -d '{
  "settings": {
      "keyspace":"mytest_s",
      "index.partition_function":"toDayIndex tp_{0,date,yyyyMMdd} starttime",
      "index.partition_function_class":"org.elassandra.index.MessageFormatPartitionFunction"
  },
  "mappings": {
      "mymaptable" : { "discover" : ".*" }
  }
}'
</pre>
<pre>
curl -XPUT -H 'Content-Type: application/json'  localhost:9200/tp_20190506 -d '{
  "settings": {
      "keyspace":"mytest_s",
      "index.partition_function":"toDayIndex tp_{0,date,yyyyMMdd} starttime",
      "index.partition_function_class":"org.elassandra.index.MessageFormatPartitionFunction"
  },
  "mappings": {
      "mymaptable" : { "discover" : ".*" }
  }
}'
</pre>

4. check the indices status and it shows green in the cluster:
<pre>
**curl localhost:9200/_cat/indices**
green open tp_20190505 X9Anp4q-R2C528HcrROHcw 3 1 2 0 6.2kb 6.2kb
green open tp_20190506 Zr5HCkfCSEmyg_VsAFlqaA 3 1 0 0  624b  624b
</pre>

5. try to delete tp_20190505 and found it only deleted on node1(on which we call the rest API to delete the ES index):
<pre>
[root@node01 ~]# curl -XDELETE http://localhost:9200/tp_20190505
{"acknowledged":true}
[root@node01 ~]# curl localhost:9200/_cat/indices
green open tp_20190506 Zr5HCkfCSEmyg_VsAFlqaA 3 1 0 0 624b 624b
</pre>

the ES index deleted from node1, but it shows **yellow** in node2 and node3:
<pre>
[root@node2~]# curl localhost:9200/_cat/indices
yellow open tp_20190505 X9Anp4q-R2C528HcrROHcw 1 0 2 0  6kb  6kb
green  open tp_20190506 Zr5HCkfCSEmyg_VsAFlqaA 1 0 0 0 624b 624b
</pre>
<pre>
[root@node03 ~]# curl localhost:9200/_cat/indices
yellow open tp_20190505 X9Anp4q-R2C528HcrROHcw 1 0 2 0  6kb  6kb
green  open tp_20190506 Zr5HCkfCSEmyg_VsAFlqaA 1 0 0 0 624b 624b
</pre>

**Please let me know if any more info needed.**

**Comment by figo-yu** [comment]
@vroyer this function works at 5.5 version.

**Comment by vroyer** [comment]
This issue has been reproduced and fixed, it will be included in the next release planned for  the next week. Thanks for reporting this issue.

**Comment by figo-yu** [comment]
> This issue has been reproduced and fixed, it will be included in the next release planned for the next week. Thanks for reporting this issue.

Thanks Vroyer. Since this is basic function to purge data, good to see the patch ASAP.
