### ISSUE TITLE
When creating mapping, the discovered column types cannot be overriden

### ISSUE THREAD

**Issue by sajja** [strapdata/elassandra#289]
**Elassandra version**: 6.2.3.12

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_181

**OS version** (`uname -a` if on a Unix-like system): Linux xxxxx 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**When creating mapping, the discovered column types cannot be overriden**:

**Steps to reproduce**:

**Cassandra keyspace creation**
```
CREATE KEYSPACE customer WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '1'}  AND durable_writes = true;
```

**Cassandra table creation**
```
CREATE TABLE customer.cdata (
    "id" text PRIMARY KEY,
    name text
)
```

**Create ES index**
```
curl -X PUT "localhost:9200/customer"
```
**Create mapping **
```
curl -XPUT -H 'Content-Type: application/json' "http://localhost:9200/customer/_mapping/cdata" -d '{
    "cdata" : {
        "discover" : "n.*",
        "properties" : {
            "name" : {
                "type" : "text",
                "cql_collection": "singleton"
            }
        }
    }
}'
```

Inspect the index
```
curl  "localhost:9200/customer"
```

Expected: column name should be created with ES type text
```
{"name":{"type":"text","cql_collection":"singleton"}}
```

Actual: Its created as keywords
```
{"name":{"type":"keyword","cql_collection":"singleton"}}
```

Notes: 
According to the elassandra documentation 
https://elassandra.readthedocs.io/en/latest/mapping.html
Discover should discover casssandra column names and those could be overwritten in the properties section. However I don't see that behaviour . Am I doing something wrong.

**Comment by vroyer** [comment]
Yes, your discover regexp should exclude fields with explicit mapping.
In your case, use "^((?!name)n.*)"

**Comment by sajja** [comment]
Thanks. I did not realize regex need to exclude the explicit mapping fields. Documentation was not clear on that.
