### ISSUE TITLE
Unable to set cluster.default_replication or es.replication

### ISSUE THREAD

**Issue by mimarpe** [strapdata/elassandra#290]
**Describe the feature**:
We are trying to setup a multi-DC elassandra cluster and we would like to have all the keyspaces (which are created dynamically) created with a NetworkTopologyStrategy like 'DC1:1,DC2:1,DC3:1'. Following the [docs](https://elassandra.readthedocs.io/en/latest/configuration.html#elassandra-settings), we tried setting in elassandra.yaml:
`cluster.default_replication: "DC1:1,DC2:1,DC3:1"`
We also tried:
`es.replication: "DC1:1,DC2:1,DC3:1"`

That results at startup in:
```
java.lang.IllegalArgumentException: unknown setting [cluster.default_replication] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:346)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:310)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:284)
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:134)
        at org.elasticsearch.node.Node.<init>(Node.java:335)
        at org.elasticsearch.node.Node.<init>(Node.java:246)
        at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:181)
        at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:548)
```
We also tried going through the API, in case that worked better, but the result is similar:

`curl -XPUT -H "Content-Type: application/json" "host:9200/settings" -d'{ "persistent":{ "cluster.default_replication":"GV2:1,NHP:1,VDC:1" } }'`

and:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"persistent setting [cluster.default_replication], not recognized"}],"type":"illegal_argument_exception","reason":"persistent setting [cluster.default_replication], not recognized"},"status":400}`

- How are we supposed to configure multi-DC data distribution and apply the same Strategy to all keyspaces from the start?
- Is there another recommended way to do this? 
- Should we be aware of racks?

**Elassandra version**: elassandra-6.2.3.13

**OS version** (`uname -a` if on a Unix-like system): RHEL 7.5

Thanks!

**Comment by vroyer** [comment]
Hi,
This settings can only be used at index level, in your index settings.
An example is available in [this blog](https://medium.com/@vroyer/kubernetes-logs-analysis-with-elassandra-fluent-bit-and-kibana-4f827854e5c8).

**Comment by mimarpe** [comment]
Hi, 
thanks for your answer. So if I understand, I cannot apply a general config in elassandra.yaml but through the API, since I get:

```
Found index level settings on node level configuration.

Since elasticsearch 5.x index level settings can NOT be set on the nodes
configuration like the elasticsearch.yaml, in system properties or command line
arguments.In order to upgrade all indices the settings must be updated via the
/${index}/_settings API. Unless all settings are dynamic all indices must be closed
in order to apply the upgradeIndices created in the future should use index templates
to set default values.

Please ensure all required values are updated on all indices by executing:

curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.replication" : "GV2:1,NHP:1,VDC:1"
}'
```

This API call will make that all new keyspaces have this replication in the future as well? Sorry needed to clarify it.

```
curl -XPUT -H "Content-Type: application/json" "elassandra__01:9200/_all/_settings?preserve_existing=true" -d '{"index.replication" : "DC1:1,DC2:1,DC3:1"}'
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_all"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_all"},"status":404}
```

It seems _all is not a placeholder for really all keyspaces. Do I have it one by one? Every time they are created..?

Thanks again.

**Comment by mimarpe** [comment]
I found out that actually the framework will create the keyspaces directly with the right strategy.
Thanks for the help, if anyway there is a way to set a default strategy for everything that gets created I'd like to know.
Best,
    Miguel
