### ISSUE TITLE
Issue in pushing templates in 3 node cluster of Elassandra 6.2.3.15

### ISSUE THREAD

**Issue by ackarande** [strapdata/elassandra#294]
Hi,

We are facing issues in pushing templates in 3 node cluster of Elassandra 6.2.3.15

Steps are as below:
1. Install Elassandra version: 6.2.3.15
2. Install Strapdata plugin - strapdata-enterprise-6.2.3.15
3. Do above to prepare 3 node cluster

Try pushing new templates for each node.(Sample which I have used in below)

Its observed that the response comes successful at client side {"acknowledged":true}

But, templates are not created. I dont see any error in log, but a **WARN** - maybe relevant
**CassandraDiscovery.java:1037 publishAsParticipator Ignore and acknowledge obsolete update metadata=230de8fe-fe68-416d-90e4-f48e334a5635/1**

Could you please check this on priority?

Template:

    "index_patterns": ["my_test_pattern"],
    "version": 1,
    "settings": {
        "replication": "DC1:2",
        "drop_on_delete_index": true,
        "index.codec": "best_compression",
        "number_of_shards": 1,
        "index.mapping.ignore_malformed": true
    },
    "aliases": {},
    "mappings": {
        "doc": {
            "_source": {"enabled": true},
            "properties": {
                "tenant": {
                    "type": "text",
                    "analyzer": "keyword"
                }
            }
        }
    }
}
'

**Comment by ackarande** [comment]
Just to add, nodetool status was **UN** and cluster is fine.

**Comment by vroyer** [comment]
I tried to reproduce your issue, but it work properly with both 6.2.3.11 and 6.2.3.16-SNAPSHOT (the next release currently under development. According to the WARN message  you get, your coordinator node has cluster state metadata verison = 1 (see your Elasticsearch cluster state, metadata.version), which is lower than the cluster state metadata version on other nodes (the participant node ignoring the cluster state metadata update).

So you can have a schema synchronization issue => **nodetool describecluster** to check that the 3 nodes runs the same cassandra schema.

You can also have a node restarting with non-empty data, having an old schema loaded, with a cluster state metadata.version > 1. Check that all nodes have the same X2 field in the gossip state:
**nodetool gossipinfo**

The X2 = <host_id>/<metadata.version> where host_id is the id of the last node having updated the ES cluster state, and metadata.version is the ES cluster state metadata.version.

Thanks.
