### ISSUE TITLE
Trigger on ES 

### ISSUE THREAD

**Issue by writeaditya** [strapdata/elassandra#297]
Hi,

I'am using Elassandra to sync between Cassandra and ES. 

Now my issue is that I want to create a trigger on ES whenever a new row is inserted in ES, I need to insert same copy of that row in another table of ES with addition of one column value that I'll provide. Like I'll explain you with an example.

ES row - id,date,c1,c2,etc.

Now I have a list of users that can access the specific ID data and single user can access multiple ID and like single ID can be accessed by multiple users. Now, as soon as the new ID comes in ES, trigger should pick the row and based on its mapping like which user can access that Particular ID, the entire row data should be send in new table with the stamping of user_id.

So, moral of this is to find how can we achieve this using triggers in ES.

Can suggestions please

**Comment by vroyer** [comment]
Use a cassandra trigger.

**Comment by erangaeb** [comment]
I wrote about publishing events to kafka via cassandra triggers, I have used elassandra as the storage. It will be helpful to get some idea. 

https://medium.com/rahasak/publish-events-from-cassandra-to-kafka-via-cassandra-triggers-59818dcf7eed
