### ISSUE TITLE
build_hash and build_date as Unknown after Installing ELS

### ISSUE THREAD

**Issue by ackarande** [strapdata/elassandra#298]
Hi,
Post installation of elassandra i see output of curl -X GET http://localhost:9200/ having 
build_hash and build_date as Unknown

Could you please fix the same?

Thanks
Ashish

**Comment by vroyer** [comment]
Yes, this issue was introduced in 6.2.3.11 and will be fixed in next release 6.2.3.17.
The build date and hash are currently available in **lib/elasticsearch-<version>.jar:META-INF/MANIFEST.MF**, fields **Build-Date** and **Change**.

**Comment by vroyer** [comment]
Fixed with 6.2.3.17
