### ISSUE TITLE
Delete / document reappears when searching issue

### ISSUE THREAD

**Issue by cristigodri** [strapdata/elassandra#299]
Hello,

Our issue is as follows:

We are trying to delete a single document. It should be ok according to the response of the request:

Request:
```
curl -XDELETE 'https://our_url_here/our_index_here/_doc/d83bf9d0-99b0-11e9-8d94-fdd299fdd95f'
```

Response:
```
{"_index":"our_index_here","_type":"_doc","_id":"d83bf9d0-99b0-11e9-8d94-fdd299fdd95f","_version":1,"result":"deleted","_shards":{"total":1,"successful":1,"failed":0}}
```

It would appear to also work when searching (the document is no longer included in search results), but after a few seconds it's being included again:

Immediate response (document no longer shows up):

```
curl -XGET 'https://our_url_here/our_index_here/_search?pretty=true'
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "our_index_here",
        "_type" : "_doc",
        "_id" : "3c3dc610-99a5-11e9-84f8-f3f4655d3ad9",
        "_score" : 1.0        
      }
    ]
  }
}
```

After searching a few seconds later (you can see that the document with the deleted id starts showing up again):

```
curl -XGET 'https://our_url_here/our_index_here/_search?pretty=true'
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "our_index_here",
        "_type" : "_doc",
        "_id" : "3c3dc610-99a5-11e9-84f8-f3f4655d3ad9",
        "_score" : 1.0,        
      },
      {
        "_index" : "our_index_here",
        "_type" : "_doc",
        "_id" : "d83bf9d0-99b0-11e9-8d94-fdd299fdd95f",
        "_score" : 1.0        
      }
    ]
  }
}
```

What could be causing this issue ? I know that documents are not deleted on the spot (only marked for delete) but should they not be excluded from search results ?

We are using version 6.2.3.16.

Looking forward to your answer.

Thanks.

**Comment by vroyer** [comment]
Hi,
If you have multiple nodes, with a replication factor > 1, if a tombestone is not properly replicated, you might get this result from a node where the data is not yet deleted. You should enable TRACE for org.elassandra.index, and check the logs/system.logs on your nodes.
Thanks.

**Comment by cristigodri** [comment]
Hello,

Thanks for answering.

We only have one node though. Could this be a sync issue between cassandra and elasticsearch ?

**Comment by cristigodri** [comment]
After enabling TRACE level logging, we found some info that will help us solve this issue.

Thank you for your time.
