### ISSUE TITLE
Simply Documentation improvement

### ISSUE THREAD

**Issue by brenthale** [strapdata/elassandra#300]
In the README.md file under the section titled "Installation".

Immediately after the text "Then look-up in Cassandra:" it suggests using this command:

`bin/cqlsh -c "SELECT * from twitter.\"_doc\""`

The "-c" is wrong and should be "-e".   At least on my Mac it should be.  The script controls this and there is no "-c" option.  I get the following if I try to use it as written:

```
~/elassandra/elassandra-6.2.3.17$ bin/cqlsh -c "SELECT * from twitter.\"_doc\""
Usage: cqlsh.py [options] [host [port]]

cqlsh.py: error: no such option: -c

```

**Comment by brenthale** [comment]
Do I have other problems going on as well?

Other problem while trying to go through Installation docs:

- It creates a C* table called "_doc".   The name actually includes the 2 quote marks.  Like this:
```
cqlsh:twitter> desc tables

"_doc"
```
I don't think you really want a table name with quotes in the name.  

- I try to perform the "INSERT INTO" command as written and it causes problems as well.  It complains about types being different:  (ignore the fact that I changed my table name to 'testtable' without quotes)
```
cqlsh> INSERT INTO twitter.testtable ("_id", user, post_date, message)
   ... VALUES ( '2', ['Jimmy'], [dateof(now())], ['New data is indexed automatically']);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid list literal for post_date: value dateof(now()) is not of type text"
```

It would be helpful for newbies to have these docs a bit more polished.

Or is my copy/paste adding things it shouldn't be?

**Comment by vroyer** [comment]
* Yes, cqlsh option should be -e to execute a CQL statement.
* "_doc" is the default elasticsearch document type in version 6.x.
* The data format is not ISO in the example, so elasticsearch does not recognize a date but a text field. Then the CQL insert mismatch the inferred column type.

Thanks very much for reporting the issue, this is now fixed.

**Comment by brenthale** [comment]
Perhaps a change to this line might be helpful then:

`Behind the scenes, Elassandra has created a new Keyspace twitter and table _doc.`

to

`Behind the scenes, Elassandra has created a new Keyspace twitter and table "_doc".`

So that it shows that the name of the table is "_doc" (with the quotes in the name).   That still seems really bad practice to have quotes in a table name.  You mention above that that is a `document type`.   We're really talking about the name of the created table not a `document type`.

Sorry still learning.
