### ISSUE TITLE
Remove cassandra column with zero down time

### ISSUE THREAD

**Issue by pramodShehan5** [strapdata/elassandra#302]
I need to remove an existing column in zero downtime. 

I think there is no possibility to remove column in zero downtime. We can remove mapping from elasticsearch but we can not use "ALTER TABLE **table_name** DROP **column**" because that column has dependent on secondary index.

Is there any way to do it?

**Comment by vroyer** [comment]
Hi,

1.You should create another ES index without the column you want to remove, see http://doc.elassandra.io/en/latest/mapping.html#mapping-change-with-zero-downtime <http://doc.elassandra.io/en/latest/mapping.html#mapping-change-with-zero-downtime>
2.switch your application from the old to the new index with an index alias.
3.remove the old ES index.
4.drop the CQL column.

The ElasticSecondaryIndex ignores columns not referenced in its mapping.
- Vincent

**Comment by pramodShehan5** [comment]
Hi,

but we must reindex all the existing data by using nodetool rebuild_index.  it must do before deleting old index. when we did it, still there has dependent on secondary indexes(elastic_testtable_idx).

**Comment by vroyer** [comment]
What is your Elassandra version ?
What is the error message you get when you drop the colomn after removing the old index ?
Thanks.

**Comment by pramodShehan5** [comment]
elassandra version is 6.2.3.11. 

This is the exception.
**InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot drop column tel because it has dependent secondary indexes (elastic_teststable_idx)"**


Thanks

**Comment by vroyer** [comment]
Yes, a reference remains into memory to the unindexed column.
Restarting the node after you remove the old index remove this reference.

So the workaround is:
1.You should create another ES index without the column you want to remove, see http://doc.elassandra.io/en/latest/mapping.html#mapping-change-with-zero-downtime 
2.switch your application from the old to the new index with an index alias.
3.remove the old ES index.
**4.rolling restart nodes where the old index was available.**
5.drop the CQL column.

I keep the point to improve that in future releases.
Thanks.

**Comment by vroyer** [comment]
This is now fixed in release 6.2.3.19.
Thanks for reporting the issue.
