### ISSUE TITLE
source collumns not returned without discover mapping

### ISSUE THREAD

**Issue by measwel** [strapdata/elassandra#303]
Good day,

I currently have the following mapping:

    discover: "^((?!name|description).*)",
    properties: {
      "name": {
        "type": "text",
        "cql_collection": "singleton",
        "analyzer": "standard"
      },
      "description": {
        "type": "text",
        "cql_collection": "singleton",
        "analyzer": "standard"
      }

The table contains many more collumns, which are returned according to my _source setting. 
However, when I remove the auto discovery parameter from the mapping and only leave the explicit mapping, then the not mapped source collumns are not returned by elastic.

Is this the expected behaviour, or a bug? I thought that using only the explicit mapping would be better, as it would keep the index small. Do I have to index all the collumns that I want returned in the result set, even if I do not perform searches on them?

**Comment by vroyer** [comment]
The elasticsearch API only returns known fields describe in the mapping. If you want to see non-indexed column in *_source*, just add explicit a mapping for this column with "index":"false". 

Alternatively, you can query Elasticsearch through CQL, and get any columns from the underlying cassandra table for rows matching your query. See [Search request through CQL](http://doc.elassandra.io/en/latest/search_over_cql.html#search-request-through-cql) for more information.
