### ISSUE TITLE
Racing condition when reading records soon after a delete

### ISSUE THREAD

**Issue by measwel** [strapdata/elassandra#304]
When a record is deleted and immediately afterwards one performs a read query that would include the deleted record, then a racing condition arrises. The read operation is performed after the record has been deleted from cassandra, but before the elastic index reflects the changes. The index finds the record but is then unable to rebuild the _source from the underlying cassandra table as the original record is not there any more. The following error is raised:

unable to fetch fields from _source field: _source is disabled in the mappings for index

If one waits a bit before performing the read query, then the error does not appear anymore.

**Comment by vroyer** [comment]
Yes, this because elasticsearch makes changes visible for search after a refresh occurs. By default, refresh are every seconds. So, your deleted document is visible for search until the refresh occurs. 

You should perform an elasticsearch refresh right after the delete, or just before search. If you don’t have too much load, you can also enable the synchronous_refresh index setting, so refresh will be synchronous on every write/delete operation.

**Comment by measwel** [comment]
Thank you. I access elassandra on node and have access to a node esClient for given index. How would I perform the refresh operation via the node esClient? 

I imagine the refresh operation is asynchronous. How do I wait for the operation to finish, before executing a search? Searches can come in at any time, so I think I will have to run a refresh and wait for it to finish before starting any new search.

**Comment by measwel** [comment]
I found out by experiment, that the index does not block searches automatically when a refresh operation is running on it. So the solution would seem to be:

Delete the document from elastic first with 'wait_for refresh' option. When this call returns, delete the record from the underlying cassandra table.

In this approach, I won't have to trigger manual refresh and just use the standard refresh interval. 

UPDATE:
I managed to delete the document from ES with the node client. However, I think I have found a bug in Elassandra.

1. When deleting the document from ES, the document is also deleted from the underlying cassandra table. My idea was to first delete from ES then manually delete from cassandra. 

2. When I delete the document with refresh: 'wait_for', then for some reason the racing condition still appears. I suspect this is because Elassandra is immediately deleting the record from the underlying table as soon as it is deleted from the index. This means that searches can still find the es record (before the automatic refresh happens), while the underlying record is gone. 

My strategy to delete from ES first, only works when I force an inmediate refresh (which can lead to inefficient indexing).

I think the default delete behaviour in Elassandra (when deleting a record either from cassandra or from the index)  should be:

1. First delete the related document from ES with refresh 'wait_for'. Only when this call returns, delete the underlying record from cassandra. 

OR 

2. First delete the related document from ES with refresh 'true'. Only when this call returns, delete the underlying record from cassandra. 

This would guarantee that the user never finds an ES document without the underlying cassandra record. I think it should be settable in the driver which delete method it should use. If the first option is chosen, then it will result in a better index at the expense of speed; a mean latency of 500ms will be introduced for each single delete operation.

Currently the bug is, that Elassandra will delete the underlying cassandra record, even if the delete request is first made to ES with refresh 'wait_for'. This means that I am forced to set refresh 'true' on all delete calls. This seems to work in my test case, but I am still not sure that even an immediate refresh will prevent the racing condition as it is not known to me whether the refresh will always finish before Elassandra actually deletes the underlying record and before another search request is performed.

In my opinion Elassandra should never allow an ES document to be findable without the underlying record. It should then be up to the developer to chose the appropriate index refresh strategy at record deletion.

**Comment by vroyer** [comment]
As said in my first response, you can get the expected behaviour with the index setting synchronous_refresh=true, but it comes with a cost for all updates. 

Currently, it is not possible to trigger a refresh for a specific  insert/delete operation because it would require to transport this information in the CQL request to the replica node (the synchronous_refresh=true/false is global setting for all write operations). This could be implemented by using a custom payload (see https://docs.datastax.com/en/developer/java-driver/3.2/manual/custom_payloads/) and manage that with a CQL handler,  but it's  probably 2 weeks of work....

**Comment by measwel** [comment]
I am currently deleting records this way:

`          const deleteoptions = {
            id: found_entity.uuid.toString(),
            index: index_name,
            type: type_name,
            refresh: 'true' // force immediate refresh so the record cannot be found in ES
          };

          esClient.delete(deleteoptions, (err, result) => { ... });`

Thanks to the immediate refresh, this approach seems to work. However, I am currently using only 1 elassandra node. Are you suggesting that deleting from the index with the immediate refresh option could still fail when running in distributed mode? I do not see how.

I also do not understand your remark about the global synchronous_refresh setting.

**Comment by vroyer** [comment]
Closing inactive ticket
