### ISSUE TITLE
Doing count(*) from elassandra table with CQL

### ISSUE THREAD

**Issue by KevinDomco94** [strapdata/elassandra#307]
Can I do in Elassandra count(*) without using a count API?

**Comment by vroyer** [comment]
No, currently you need to execute an Elasticsearch count query.
You can also get the total_hit of an elasticsearch query over CQL, see file:///Users/vroyer/git/strapdata/elassandra/docs/elassandra/build/html/search_over_cql.html#cql-driver-integration <file:///Users/vroyer/git/strapdata/elassandra/docs/elassandra/build/html/search_over_cql.html#cql-driver-integration>
but total_hits is less accurate than count, see https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-track-total-hits.html <https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-track-total-hits.html>
