### ISSUE TITLE
EOL for Elasticsearch 6.2.x

### ISSUE THREAD

**Issue by ackarande** [strapdata/elassandra#308]
Hi,

According to EOL dates of Elasticsearch - Elasticsearch 6.2.x is already passed the EOL 

https://www.elastic.co/support/eol

Could you please let us know if there are plans for upgrade? and if yes then by when?

Thanks

**Comment by vroyer** [comment]
Elassandra is currently based on ES 6.2.3, and this is the version supported by Strapdata.
A dev cycle with ES 6.8.3 + Cassandra 3.11.4 is ongoing.

**Comment by leoandrea7** [comment]
> Elassandra is currently based on ES 6.2.3, and this is the version supported by Strapdata.
> A dev cycle with ES 6.8.3 + Cassandra 3.11.4 is ongoing.

Hi,
when will the new version of elassandra be released?
Thanks

**Comment by vroyer** [comment]
Elassandra 6.8.4.0 = Cassandra 3.11.5 + Elasticsearch 6.8.4 is released !

**Comment by steebchen** [comment]
Awesome, thanks @vroyer!
