### ISSUE TITLE
Collections with one element are returned as a single element

### ISSUE THREAD

**Issue by silviucpp** [strapdata/elassandra#309]
**Elassandra version**: elassandra 6.2.3.17-1

**Plugins installed**: []

**JVM version** (`java -version`):
penjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):CentOS Linux release 7.6.1810 

**Description of the problem including expected versus actual behavior**:

I have a cassandra table as follow:

```
CREATE TABLE accounts(uuid timeuuid, name text, created_at timestamp, permissions set<smallint>, PRIMARY KEY(uuid))"
```

And an index on that table (autodiscover the metadata) where permissions is discovered (correctly) as :

```
"permissions": {
"index": false,
"type": "short",
"cql_collection": "set"
},
```
When I query the data via ELASTIC SEARCH API in case the row has 1 element in the `permissions` set is returned as a single element. In case there are multiple elements is returned as a list.

Example: for `permissions` = with `[1]` I receive `1`
 
This is not consistent at all

Silviu

**Comment by vroyer** [comment]
Elasticsearch store the original _source JSON document, and you get the result as you stored it.
But in Elassandra, _source is rebuilt from the cassandra layer, to avoid double data storage.

As you suggest, we could add brackets when cql_collection is set or list, but if someone stores "permissions: 1", he will get _source with "permissions: [ 1 ]", which is not consistent with the elasticsearch behaviour too.

So, there is no way to be consistent in all cases !

**Comment by silviucpp** [comment]
@vroyer I was thinking to be consistent between querying the data from cqerl and Elasticsearch. Through cqerl you always get `[1]` for one single element.

**Comment by vroyer** [comment]
Ok, i understand.
FYI, you should be able to query Elasticsearch through CQL with cqerl, and returned columns will be properly typed, with `X`, `set<X>` or `list<X>`, where X is a native type.
See [Search request through CQL](http://doc.elassandra.io/en/latest/search_over_cql.html#search-request-through-cql) for details.
