### ISSUE TITLE
Docker Swarm Elassandra cluster

### ISSUE THREAD

**Issue by weworksonam** [strapdata/elassandra#310]
Is there an example on how to build a Elassandra cluster for use on on a Docker Swarm cluster?  I see a helm chart for Kubernetes and is mentioned in the documentation as well but didn't see much for docker swarm.

**Comment by vroyer** [comment]
No sorry, we don’t have a deployment guide on swarm, mainly becauses warm does not provide something equivalent to k8s statefulset.
Thanks.

**Comment by weworksonam** [comment]
I want to create a Elassandra cluster manually within one datacenter.  I saw some mentions of it some time ago but can't find it anymore.  Can you point me to where I can find it?  It would be of much help.
Let's say I ran my first elassandra container:

docker run --name my-elassandra strapdata/elassandra

If I run another docker container of elassandra how does it join the previous as a cluster?  I guess I am not able to find that info.

thank you

**Comment by vroyer** [comment]
Please see [quick start guide](https://elassandra.readthedocs.io/en/latest/quickstart.html) using docker-compose.
