### ISSUE TITLE
Elassandra doesn't work with Istio

### ISSUE THREAD

**Issue by steebchen** [strapdata/elassandra#311]
Elassandra doesn't work with Istio, but it's a known issue. The respective issues are https://github.com/istio/istio/issues/14662 and https://github.com/istio/istio/issues/10053 (more specifically., https://github.com/istio/istio/issues/10053#issuecomment-459443812). It would be nice if this could be supported out of the box.

**Comment by vroyer** [comment]
What do you expect from Elassandra to make this work ?

**Comment by vroyer** [comment]
Closing inactive ticket
