### ISSUE TITLE
Nested objects' fields not indexed

### ISSUE THREAD

**Issue by paolodedo** [strapdata/elassandra#315]
Hello,

I have tried to use Elassandra 6.2.3 and 6.8.4 (on Docker Hub) and a critical issue came out:

The steps I made:

1. Created a new index
2. Indexed a document with a field containing a nested object (everything OK for now)
Request
`{
    "fieldA": "A",
    "fieldB": "B",
    "nested": {
        "fieldC": "C",
        "fieldD": "D",
        "fieldE": "E",
        "fieldF": "F"
    }
}`

3. Indexed a second document with this same field containing, in the nested object, some different fields from the first document -> the result is that only a random field is saved, even if under **/_mapping** URL all the fields are displayed correctly.
Request
`{
    "fieldA": "A",
    "fieldB": "B",
    "nested": {
        "fieldG": "G",
        "fieldH": "H",
        "fieldI": "I",
        "fieldJ": "J"
    }
}`

GET output:
`{
    "took": 11,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 2,
        "max_score": 1.0,
        "hits": [
            {
                "_index": "test-issue-index",
                "_type": "test-issue",
                "_id": "B0rWGG8Bx4Fl4m8pOw3Q",
                "_score": 1.0,
                "_source": {
                    "fieldA": "A",
                    "fieldB": "B",
                    "nested": {
                        "fieldF": "F",
                        "fieldC": "C",
                        "fieldE": "E",
                        "fieldD": "D"
                    }
                }
            },
            {
                "_index": "test-issue-index",
                "_type": "test-issue",
                "_id": "CErWGG8Bx4Fl4m8p0A26",
                "_score": 1.0,
                "_source": {
                    "fieldA": "A",
                    "fieldB": "B",
                    "nested": {
                        "fieldJ": "J"
                    }
                }
            }
        ]
    }
}`

Here the /_mapping endpoint request, just to show to you that every field in the nested object is correctly mapped into the index.
`{
    "test-issue-index": {
        "mappings": {
            "test-issue": {
                "properties": {
                    "fieldA": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
                    "fieldB": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
                    "nested": {
                        "properties": {
                            "fieldC": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldD": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldE": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldF": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldG": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldH": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldI": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldJ": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`

**NOTE: These behaviour is NOT reproduced on ElasticSearch (not Elassandra) 6.2.3 or 6.8.4**

Can you help me, please?

Thanks and regards.

Paolo

**Comment by vroyer** [comment]
Sorry, please provide ALL information to fully replay your issue (index ans search requests).
What do you mean with "the result is that only a random field is saved" means ?

**Comment by paolodedo** [comment]
Here you have my curl requests:

**1. Create Index:**

`curl -X PUT localhost:9200/test-issue-index
`

**2. First document inserted:**

```
curl -X POST localhost:9200/test-issue-index/test-issue/ -H 'Content-Type: application/json' -d '{
"fieldA": "A",
"fieldB": "B",
"nested": {
     "fieldC": "C",
     "fieldD": "D",
     "fieldE": "E",
     "fieldF": "F"
   }
}'
```

**3. Second document inserted:**

```
curl -X POST localhost:9200/test-issue-index/test-issue/ -H 'Content-Type: application/json' -d '{
"fieldA": "A",
"fieldB": "B",
"nested": {
    "fieldG": "G",
    "fieldH": "H",
    "fieldI": "I",
    "fieldJ": "J"
  }
}'
```

**4. Search executed on this index for this document type:**

_Request_
`curl localhost:9200/test-issue-index/test-issue/_search`

_Response_
```
{
    "took": 9,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 2,
        "max_score": 1.0,
        "hits": [
            {
                "_index": "test-issue-index",
                "_type": "test-issue",
                "_id": "DUpGGW8Bx4Fl4m8p9A0L",
                "_score": 1.0,
                "_source": {
                    "fieldA": "A",
                    "fieldB": "B",
                    "nested": {
                        "fieldF": "F",
                        "fieldC": "C",
                        "fieldE": "E",
                        "fieldD": "D"
                    }
                }
            },
            {
                "_index": "test-issue-index",
                "_type": "test-issue",
                "_id": "DkpHGW8Bx4Fl4m8pEQ35",
                "_score": 1.0,
                "_source": {
                    "fieldA": "A",
                    "fieldB": "B",
                    "nested": {
                        "fieldH": "H"
                    }
                }
            }
        ]
    }
}

```

**5. Mapping request executed on this index for this document type:**

_Request_
`curl localhost:9200/test-issue-index/test-issue/_mapping
`
_Response_
```
{
    "test-issue-index": {
        "mappings": {
            "test-issue": {
                "properties": {
                    "fieldA": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
                    "fieldB": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
                    "nested": {
                        "properties": {
                            "fieldC": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldD": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldE": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldF": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldG": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldH": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldI": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "fieldJ": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```


As you can see in the search response, the second document's nested object doesn't contain all the fields inserted in the POST request.

**Comment by vroyer** [comment]
Thanks, we have reproduce this issue and fixed it.
This happens when more than one UDT subfield is added in a single mapping update.
A workaround is to create the mapping with all UDT fields before inserting documents, or to add several documents with only one new subfield on each insert.
The fix will be available soon in the next release.
