### ISSUE TITLE
elassandara build from source code 

### ISSUE THREAD

**Issue by saranamsai** [strapdata/elassandra#318]
Hi,

   I am using elassandara source code to build the package from Gradle . 
**Elassandra version**: 6.2.3

**Plugins installed**: []

**JVM version** (`java -version`): 8 ,9

**OS version** (`uname -a` if on a Unix-like system):linuix 4.4.0-1092-aws #103-Ubuntu SMP Tue Aug 27 10:21:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: 13:09:49.819 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 132 more
13:09:49.819 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.reflect.UndeclaredThrowableException
13:09:49.819 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.proxy.$Proxy66.handleOption(Unknown Source)
13:09:49.819 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.handleOption(jdk.compiler@9-internal/ClientCodeWrapper.java:265)

**Steps to reproduce**:

Please include a *minimal* but **complete** **recreation** of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.installed Gradle 4.5 
 2. installed java 8 and 9 set the paths for java
 3. I am using Gradle build command to build the package  the below-attached issue I am
[elassandra issue.docx](https://github.com/strapdata/elassandra/files/4026194/elassandra.issue.docx)
 facing

**Please provide the following information**:

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)
* elasticsearch cluster state (curl http://localhost:9200/_cluster/state)
* cassandra schema (cqlsh>DESC KEYSPACE <your_keyspace>)
* cassandra gossip state (run: nodetool gossipinfo)

**Comment by leleueri** [comment]
Hi,

Did you try to use the grade wrapper script (gradlew) present in the base directory of this repository  ? 

To build elassandra you need to configure the  JAVA_HOME and CASSANDRA_JAVA_HOME environment variables:
* JAVA_HOME must be initialized with the JDK9 home directory
* CASSANDRA_JAVA_HOME must be initialized with the JDK8 home directory

Eric

**Comment by saranamsai** [comment]
yes I follow the same steps you mentioned still am facing the same issue as above 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> java.lang.reflect.UndeclaredThrowableException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by vroyer** [comment]
Sorry, but elassandra has no build issue. Elassandra is automatically built by travis, please see the **.travis.yml** file for env and commands or see build logs at [travis](https://travis-ci.com/strapdata/elassandra/builds/142888537)

If you need consulting services to assist you, please contact Strapdata.
