### ISSUE TITLE
Can elassandra be used as a datasource for Grafana dashboarding?

### ISSUE THREAD

**Issue by imran20487** [strapdata/elassandra#320]
Hi we have cassandra as our database and we plan to use Grafana for our dashboarding purpose, but Grafana does not support Cassandra as a datasource but supports Elastic Search. So, is there a way to use Elassandra as the datasource? Any plugin for Grafana?

**Comment by vroyer** [comment]
Elassandra expose the Elasticsearch API, so Grafana can use the Elasticsearch plugin to query Elassandra.
