### ISSUE TITLE
How to maintain sync between Cassandra and Elastic Search in Elassandra

### ISSUE THREAD

**Issue by rashmip1022174** [strapdata/elassandra#321]
**Sometimes Cassandra and Elastic Search are not in sync.**:

**Elassandra version**:elassandra-6.2.3.17

**Plugins installed**: elasticsearch-sql plugin

**JVM version** (`java -version`):"1.8.0_232"

**OS version** (`uname -a` if on a Unix-like system):x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I have observed that sometimes Cassandra and Elastic Search docs count are out of sync.
How to maintain this sync between them in elassandra.

**Comment by vroyer** [comment]
Please provide an example.
A cassandra secondary index synchronously update Elasticsearch index on each write operation, so it’s always sync, but doc dument are visible for search after a refresh (every second by default)...
