### ISSUE TITLE
Issue in searching data using routing.

### ISSUE THREAD

**Issue by govindakumar** [strapdata/elassandra#324]
I find it hard to build a curl query on a table having partition key including multiple columns. I used below query to create the table in Cassandra.

CREATE TABLE details.customers (country text, state text, city text, id int, name text, gender text, email text, phone text, address text, PRIMARY KEY(country, state, city, id))

And now I want to include partition in my search i.e. some thing like this
GET /books/_search?pretty&routing=xxx
{
“query":{ ... }
} 

I want to build a similar search for my table where I can include country, state and city in routing. Please help in with this info because I found it difficult to extract this info from the documentation.

**Comment by leleueri** [comment]
Hi,

Routing is done using the Cassandra partition key (the first column of the primary key).
If you include this field in your query the request will be redirect in the right replicas.

**Comment by govindakumar** [comment]
> Hi,
> 
> Routing is done using the Cassandra partition key (the first column of the primary key).
> If you include this field in your query the request will be redirect in the right replicas.

Thanks for your response!!
That means if I have created a table with below script
**CREATE TABLE details.customers (country text, state text, city text, id int, name text, gender text, email text, phone text, address text, PRIMARY KEY(country, state, city, id))**

Then I can include country as routing in the query and it will be redirected to the correct replica. Is my understanding correct?

**Comment by vroyer** [comment]
Yes, “country" is your partition key, so query are directed to a replica node hosting this partition.
