### ISSUE TITLE
Upgrade from 6.2.x to 6.8.x "can't add node XXX, found existing node YYY, with same address"

### ISSUE THREAD

**Issue by mrloud** [strapdata/elassandra#326]
What is the proper way to upgrade from Elassandra 6.2.x to 6.8.x?  Just doing a rolling update I get "can't add node XXX, found existing node YYY, with same address" errors from elasticsearch.

**Comment by vroyer** [comment]
A rolling update is not the good way to update elassandra.
You should start a new DC running EL 6.8 using the datacenter.group feature, recreate your indices, test your application and then drop the old DC running EL 6.2.

**Comment by dioptre** [comment]
I found that clearing the node out after the upgrade works for me. You can remove the node with ```nodetool removenode``` after you stop the service from another machine.

BE CAREFUL! :)
```
nodetool status
systemctl stop cassandra.service 
rm -rf /var/lib/cassandra/
mkdir /var/lib/cassandra
chown cassandra:cassandra /var/lib/cassandra
systemctl start cassandra.service
```
