### ISSUE TITLE
Can I determine which columns to be indexed ?

### ISSUE THREAD

**Issue by jasonever** [strapdata/elassandra#328]
Hi,

I'm using `SchemaBuilder` from `Datastax Java Driver`:
https://docs.datastax.com/en/developer/java-driver/4.4/manual/query_builder/schema/

in order to simulate the schema creation from `CQL` instead of `Elastic` , but the problem that it mandates me to assign the columns to be indexed , while in `Elassandra` I see it doesn't require this

The question here , Can I decide which columns to be indexed in Elastic ? instead of all ?
Let's say:

- we have table with columns A, B,C
- A is the primary key
- C is a normal column
- I want to index the A & C (Primary _id & C)
- In case if it's doable , Could you give me `CQL example` ?

**Comment by leleueri** [comment]
Hi,

To create an elastic index on an existing table, you have to request the Elastic API. 
It is possible to select which fields are indexed using the "discover" field.

Some documentation here after : 

- https://elassandra.readthedocs.io/en/v6.8.4.1/operations.html#create-delete-and-rebuild-index
- https://elassandra.readthedocs.io/en/v6.8.4.1/mapping.html#bi-directional-mapping
