### ISSUE TITLE
Problem while creating an index using ES High Level REST Client -> Create Index API ?

### ISSUE THREAD

**Issue by jasonever** [strapdata/elassandra#329]
Hello,
I'm trying to use `Elasticsearch High Level Rest Client` in order to create an index from a keyspace in a table.
This is my try :
```
        CreateIndexRequest request =  new CreateIndexRequest(keyspace);
        XContentBuilder mappingBuilder = XContentFactory.jsonBuilder();
        mappingBuilder.startObject();
        {
            mappingBuilder.startObject("properties");
            {
                mappingBuilder.startObject(table);
                {
                    mappingBuilder.startObject("properties");
                    {
                        mappingBuilder.field("discover", ".*");
                    }
                    mappingBuilder.endObject();
                }
                mappingBuilder.endObject();
            }
            mappingBuilder.endObject();
        }
        mappingBuilder.endObject();
        request.mapping(mappingBuilder);
        client.indices().create(request, COMMON_OPTIONS);
```

However , I'm getting the index `created` , but the `mapping` is empty . it didn't discover the columns as expected similarly to:
`curl -XPUT -H 'Content-Type: application/json' http://localhost:9200/test -d'{"mappings":{"docs":{"discover":".*"}}}'`

So i'm not sure if `Elassandra` **is supporting this Client or not?** , or Have I did something wrong ? (I've tried many formats for the mapping and the same)

----

**Another problem** , Not sure why no `aggregators` are working with me except fews:
```
cqlsh> select version from ip.ipv where es_query='{"aggs":{"version":{"stats":{"field":"version"}}}}';
ServerError: java.lang.IllegalArgumentException: unsupported aggregation type=[stats] name=[version]

cqlsh> select * from ip.ipv where es_query='{"aggs":{"statics":{"extended_stats":{"field":"version"}}}}';
ServerError: java.lang.IllegalArgumentException: unsupported aggregation type=[extended_stats] name=[statics]
```

**Comment by vroyer** [comment]
Hi,

Here is a piece of code that works in a project.
I think you need to attache your mapping to the table name (= document type).

CreateIndexRequest request = new CreateIndexRequest(index);
XContentBuilder builder = XContentFactory.jsonBuilder();
builder.startObject()
            .startObject(table.name())
                .field("discover", “.*")
            .endObject()
        .endObject();
request.mapping(table.name(), builder);
request.settings(Settings.builder()
    .put("keyspace", session.getLoggedKeyspace())
    .put("synchronous_refresh", true)   // for testing only
    .build());
CreateIndexResponse createIndexResponse = client.indices().create(request);
For the second point, use es_options to specify your index name (require ALLOW FILTERING, but this has no effect).
Last point, Elassandra supports “stats” aggregation, but not “extended_stats”.

**Comment by joffredlp** [comment]
Hi, I am also working on this where I use the RestClient version 6.8.6 to create the mapping. 

1) the request.mapping() method has only one parameter which is the Builder parameter. so you can't pass the tablename as the first parameter. 
request.mapping(builder);
Which version of RestClient you are using ?  

2) If i use your builder.startObject()
            .startObject("mytable")
                .field("discover", “.*")
            .endObject()
        .endObject();
I get an error : 
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [mytable : {discover=.*}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [mytable : {discover=.*}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [mytable : {discover=.*}]"}},"status":400}

thanks.

**Comment by vroyer** [comment]
My example works for elassandra version 6.2.3.x and 6.8.4.x using the same rest client version.
