### ISSUE TITLE
elastic search configurations

### ISSUE THREAD

**Issue by doey28** [strapdata/elassandra#33]
I'm a bit confused on where to place elasticsearch config parameters? The docs say "don't touch" elasticsearch.yml but where do you place default/global index parameters such as index.max_result_window?

**Comment by vroyer** [comment]
Hi,
Cluster name, listen addresses, paths are unherited from the cassandra.yml, number of shards is the number of nodes in your elassandra datacenter, but you can still set some default elasticsearch in conf/elasticsearch.yml.
Thanks'
Vincent
