### ISSUE TITLE
Inconsistent cluster state after node restart

### ISSUE THREAD

**Issue by pankajydv** [strapdata/elassandra#331]
**Elassandra version**: elassandra-6.2.3.21

**Plugins installed**: []

**JVM version** (`java -version`): 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux cgrphdb139147 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The` /_cat/indices?v` reports different `docs.count` and `store.size` on the restarted node than rest of the nodes of the cluster.

**Steps to reproduce**:
1. Migrate the existing Cassandra setup to Elassandra as per [the documentation](https://elassandra.readthedocs.io/en/latest/operations.html#data-migration)
2. PUT the mapping file to kickstart the indexing of the existing data.
3. Once the indexing is complete verify that `/_cat/indices?v` reports same number for all the nodes of the cluster.
4. Restart one of the node - the data is drastically reduced on the node just restarted.
5. The problem moves to the node just restarted (the previous one recovers automatically as soon as new one is restarted)
Following is the cluster detail.
`http://172.26.139.146:9200/_cat/nodes?v`
> ip             heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
172.26.139.148           51          99   0    0.01    0.03     0.05 md        -      172.26.139.148
172.26.139.147           71          99   6    0.95    0.95     0.95 md        -      172.26.139.147
172.26.139.146           20          99   0    0.00    0.01     0.05 mdi       *      172.26.139.146
172.26.139.149           53          98   0    0.01    0.02     0.05 md        -      172.26.139.149

After indexing is complete, every node report the same indices numbers
`http://172.26.139.146:9200/_cat/indices?v`
>health status index         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   cmsentitydb_1 11G2lkP_RCyMOD7KMOTuRQ   4   2  261533582            0      7.4gb          7.4gb
green  open   .kibana       Tq9UPCsoQdasvwU4LEausg   4   0          2            0     10.7kb         10.7kb
green  open   cmsentitydb   -JA_NHNgT9aWlZFV2x_89Q   4   2  **972391179**     68855969     **29.9gb**         29.9gb

Now whichever node I restart, startes reporting much lesser number of documents, size etc. If I restart **172.26.139.147**
`http://172.26.139.146:9200/_cat/indices?v` - Full data on **172.26.139.146**
>health status index         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   cmsentitydb_1 11G2lkP_RCyMOD7KMOTuRQ   4   2  261533582            0      7.4gb          7.4gb
green  open   .kibana       Tq9UPCsoQdasvwU4LEausg   4   0          2            0     10.7kb         10.7kb
green  open   cmsentitydb   -JA_NHNgT9aWlZFV2x_89Q   4   2  **972391179**     68855969     **29.9gb**         29.9gb

`http://172.26.139.147:9200/_cat/indices?v` - Lesser records on **172.26.139.147**
>health status index         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   cmsentitydb_1 11G2lkP_RCyMOD7KMOTuRQ   4   2          0            0       208b           208b
green  open   .kibana       Tq9UPCsoQdasvwU4LEausg   4   0          2            0     10.1kb         10.1kb
green  open   cmsentitydb   -JA_NHNgT9aWlZFV2x_89Q   4   2  **258569130**            0      **7.3gb**          7.3gb

If I restart the elassandra node **172.26.139.146**, the problem moves to 172.26.139.146 and 172.26.139.147 starts reporting correct data.
`http://172.26.139.146:9200/_cat/indices?v` - Lesser records on **172.26.139.146**
>health status index         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   cmsentitydb_1 11G2lkP_RCyMOD7KMOTuRQ   4   2  261533582            0      7.4gb          7.4gb
green  open   .kibana       Tq9UPCsoQdasvwU4LEausg   4   0          0            0       208b           208b
green  open   cmsentitydb   -JA_NHNgT9aWlZFV2x_89Q   4   2  **261533582**     68855969      **9.4gb**          9.4gb

`http://172.26.139.147:9200/_cat/indices?v` - Full data on **172.26.139.147**
>health status index         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   cmsentitydb_1 11G2lkP_RCyMOD7KMOTuRQ   4   2  261533582            0      7.4gb          7.4gb
green  open   .kibana       Tq9UPCsoQdasvwU4LEausg   4   0          2            0     10.7kb         10.7kb
green  open   cmsentitydb   -JA_NHNgT9aWlZFV2x_89Q   4   2  **972391179**     68855969     **29.9gb**         29.9gb

Please include a *minimal* but **complete** **recreation** of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Please provide the following information**:

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)
[172.26.139.149-system.log](https://github.com/strapdata/elassandra/files/4226478/172.26.139.149-system.log)
[172.26.139.148-system.log](https://github.com/strapdata/elassandra/files/4226479/172.26.139.148-system.log)
[172.26.139.147-system.log](https://github.com/strapdata/elassandra/files/4226481/172.26.139.147-system.log)
[172.26.139.146-system.log](https://github.com/strapdata/elassandra/files/4226484/172.26.139.146-system.log)
* elasticsearch cluster state (curl http://localhost:9200/_cluster/state)
[cluster-state.txt](https://github.com/strapdata/elassandra/files/4226477/cluster-state.txt)
* cassandra schema (cqlsh>DESC KEYSPACE <your_keyspace>)
[desc_keypace.txt](https://github.com/strapdata/elassandra/files/4226475/desc_keypace.txt)
* cassandra gossip state (run: nodetool gossipinfo)
[gossip_info.txt](https://github.com/strapdata/elassandra/files/4226474/gossip_info.txt)

**Comment by leleueri** [comment]
Hi,

According to your post, you are using the version 6.2.3.21 of Elassandra.
Could you please try with the last Elassandra 6.2.3 release (6.2.3.25) ?

There are some improvements since the release 6.2.3.21 that may solve your issue.

Regards,
Eric

**Comment by denmark-admin** [comment]
Thanks, @leleueri Upgrade to latest version i.e. 6.8.4.3 has resolved the issue.

**Comment by pankajydv** [comment]
Thanks, @leleueri Upgrade to latest version i.e. 6.8.4.3 has resolved the issue.
