### ISSUE TITLE
Can't query when es index name different from cassandra keyspace name

### ISSUE THREAD

**Issue by tlthiem** [strapdata/elassandra#333]
Hello, I am currently trying to move my cassandra 3.11 cluster to elassandra v6.8.4 

However, due to elasticsearch retiring _types in 6.x releases, I figured I have to create lots of Indices per Keyspace. I am also planning to use the ["Search request through CQL"](https://elassandra.readthedocs.io/en/v6.8.4.3/search_over_cql.html#search-request-through-cql) feature extensively.

I have not yet figured out how to create indices that point to a keyspace with a different name.
The only documentation I've found, regarding this issue, is not working for me:

`cassandra@cqlsh> SELECT "_id",foo FROM twitter.tweet WHERE es_query='{"query":{"query_string":{"query":"bar2*"}}}' AND es_options='indices=twitter*' ALLOW FILTERING;`

If I create the following Index everything works as expected. Because `my_keyspace` is my cassandra keyspace name. If I change that to something else I cant query anything even though the Index exists and I do not get an error.
```
curl -X PUT \
  http://localhost:9200/my_keyspace \
  -H 'content-type: application/json' \
  -d '{
    "mappings": {
    	  "users": {
        "properties": {
          "anon": { "type": "keyword", "cql_collection": "singleton" },
          "banned": { "type": "boolean", "cql_collection": "singleton" },
          "birthday": { "type": "date", "cql_collection": "singleton" },
          "userid": {
            "type": "keyword",
            "cql_collection": "singleton",
            "cql_partition_key": true,
            "cql_primary_key_order": 0
          }
        }
    	  }
    }
  
}
```

My question is, how can I create indices for multiple existing cassandra tables that share the same keyspace and query them using es-queries through CQL.

**Also a more general question is, using aboves code snippet: can the `ALLOW FILTERING` have a performance impact on the query or is it just to satisfy CQL 3 syntax?**

Thank you guys for this project and any help. I'm excited.

**Comment by vroyer** [comment]
By default, keyspace = index name, but you can alter this by using the “keyspace” setting in your index settings.
Thus, you can have many indices using the same keyspace, with index type = table name

The ALLOW FILTERING is just a mandatory trick because cassandra cannot search on multiple indexed columns.
With the elassandra CQL handler, the elasticsearch query is directed to the Elasticsearch API, and the coordinator node does not filter anything, this is just a syntaxe trick !

**Comment by tlthiem** [comment]
@vroyer Thank You very much for your answer. I get it now.
