### ISSUE TITLE
the elastic search inner hits problem

### ISSUE THREAD

**Issue by thomas81528262** [strapdata/elassandra#337]
6.8.3 seem have some problem with inner_hits query.

It always return the wrong inner_hits.
But I try 6.2.3 get the correct result.

Here is the schema

body: {
        properties: {
          mac: { type: "keyword" },
          data: {
            type: "nested",
            include_in_parent: true,
            properties: {
              name: { type: "keyword" },
              value: { type: "keyword", "ignore_above": 10000 },
              nameid: { type: "keyword", "index": false }
            }
          }
        }
      }

insert data

 body: {
        data: [
          { name: "CPU", value: "intel V1" },
          { name: "MEM", value: "samsung" },
          {name:"HDD", value:'WD'}
        ],
        mac: "301422"
      }​

Here is the query.

 body: {
        _source: false,
        query: {
          nested: {
            path: "data",
            query: {
              term: {
                "data.value": "WD",
              },
            },
            inner_hits: {
              highlight: {
                fields: {
                  "daata.value": {},
                },
              },
            },
          },
        },
      },​

6.8.3 will alwasy get the 
 { name: "CPU", value: "intel V1" },

but 6.2.3 wiil get the 
    {name:"HDD", value:'WD'}

**Comment by vroyer** [comment]
Similar issue has been fixed in release 6.8.4.6, please check it fixes your issue.
Thanks.

**Comment by thomas81528262** [comment]
The problem already solve in 6.8.4.6

Thanks,
