### ISSUE TITLE
Alter Type From Cassandra to Elasticsearch SYNC

### ISSUE THREAD

**Issue by pramodShehan** [strapdata/elassandra#338]
Hi,

I have defined UDT and used a set of that UDT in my table.

**CREATE TYPE contact (
        name TEXT,
        phone TEXT,
        email TEXT,
      );

CREATE TABLE employees (
        id timeuuid,
        contacts SET<frozen <contact>>,
        PRIMARY KEY( id));**

after that I added new filed to the UDT contact.

ALTER TYPE contact ADD web TEXT;

The question is how am I be able to sync the changes of the table from cassandra to elasticsearch?

**Comment by vroyer** [comment]
You need to do a mapping discover to see added fields (or you can manually update the elasticsearch mapping).
See https://elassandra.readthedocs.io/en/latest/mapping.html#bi-directional-mapping <https://elassandra.readthedocs.io/en/latest/mapping.html#bi-directional-mapping>

**Comment by pramodShehan5** [comment]
Hi,

Here I used below elasticsearch API. But it was not mapped with new web field. 
I added also some data after executing es api.

   curl -XPUT "http://172.17.0.3:9200/employees /_mapping/employees "
    "employees" : {
        "discover" : "web"
    }
}'

Thank you

**Comment by pramodShehan5** [comment]
Hi again,

But after I used below api, it is created a mapping for mime_code

curl -XPUT "http://172.17.0.3:9200/employees /_mapping/employees "
"employees" : {
"discover" : "contact"
}
}'

Thank you
