### ISSUE TITLE
unable run elassandra on windows.

### ISSUE THREAD

**Issue by usmanq8** [strapdata/elassandra#339]
so far i downloaded TAR of elassandra 6.8.4.3 and able to run on dockers.
But same source is not getting run on Windows?
How is it possible to run it.

**Comment by tlthiem** [comment]
I don't think native windows is a supported platform.

**Comment by vroyer** [comment]
Yes, windows is not supported, but you can run it in docker on window.  See the elassandra quickstart on docker.
