### ISSUE TITLE
Elassandra not able to access elastic search url

### ISSUE THREAD

**Issue by sumitchoudhary92** [strapdata/elassandra#343]
Hi, I am new to Elassandra. I want to make setup(windows 10) and hit queries from elastic search url in stored documents. I have installed Elassandra and start it is working fine but i am not able to access elastic search url. I also tried to configure host and http.port in elasticsearch.yml but it did not work.

I doubt i need to configure elastic search separately and then need to integrate with my Elassandra, But if it is then why Elassandra offers libs and configs for elastic search. I don't know, I am totally confused.

**Comment by vroyer** [comment]
No an issue !

**Comment by shanawaz12345** [comment]
same issue am also facing.. not able to access localhost:9200 in windows os. it shows connection refused. can please suggest me. any modification need to do in conf file?
