### ISSUE TITLE
SSL has been successfully enabled using the cassandra.yaml settings but not able to enable https for client to elassandra connections.

### ISSUE THREAD

**Issue by rsr999** [strapdata/elassandra#345]
Current SSL settings in cassandra.yaml:

server_encryption_options:
    internode_encryption: all
    keystore: /cassandra/keystores/keystore_name.jks
    keystore_password: abcdefg
    truststore: /cassandra/keystores/truststore_name.jks
    truststore_password: abcdefg
    # More advanced defaults below:
    protocol: TLS
    algorithm: SunX509
    store_type: JKS
    cipher_suites: [TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]
    require_client_auth: true
    require_endpoint_verification: false

client_encryption_options:
    enabled: true
    # If enabled and optional is set to true, encrypted and unencrypted connections over native transport are handled.
    optional: false
    keystore: /cassandra/keystores/keystore_name.jks
    keystore_password: abcdefg
    require_client_auth: false
    # Set trustore and truststore_password if require_client_auth is true
    truststore: /cassandra/keystores/truststore_name.jks
    truststore_password: abcdefg
    # More advanced defaults below:
    protocol: TLS
    algorithm: SunX509
    store_type: JKS
    cipher_suites: [TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]

**Comment by rsr999** [comment]
Basically need instructions and guidance on what else (in addition to the SSL setup in cassandra.yaml) is required for enabling https for client connections to elassandra.

**Comment by vroyer** [comment]
This is possible with the Elassandra Enterprise version, see doc https://elassandra.readthedocs.io/en/latest/enterprise.html#ssl-network-encryption <https://elassandra.readthedocs.io/en/latest/enterprise.html#ssl-network-encryption>

**Comment by rsr999** [comment]
Thanks Vincent, for the prompt response.
So, does that mean that https cannot be set up for open source free version?
We are using elassandra-6.8.4.4.
Is there any licensing cost for using Elassandra Enterprise Version?

**Comment by rsr999** [comment]
Also, as suggested in the readthedocs, I did try to add the 2 parameters in the elasticsearch.yml :

Setting | Default | Description
-- | -- | --
https.enabled | false | Enable HTTPS on client-to-node Elasticsearch connections
ssl.transport.enabled | false | Enable SSL on Elastisearch transport connections (node-to-node connections)

But then it prevents elassandra from even starting up.
Then it starts throwing the following errors:

ERROR [main] 2020-05-21 09:38:19,152 ElassandraDaemon.java:601 - Exception
org.elasticsearch.common.settings.SettingsException: Failed to load settings from [elasticsearch.yml]
        at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1148)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1121)
        at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:100)
        at org.apache.cassandra.service.ElassandraDaemon$5.loadEnvironment(ElassandraDaemon.java:543)
        at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:554)
Caused by: org.elasticsearch.common.ParsingException: Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING]
        at org.elasticsearch.common.xcontent.XContentParserUtils.ensureExpectedToken(XContentParserUtils.java:78)
        at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:656)
        at org.elasticsearch.common.settings.Settings.access$500(Settings.java:82)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1144)
        ... 4 common frames omitted

**Comment by vroyer** [comment]
Yes, you need to install the enterprise plugin.
A free trail version is available in version 6.8.4.5. You should upgrade to 6.8.4.5, then download and install the enterprise plugin available at https://cdn.repo.strapdata.com/enterprise/strapdata-enterprise-6.8.4.5.zip

Please contact Strapdata if you need more information about the enterprise version.

**Comment by rsr999** [comment]
Thanks Again.
Appreciate the KT.
