### ISSUE TITLE
Documents vanish automatically from elassandra index, though they are in Cassandra

### ISSUE THREAD

**Issue by pankajydv** [strapdata/elassandra#350]
**Elassandra version**: elassandra-6.8.4.3

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux cgrphdb4441 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

- We have 4 data-center Cassandra setup used in our production environment.
- We create a mapping , perform re-indexing and alias the index name to new mapping created to use the mapping changes with zero downtime. 
- After re-indexing we see the count remains same across all our 4 data-centers.
- But after 3-5 days, we see count varies widely and we see huge differences across our datacenters. For example we performed re-indexing last week and after 7 days I see a huge difference in the document count across my 4 datacenters in elassandra. In cassandra this is OK.
`{"count":43489,"_shards":{"total":10,"successful":10,"skipped":0,"failed":0}}`
`{"count":16918110,"_shards":{"total":10,"successful":10,"skipped":0,"failed":0}}`
`{"count":43645422,"_shards":{"total":11,"successful":11,"skipped":0,"failed":0}}`
`{"count":43645417,"_shards":{"total":11,"successful":11,"skipped":0,"failed":0}}`

The actual count of documents is **43645417**.

**Steps to reproduce**:

 1. In a multi data-center Cassandra setup, put a new mapping (selected fields from Cassandra schema - not all fields)
 2. Perform re-indexing using 16 threads across all the 4 datacenters, each node simultaneouls to speed-up the new index creation.
 3. Once the indexing is complete, switch the alias to new mapping thus created.
 4. We perform all of our write operations in just 1 datacenter and rest of the 3 data-centers replicate the data from the write data-center.
 5. Wait for around 7 days,and data goes so much out of sync in Elassandra, but is consistent in Cassandra.

**Please provide the following information**:

* elassandra logs (logs/system.logs or /var/lib/cassandra/system.log)
[system.log](https://github.com/strapdata/elassandra/files/4819703/system.log)
* elasticsearch cluster state (curl http://localhost:9200/_cluster/state)
[cluster-state.log](https://github.com/strapdata/elassandra/files/4819697/cluster-state.log)
* cassandra schema (cqlsh>DESC KEYSPACE <your_keyspace>)
[keyspace.log](https://github.com/strapdata/elassandra/files/4819709/keyspace.log)
* cassandra gossip state (run: nodetool gossipinfo)
[gossipinfo.log](https://github.com/strapdata/elassandra/files/4819710/gossipinfo.log)

**Comment by pankajydv** [comment]
Could this be because of Cassandra restart?

**Comment by vroyer** [comment]
Sorry, but without your full configuration and deep investigation, that's impossible to solve.
You can contact strapdata if you need professional support.

**Comment by pankajydv** [comment]
@vroyer - I have shared full configuration and all the required logs have been attached to the JIRA.
