### ISSUE TITLE
Can I change the default replication factor for all keyspaces?

### ISSUE THREAD

**Issue by didip** [strapdata/elassandra#352]
I noticed that the default RF is 1. Can I change that on Elassandra config file?

**Comment by vroyer** [comment]
Yes, see index setting replication https://elassandra.readthedocs.io/en/latest/configuration.html#elassandra-settings <https://elassandra.readthedocs.io/en/latest/configuration.html#elassandra-settings>

**Comment by didip** [comment]
That works. Thanks!
