### ISSUE TITLE
Does Elassandra require a large number of open files?

### ISSUE THREAD

**Issue by didip** [strapdata/elassandra#356]
**Elassandra version**: Latest

**Plugins installed**: []

**JVM version** (`java -version`): JDK 8

**OS version** (`uname -a` if on a Unix-like system): Ubuntu

**Description of the problem including expected versus actual behavior**:

I am load testing Elassandra by inserting the same thing again and again at 10,000 per second.

During that time, Elassandra consumes 107,000 open files based on `lsof`.

Is that a normal behavior? If it is normal, what is a good open file limit we should set for a large production cluster?

**Steps to reproduce**:

Create an index:

```
curl -k -XPUT -H 'Content-Type: application/json' 'http://10.0.7.0:9200/ks_1' -d '{
    "settings": { 
        "keyspace":"ks_1",
        "index": {
            "replication": "DC1:3",
            "search_strategy_class": "RandomSearchStrategy"
        }
    },
    "mappings": {
        "payload" : {
            "discover":"^(?!_blob).*",
            "properties" : {
               "_blob" : { "type": "text", "cql_collection" : "singleton", "index": false }
            }
        }
    }
}'
```

Download "Hey Golang" (basically yet another apache benchmark) and run this benchmark:

```
~/hey -n 10000 -c 10000 -m PUT -T "application/json" -d '
{
   "_blob" : "eyJuYW1lIjoiZGFubmllcyIsImFnZSI6NywibG9jYXRpb24iOiJwb3J0bGFuZCJ9Cg==",
   "record_body" : {
      "age" : 29,
   },
   "record_head" : {
      "timestamp" : 1593234085,
   },
   "metadata" : {
      "Collect" : {
         "token" : "token-spider-guy",
         "schema" : {
            "id" : "b65bca00-5b8d-4b76-9c30-093957f4e95f"
         },
         "id" : "4bc9640f-82cf-4e71-90f3-10713a514767"
      },
      "Client" : {
         "id" : "8e7c876f-f08e-4533-a5ca-b81fa1f59d69",
         "email" : "spider.guy@example.com",
      },
      "Info" : {
         "timestamp" : 1593234224,
         "request_id" : "3c76bfb7-5022-4482-b3d7-7b6e67b9f317"
      }
   }
}' 'http://10.0.7.0:9200/ks_1/payload/1'
```

The cluster's open file limit is currently at 90,000.

**Comment by vroyer** [comment]
Yes, that's normal, and you should increase that limit until you touch another system limit.
You should apply the recommended production settings for Cassandra, see https://doc.dovecot.org/admin_manual/cassandra/cassandra_tuning/

**Comment by didip** [comment]
As usual, thank you for the quick response.
