### ISSUE TITLE
Can I still use range query or boolean comparison if all of my data types is in String?

### ISSUE THREAD

**Issue by didip** [strapdata/elassandra#359]
Given how flexible JSON is, someone can accidentally change types inside one of the JSON field. This will raise an error in Elassandra.

So, I am wondering if I can just configure all fields as string. If the Lucene query inside Elassandra still works, then I won't have any type errors anymore.

Is this a bad idea?

**Comment by vroyer** [comment]
Once a field has a type in the elasticsearch mapping, you cannot change it anymore, any data not matching the initial defined type will be rejected.

**Comment by didip** [comment]
Sorry for not being clear.

I am planning to create a brand new index with all the fields discovered and typed as string.
Then I'll re-push the data from to this new index.

**Comment by vroyer** [comment]
Ordering on numbers is not the same as ordering on strings, so you should use the right type.

**Comment by didip** [comment]
Got it. Thanks again for answering quickly.
