### ISSUE TITLE
ElasticSearch API issues

### ISSUE THREAD

**Issue by peterdload** [strapdata/elassandra#36]
Hi,

I am having issues using the ElasticSearch API with Put, Get and Delete operations. If we use a standard ElasticSearch server then:
1. Put a document on the index - returns "created: true"
2. Get it successfully - returns "document"
3. Delete it from the index - returns "found: true"
4. Try to retrieve it again - returns nothing 

If we use Elassandra, 1,2 and 3 work but on 4 it still returns the part of the document and an ElasticSearch document id?

Again, if we use a standard ElasticSearch server:
1. Put a document on the index - returns "created: true"
2. Put same document on the index - returns "created: false"
3. Delete it from the index - returns "found: true"
4. Delete same document from the index - returns "found: false"

If we use Elassandra, the service always returns "created: true" and "found: true"? 

Although sometimes we get an error "write_failure_exception" if we try to place the same document on the index again even if we delete it first? 

And what is the story in regards to deleting indexes?

Thanks for any help

Peter

**Comment by vroyer** [comment]
Hi,
In elassandra, index and delete operations are transformed to CQL insert and delete, so create and found are always true if CQL succeed  to avoid a read before write in cassandra. 
For the delete operation not really deleted, it is not yet implemented and you should see such a message in your logs. I should fix this in the first week of august.
Thanks'
Vincent.

**Comment by vroyer** [comment]
Solved with release 2.1.1-16, delete operation is implemented, and nodetool cleanup also delete document form elasticsearch indices.
