### ISSUE TITLE
CQL Map types with map<text, text> throws mapper_parsing_exception when used in UDT

### ISSUE THREAD

**Issue by bhardwajkunla555** [strapdata/elassandra#365]
I have created UDT in Cassandra

CREATE type starter.random_data_demo(  
   destination_wise_count map<text,text>
);

then used this udt in my table

CREATE TABLE demo(
   field_data FROZEN<random_data_demo> PRIMARY KEY 
   );
when i hit query for elasticsearch mapping receives an error

query:-

curl -XPUT -H 'Content-Type:application/json' "http://localhost:9200/demo" -d '{
    "settings": { "keyspace":"starter" },
    "mappings": {
        "demo" : {
            "discover" : ".*"
        }
    }
}'

error:-

{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "Failed to execute query:null : Field \"destination_wise_count\" with type map<text, text> does not match type frozen<\"testing.demo_field_data_destination_wise_count\">"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Failed to execute query:null : Field \"destination_wise_count\" with type map<text, text> does not match type frozen<\"testing.demo_field_data_destination_wise_count\">",
        "caused_by": {
            "type": "invalid_request_exception",
            "reason": "Field \"destination_wise_count\" with type map<text, text> does not match type frozen<\"testing.demo_field_data_destination_wise_count\">"
        }
    },
    "status": 400
}

**Comment by vroyer** [comment]
CQL map is currently only supported as a top level field of a document, you cannot use it in a nested field.
