### ISSUE TITLE
 Can the number of shards under an index be set or must it be the number of nodes

### ISSUE THREAD

**Issue by tengzhuofei** [strapdata/elassandra#376]

**Comment by Coder-Qian** [comment]
Each Cassandra node is an Elasticsearch shard for each indexed keyspace. Unlike Elasticsearch, sharding depends on the number of nodes in the datacenter, and the number of replica is defined by your keyspace Replication Factor . Elasticsearch numberOfShards is just information about the number of nodes.

**Comment by vroyer** [comment]
Good explanation given by Coder-Qian
