### ISSUE TITLE
Question: Will this project continue being OSS, or will it become part of DSE?

### ISSUE THREAD

**Issue by carlspring** [strapdata/elassandra#390]
Hi,

We're investigating Elassandra, as we're interested in using it in our OSS project. We can see that Strapdata's site now points to DataStax, which leads us to think that this has been acquired by DataStax.

What does this mean for the future of this project:
* Will it continue being developed as OSS?
* Will it become part of a commercial offerring of DataStax, such as DSE?
* Do you foresee any licensing issues with ES's latest license changes?
* What's the future roadmap of this project?

Many thanks in advance!
Kind regards,

Martin

**Comment by carlspring** [comment]
@vroyer ,

Would you perhaps be able to comment...? ;)

**Comment by dioptre** [comment]
+1

**Comment by Stoyan-Bukovich** [comment]
Good question. Many of us are eager to know the future plans of this project.

**Comment by steve-todorov** [comment]
I've been watching this thread for a while and would also like to hear what are the future plans?

**Comment by dioptre** [comment]
My 2c are that the project should continue, here or in another fork.

Amazon's fork of their supported version of ES could be used as a replacement for the standard ES license. 

Cassandra 4 is coming up, and it would be great to continue the project into v4.

DSE already has another product based on SOLR which would internally compete with Elassandra... But Vincent's work is brilliant combining the data-sources of each into a single distributed data-store. 

Apache Arrow could be a long term alternative, as a lot of products are committing to shared interprocess storage of underlying data. I've heard the Cassandra team was interested in this, but might be a long time away.

Regardless, this project could be the foundation of something much bigger. I hope Vincent knows it and will lead it internally within DSE. It would be good to get his feedback eventually on this, so we can help or independent work might continue.

**Comment by vroyer** [comment]
Sorry about that, I cannot contribute anymore to this project, so it is end-of-life.
