### ISSUE TITLE
Upgarding ElasticSearch for Elassandra

### ISSUE THREAD

**Issue by chinmaya24x7** [strapdata/elassandra#40]
Hi,

The latest release of Elassandra contains Elastic Search version 2.1.1.
I want to upgrade elastic search to the latest release i.e 2.3.4 so that i can use kibana latest release i.e 4.5 for elassandra.
I am unable to find any information on the same.
Please provide steps to upgrade.

Thanks.

regards,
Chinmaya

**Comment by vroyer** [comment]
Hi,
Upgrading elasticsearch require to merge elassandra and the last version of elasticsearch. There is about 100 elasticsearch modified classes from elasticsearch 2.1.1 to merge with elasticsearch 2.1.1+. I plan to do this upgrade for septembre 2016, but you can try it if you want.
Thanks'
Vincent

**Comment by chinmaya24x7** [comment]
Hi Vincent,

Thanks for your reply.
If we use elassandra on production, any team or some one would be there to support us for any issues?

Thanks.
Chinmaya

**Comment by vroyer** [comment]
Hi Chinmaya,

Yes, we plan to deliver production support by the end of 2016 with strapdata, a new company supporting elassandra.
Moreover, elassandra will be presented at the cassandra summit 2016 at San Jose.

Thanks,
Vincent.

**Comment by W3Max** [comment]
Any news about the merge with elasticsearch 2.1.1+ ? 

I would like to give this project a try but I am scared of the idea of not being able to use the desired version of elasticsearch or cassandra (as they are embedded in elassandra).

Thanks!

Maxime

**Comment by vroyer** [comment]
Next release of Elassandra will be based on Elasticsearch 2.4 + Cassandra 2.2.8, probably by the end of November (and upgrade to cassandra 3.0.last by the end of 2016).

**Comment by shohamlevy** [comment]
Waiting for ES 2.4 as well. I want to use the  [Update By Query](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-update-by-query.html) plugin that was introduced in 2.3 and replaces the deprecated (since 2.0) [plugin](https://github.com/yakaz/elasticsearch-action-updatebyquery).

Shoham

**Comment by mishka2000** [comment]
Also waiting for Elastic Search 2.4.
The "end of November" date is still relevant ?

**Comment by vroyer** [comment]
Yes,  it should be available by the end of November, it's currently under testing.

**Comment by vroyer** [comment]
Elassandra release 2.4.2 is available. 
It includes unit tests support and ES plugins.
