### ISSUE TITLE
Not enough active copies to meet write consistency of [QUORUM] (have 0, needed 1)

### ISSUE THREAD

**Issue by starwithmoon** [strapdata/elassandra#43]
when the elassandra(version:elassandra-2.1.1-16) cluster setup ok, execute the command:
curl -XPUT 'http://localhost:9200/twitter/user/kimchy' -d '{ "name" : "Shay Banon" }'

response:
Not enough active copies to meet write consistency of [ QUORUM ](have 0, needed 1). Timeout: [1m]

Please let me know what I am doing wrong here and help me in resolving this issue. Thanks!
[cluster_info.txt](https://github.com/vroyer/elassandra/files/451948/cluster_info.txt)
[system_log.txt](https://github.com/vroyer/elassandra/files/451949/system_log.txt)

**Comment by vroyer** [comment]
Hi,

You have a wrong transport_adress 0.0.0.0 on one node and your routing table is empty.
In your conf/cassandra.yaml, you should have **listen_address: 20.20.20.57**  for this node (do not set any ip adress in conf/elasticsearch.yml ). Could you fix this on all nodes and restart.

Thanks'.
Vincent.

```
"4d25b351-8e83-40d6-b28d-4f8e3f68f47e" : {
      "name" : "20.20.20.57",
      "status" : "ALIVE",
      "transport_address" : "0.0.0.0:9300",
      "attributes" : {
        "rack" : "rack1",
        "data" : "true",
        "data_center" : "dc1",
        "master" : "true"
      }
    },
```

**Comment by starwithmoon** [comment]
Thank you very much! Problem has been resolved.  I'm a beginer, config the wrong rpc_address. 

THX
