### ISSUE TITLE
Mailing list ?

### ISSUE THREAD

**Issue by ddorian** [strapdata/elassandra#46]
Some issues would be better in a mailing list. This way less work for the developers having questions in the issues. Something like a google group should be easy to set up.

**Comment by vroyer** [comment]
Hi,

Good idea, I have created an elassandra web form on google group https://groups.google.com/forum/#!forum/elassandra

Vincent.

**Comment by ddorian** [comment]
Need to be open (i think) and added to docs/readme. And current issues that aren't bugs/features closed and pointed there.

**Comment by vroyer** [comment]
Ok, it's now open, and support link added to the README.md.

**Comment by ddorian** [comment]
I think you should also make it public to read/search it? Currently you need to apply + get accepted just to read it. (should be only for writing).
Open in icognito/private to verify: https://groups.google.com/forum/#!forum/elassandra
