### ISSUE TITLE
Support for PasswordAuthenticator/CassandraAuthorizer [QUESTION]

### ISSUE THREAD

**Issue by timd112** [strapdata/elassandra#49]
I apologize if this is already stated, but I couldn't find anything mentioned in the documentation or the other issues.  

Is there support for those using the PasswordAuthenticator/CassandraAuthorizer?

I was able to spin up a cluster with the "AllowAllAuthenticator" and everything works great. I encounter errors when I try to build a cluster (or single node) with:
`authenticator: org.apache.cassandra.auth.PasswordAuthenticator`
`authorizer: org.apache.cassandra.auth.CassandraAuthorizer`

Cassandra starts fine, but none of the ElasticSearch functionality seems to work, which probably makes sense if it can't write to the `elastic_admin` keyspace.

If needed, running:
elassandra-2.1.1-17.9.noarch
elassandra-kibana-4.3.3-1.x86_64

I can send more info if needed.

**Comment by vroyer** [comment]
Yes, it’s not currently supported, elasticsearch security is not yet integrated to cassandra, but this is something i plan to deliver within few months.

**Comment by timd112** [comment]
Thanks for the update.  Is there an issue I can watch to keep track of the progress?

**Comment by vroyer** [comment]
Ok, we can keep that one open.

**Comment by vroyer** [comment]
Strapdata now provides an Enterprise plugin including Elasticsearch user authentication and authorization based on Cassandra PasswordAuthenticator and CassandraAuthorizer. Thus, Elasticsearch and Cassandra share the same user and roles. Detailed documentation is available at [http://doc.elassandra.io/en/latest/enterprise.html#authentication-and-authorization](http://doc.elassandra.io/en/latest/enterprise.html#authentication-and-authorization).
