### ISSUE TITLE
Elastic Search plugins support

### ISSUE THREAD

**Issue by somecallmemike** [strapdata/elassandra#51]
Hello, I am wondering if Elassandra will support the ecosystem of ES plugins, in specific the watcher plugin for sending alerts?

**Comment by vroyer** [comment]
Hi,
It supports plugins, but, as far as i known, watcher is a commercial plugin that require a licence from Elasticsearch.
You need to trigger some events ?
Vincent.

**Comment by somecallmemike** [comment]
Vincent,

Yes we are interested in using ES for SEIM event alerting.  ES is a perfect system for storing indexed data and especially retrieving data based on grok processing that can identify trends.

**Comment by lmangani** [comment]
@somecallmemike you might want to give [sentinl](https://github.com/sirensolutions/sentinl) a try, it should work great with Elassandra as it run within the Kibana engine
