### ISSUE TITLE
Counter data type mappings

### ISSUE THREAD

**Issue by JodusNodus** [strapdata/elassandra#55]
I have a `mangahits` counter table with a `hits` counter column. When i try to map the table with discover it return the following error.
`Failed to parse mapping [mangahits]: No type specified for field [hits]`

When i add the property manually with an integer (or any other number type) it also returns an error.
`Existing column hits mismatch type int`

Am i doing something wrong, or is it just not possible ? I couldn't find any mention of the counter type anywhere in the docs.

**Comment by vroyer** [comment]
Hi,

Indexing counter columns is not supported, cassandra does not support secondary index on counters.
But you can use integer column for exemple, and update this column in a lightweight transaction to increment it like a counter (see https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_ltweight_transaction_t.html https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_ltweight_transaction_t.html ).
It comes with a cost, but it’s consistent.

**Comment by JodusNodus** [comment]
@vroyer Ok, no problem. I will use that method as a solution. 👍
