### ISSUE TITLE
Zombie Data on Elassandra / Dirty Reads

### ISSUE THREAD

**Issue by diegopacheco** [strapdata/elassandra#56]
@vroyer 

Elassandra is not DELETING 100% the data.  Sometimes the data appears again so looks like is on a zombie state.

Information 

 Elassandra version: 2.1.1-17 build from GitHub source code. 
 Cassandra version: 2.2.

Steps to Simulate the issue:

``` markdown
1. Build and RUN Elassandra 2 nodes cluster. 
2. INSERT DATA via ES REST API:
curl -XPUT 'IP_NODE1:9200/customer/external/1?pretty' -d '
{
  "name": "John Doe 1"
}'
3. DELETE all DATA via ES API: curl -XDELETE http://IP_NODE1:9200/*
4. SEARCH ALL DATA via ES API: curl http://IP_NODE1:9200/_all/_search?pretty=true&q=*:* This should return nothings - AND it returns nothing! (so far so good)
5. INSERT NEW DATA ES API: curl -XPUT 'IP_NODE1:9200/customer/external/2?pretty' -d '
{
  "name": "John Doe 2"
}'
6. Query ALL DATA again (BOOM - here is the problem - Zombie data is back!) curl http://IP_NODE1:9200/_all/_search?pretty=true&q=*:*
```

``` bash
curl http://IP_NODE1:9200/_all/_search?pretty=true&q=*:*
[1] 509
[ec2-user@ip-172-28-198-82 ~]$ {
  "took" : 47,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "customer",
      "_type" : "external",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{"name":"John Doe 1"}
    }, {
      "_index" : "customer",
      "_type" : "external",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{"name":"John Doe 2"}
    } ]
  }
}
```

Cheers,
Diego Pacheco

**Comment by vroyer** [comment]
Hi Diego,

Yes, deleting an Elasticsearch index (step 3), does not delete cassandra data in the underlying tables, but only Elasticsearch files and mapping (see http://doc.elassandra.io/en/latest/operations.html#create-delete-and-rebuild-index http://doc.elassandra.io/en/latest/operations.html#create-delete-and-rebuild-index ).
By recreating an index in step 5, elassandra re-index the new document and all existing data in the underlying table, so the doc 1 is re-indexed. 

With cqlsh, you can look at the table content to see this behavior. If you really was to drop all your documents at step 3, please drop or truncate all cassandra tables associated to your index.
Obviously, deleting a document with the ES API also delete it at the cassandra layer.

Thanks’.

**Comment by diegopacheco** [comment]
Thanks for the information. 

So If get it this properly we need to run node tool like is on the docs time to time otherwise we can run into inconsistency scenarios right? Or simply do a truncate at Cassandra side.... Correct? So this change how we operate ES compared with Elassandra. 

``` bash
nodetool rebuild_index [--threads <N>] <keyspace> <table> elastic_<table>
```

**Comment by vroyer** [comment]
Yes, if you want to delete cassandra dara when deleting an index, you actually need to TRUNCATE or DROP all underlying tables (one table by document type) (DROP TABLE <keyspace>.<table>)
As you can have many indices for the same cassandra keyspace (to update the mapping with zero downtime for exemple), it would be dangerous to drop cassandra table when deleting an index.
But i can change that to also delete cassandra data if you really need it, it could be an index setting to change this default behavior ?

(The nodetool rebuild_index allow to rebuild elasticsearch index from a cassandra table).

**Comment by diegopacheco** [comment]
OK.

We will run nodetool. Thanks for the clarification.
