### ISSUE TITLE
Elassandra installation using Tarball

### ISSUE THREAD

**Issue by uttamraj9** [strapdata/elassandra#60]
I have install elassandra using tarball followed http://doc.elassandra.io/en/latest/installation.html.
[root@localhost elasticsearch]# nodetool status
Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  127.0.0.1  170.83 KB  256          100.0%            50fd6cd2-ace6-4562-8da0-6b9967411d5f  r1

[bigdata@localhost conf]$ curl -XGET 'http://localhost:9200/_cluster/state/?pretty=true'
{
  "cluster_name" : "elasticsearch",
  "version" : 55,
  "state_uuid" : "lTMYz8U2RbO_iGJSH6mM0g",
  "master_node" : "neADQO64TKOAu7QV1OGVIw",
  "blocks" : { },
  "nodes" : {
    "neADQO64TKOAu7QV1OGVIw" : {
      "name" : "Shatter",
      "transport_address" : "127.0.0.1:9300",
      "attributes" : { }
    }
  },

but not able to connect elassandra with elasticsearch.

I have table in cassandra I am able to create Index but value is not coming in index.
curl -XPUT "http://localhost:9200/betausers/" -d '{
"settings" : { "keyspace" : "skywardsengagementprofile" } },
"mappings" : {
"betausers" : {
"properties" : {
"skywardsid" : { "type" : "string", "index" : "not_analyzed" },
"cityofresidencel" : { "type" : "string", "index" : "not_analyzed"  },
"countryofresidence" : { "type" : "string","index" : "not_analyzed" },
"email" : {"type" : "string", "index" : "not_analyzed"  },
"sepid" : { "type" : "string", "index" : "not_analyzed"  },
}
}
}
}'

Some help will be appreciated.

**Comment by vroyer** [comment]
Hi,

It seems yo are running a standalone elasticsearch because master_node neADQO64TKOAu7QV1OGVIw does not match your cassandra hostId  50fd6cd2-ace6-4562-8da0-6b9967411d5f.
In Elassandra, Elasticsearch is embedded in cassandra, so you don’t need to start any elasticsearch jvm.

Cheers,
Vincent.

**Comment by uttamraj9** [comment]
Thanks For Reply,
How to start elasandra and elasticsearch from tarball installation???

**Comment by vroyer** [comment]
Just run bin/cassandra -e
It starts cassandra with embedded elasticsearch.

**Comment by uttamraj9** [comment]
[root@localhost elassandra]# bin/cassandra -e
Starting with Elasticsearch enabled.
[root@localhost elassandra]# CompilerOracle: inline org/apache/cassandra/db/AbstractNativeCell.compareTo (Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/db/composites/AbstractSimpleCellNameType.compareUnsigned (Lorg/apache/cassandra/db/composites/Composite;Lorg/apache/cassandra/db/composites/Composite;)I
CompilerOracle: inline org/apache/cassandra/io/util/Memory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/io/util/SafeMemory.checkBounds (JJ)V
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare (Ljava/nio/ByteBuffer;[B)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compare ([BLjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/ByteBufferUtil.compareUnsigned (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/lang/Object;JI)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/lang/Object;JILjava/nio/ByteBuffer;)I
CompilerOracle: inline org/apache/cassandra/utils/FastByteOperations$UnsafeOperations.compareTo (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I

Getting this error..........

**Comment by vroyer** [comment]
It’s not an error, it’s stdout, look at your logs…

**Comment by uttamraj9** [comment]
2016-11-05 13:11:06,048 WARN  [main] CLibrary.java:205 tryMlockall Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.

**Comment by vroyer** [comment]
Please apply recommended settings as mentioned in the documentation http://doc.elassandra.io/en/latest/installation.html#tarball-installation http://doc.elassandra.io/en/latest/installation.html#tarball-installation
(OS tunning + install JNA …)

**Comment by uttamraj9** [comment]
2016-11-05 13:11:06,048 WARN  [main] CLibrary.java:205 tryMlockall Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.
curl -XPUT "http://localhost:9200/betausers/" -d '{
"settings" : { "keyspace" : "skywardsengagementprofile" } },
"mappings" : {
"betausers" : {
"properties" : {
"skywardsid" : { "type" : "string", "index" : "not_analyzed" },
"cityofresidencel" : { "type" : "string", "index" : "not_analyzed"  },
"countryofresidence" : { "type" : "string","index" : "not_analyzed" },
"email" : {"type" : "string", "index" : "not_analyzed"  },
"sepid" : { "type" : "string", "index" : "not_analyzed"  },
}
}
}
}'

**Comment by uttamraj9** [comment]
###Thanks Alot.......Now Its working I have some doubts in creating Index..
curl -XPUT "http://localhost:9200/betausers/" -d '{
"settings" : { "keyspace" : "skywardsengagementprofile" } },
"mappings" : {
"betausers" : {
"properties" : {
"skywardsid" : { "type" : "string", "index" : "not_analyzed" },
"cityofresidencel" : { "type" : "string", "index" : "not_analyzed"  },
"countryofresidence" : { "type" : "string","index" : "not_analyzed" },
"email" : {"type" : "string", "index" : "not_analyzed"  },
"sepid" : { "type" : "string", "index" : "not_analyzed"  },
}
}
}
}'
Index is created but not showing elasticHq....
{"acknowledged":true}[bigdata@localhost ~]$ nodetool compactionstats
pending tasks: 0
[bigdata@localhost ~]$ curl -XGET http://localhost:9200/_cluster/state/?pretty=true
{
  "cluster_name" : "TestCluster",
  "version" : 11,
  "state_uuid" : "Og8ZC5YIRvuBbLTu7Gp-Sw",
  "master_node" : "50fd6cd2-ace6-4562-8da0-6b9967411d5f",
  "blocks" : { },
  "nodes" : {
    "50fd6cd2-ace6-4562-8da0-6b9967411d5f" : {
      "name" : "localhost",
      "status" : "ALIVE",
      "transport_address" : "127.0.0.1:9300",
      "attributes" : {
        "rack" : "r1",
        "data" : "true",
        "data_center" : "DC1",
        "master" : "true"
      }
    }
  },
  "metadata" : {
    "version" : 5,
    "cluster_uuid" : "50fd6cd2-ace6-4562-8da0-6b9967411d5f",
    "templates" : { },
    "indices" : {
      "twitter" : {
        "state" : "open",
        "settings" : {
          "index" : {
            "creation_date" : "1478338293207",
            "number_of_shards" : "1",
            "number_of_replicas" : "0",
            "uuid" : "rw78ZHVoQXKQVp9ieM3nxw",
            "version" : {
              "created" : "2010199"
            }
          }
        },

```
  "betausers" : {
    "state" : "open",
    "settings" : {
      "index" : {
        "keyspace" : "skywardsengagementprofile",
        "creation_date" : "1478339602983",
        "number_of_shards" : "1",
        "number_of_replicas" : "0",
        "uuid" : "zapyYvPpSNai9yDHe04ZBw",
        "version" : {
          "created" : "2010199"
        }
      }
    },
    "mappings" : { },
    "aliases" : [ ]
  },
```

Data is there in cassandra table How to insert to elasticsearch.

**Comment by vroyer** [comment]
Cassandra data are automatically indexed in elasticsearch, as soon as you configure the Elasticsearch mapping. So it should be good.
Please verify that you have secondary index in the cassandra schema(cqlsh > DESC KEYSPACE beta users). 

With the following command, the number of documents in Elasticsearch should match the number of line in your table. 

curl -s -XGET http://localhost:9200/_cat/indices?v

**Comment by uttamraj9** [comment]
Thanks Vroyer...
Can you please guide me which kibana version I need to install for elassandra... and how to configure elasticsearch with kibana..I have Install kibana but it is not starting....

[root@localhost Downloads]# systemctl status kibana
● kibana.service - no description given
   Loaded: loaded (/usr/lib/systemd/system/kibana.service; enabled; vendor preset: disabled)
   Active: active (exited) since Tue 2016-11-15 11:58:21 PST; 2 days ago

Nov 15 11:58:21 localhost.localdomain systemd[1]: Starting LSB: no description given...
Nov 15 11:58:21 localhost.localdomain systemd[1]: Started LSB: no description given.
Nov 15 11:58:21 localhost.localdomain kibana[8930]: kibana started

I am not able to open kibana  in browser..
[root@localhost bigdata]# telnet localhost 5601
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
