### ISSUE TITLE
 "Peer's Certificate has expired."

### ISSUE THREAD

**Issue by jed-ob** [strapdata/elassandra#61]
Hi I have reinstalled my elassandra, It did fail after the last update. I am encountering an expired certificate. How can I get pass this? Thanks

**

> failure: repodata/repomd.xml from Elassandra: [Errno 256] No more mirrors to try.
> https://packages.elassandra.io/rpm/elassandra/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate has expired."

**

**Comment by jed-ob** [comment]
Hi,

 Kindly change the #6 of http://doc.elassandra.io/en/latest/install_rpm.html (this will save more time on installing) following the documentation. Thanks

```
 rpm -qa gpg-pubkey --qf "%{version}-%{release} %{summary} f1d18d84-5724b296 gpg(Elassandra <build@elassandra.org>) 34ec9cba-54e38751 gpg(Fedora (23) <fedora-23-primary@fedoraproject.org>) "
```

instead of:

```
rpm -qa gpg-pubkey --qf "%{version}-%{release} %{summary}\n"
f1d18d84-5724b296 gpg(Elassandra <build@elassandra.org>)
34ec9cba-54e38751 gpg(Fedora (23) <fedora-23-primary@fedoraproject.org>)
```

**Comment by vroyer** [comment]
New rpm+debian packaging will be delivered in the next version.

**Comment by vroyer** [comment]
rpm and deb packages are currently automatically built by travis and not signed.
