### ISSUE TITLE
Elassandra as C* plugin

### ISSUE THREAD

**Issue by ausov** [strapdata/elassandra#63]
Is that possible to use Elassandra as C* plugin? 

Have you considered or planned this possibility? We were evaluating this possibility and then found your promising solution. Do you think this would be possible at all, e.g. using embedded ES + your customisations?

**Comment by vroyer** [comment]
Elassandra is Cassandra + Elasticsearch, and you can start C\* nodes without enabling Elasticsearch (controlled by the option -e  in bin/cassandra). You can have some cassandra only datacenters, and some cassandra datacenters with embedded elasticsearch enable, it's up to you.
