### ISSUE TITLE
UDT by name support

### ISSUE THREAD

**Issue by shohamlevy** [strapdata/elassandra#64]
I am using Elassandra 2.1.1-18.1  - I am using UDT field mappings.

The problem is that when defining a field as UDT, the TYPE's name is automatically derived from **\<table>_<field>** You cannot use your own UDT name. This makes UDT much weaker because the purpose of UDT is TYPE reuse. And in this case, the UDT must be different for each field in the document - even if the fields are of the same TYPE.
`
"type": "nested",  "cql_struct": "udt", "properties": {...}
`

Could it be possible to supply another variable, stating the UDT's (Cassandra) TYPE name? Of course it also implies checking if the type already exists, and not trying to recreate it.

`
"type": "nested",  "cql_struct": "udt", "cql_udt_name": "MyUDTType", "properties": {...}
`

**Comment by vroyer** [comment]
Ok, I'm currently working on elasticsearch upgrade to version 2.4, then i will add this feature.

**Comment by vroyer** [comment]
This is supported in release 2.4.2-2. 
Unit test is provided in https://github.com/strapdata/elassandra/blob/master/core/src/test/java/org/elassandra/NamedUdtTests.java, see http://doc.elassandra.io/en/latest/testing.html to run tests.
