### ISSUE TITLE
elassandra installation on mac | No module named Cython.Build

### ISSUE THREAD

**Issue by Sid-CS** [strapdata/elassandra#66]
While following the instructions from the documentation - http://doc.elassandra.io/en/latest/installation.html#tarball-installation

After installing cassandra-driver successfully, I am facing an error while in step 5, command: `python pylib/setup.py install`

Error:

```
Traceback (most recent call last):
  File "pylib/setup.py", line 33, in <module>
    ext_modules=get_extensions(),
  File "pylib/setup.py", line 26, in get_extensions
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
```

**Comment by vroyer** [comment]
cqlsh require python 2.7+ (see cassandra pre-requisite)
Your python is likely not properly installed or configured.
Alternatively, run pip install cassandra-driver
