### ISSUE TITLE
ES Object Type stringified in search

### ISSUE THREAD

**Issue by lmangani** [strapdata/elassandra#68]
When inserting fields mapped as ```object```  type contents are returned as strings in search. 

In comparison my stock ES 2.x returns ```object``` fields as a valid JSON objects without escaping.

###### Steps to Reproduce

* Create Mapping:

```json
PUT watcher/watch/_mapping
{
        "properties": {
          "uuid": {
          "type":  "string",
          "index": "not_analyzed"
          },
          "condition": {
            "type":"object",
            "enabled": false
          }
        }
}
```

* Insert document with object fields

```json
PUT watcher/watch/test_watch_random23
{
    "uuid": "test",
    "trigger": {
      "schedule": {
        "later": "every 1 minutes"
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    }
  }
```

* Query results, objects are returned as strings
```
GET watcher/_search 
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "watcher",
        "_type": "watch",
        "_id": "test_watch_random23",
        "_score": 1,
        "_source": {
          "condition": "{\"script\":{\"script\":\"payload.hits.total > 1\"}}",
          "trigger": {
            "schedule": {
              "later": "every 1 minutes"
            }
          },
          "uuid": "test"
        }
      }
    ]
  }
}
```

**Comment by vroyer** [comment]
Hi Lorenzo,

I have fixed this and i get the following result in your use case.

curl -XGET "$NODE:9200/watcher/_search?pretty"
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "watcher",
      "_type" : "watch",
      "_id" : "test_watch_random23",
      "_score" : 1.0,
      "_source" : {
        "condition" : {
          "script" : {
            "script" : "payload.hits.total > 1"
          }
        },
        "trigger" : {
          "schedule" : {
            "later" : "every 1 minutes"
          }
        },
        "uuid" : "test"
      }
    } ]
  }
}

But if i request for field condition, ES reject it because it’s not a leaf field (it’s an object field). 

curl -XGET "$NODE:9200/watcher/_search?pretty&fields=condition"
{
  "error" : {
    "root_cause" : [ {
      "type" : "illegal_argument_exception",
      "reason" : "field [condition] isn't a leaf field"
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query_fetch",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "watcher",
      "node" : "94357fe9-a789-462e-be0e-5889f1ff1090",
      "reason" : {
        "type" : "illegal_argument_exception",
        "reason" : "field [condition] isn't a leaf field"
      }
    } ]
  },
  "status" : 400
}`

If i request the leaf field condition.script, i don’t have any result because this leaf field is not known internally.
So, what is the expected behavior there ?

curl -XGET "$NODE:9200/watcher/_search?pretty&fields=condition.script"
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "watcher",
      "_type" : "watch",
      "_id" : "test_watch_random23",
      "_score" : 1.0
    } ]
  }
}

**Comment by lmangani** [comment]
Hi Vincent,

The initial response you posted seems now correct, also the second point is as expected as the object should only be returned "readable" but not otherwise available for search etc. 
I'll be happy to test it once you push the change :)

**Comment by lmangani** [comment]
Confirmed resolved with latest GIT object types are returned as valid JSON - Thanks Vincent & Happy New Year!
