### ISSUE TITLE
ES Deleted Ghost Documents

### ISSUE THREAD

**Issue by lmangani** [strapdata/elassandra#71]
Using the latest build I am experiencing some "ghosting" effect _(for lack of better description)_ affecting documents in supposedly deleted Elasticsearch indices. Posting as an issue for others to replicate/confirm or suggest the issue being triggered.

### Steps to Replicate
```
PUT _template/plain_index
{
    "template": "plain_index-*",
    "mappings": {
      "test_type": {
        "properties": {
          "uuid": {
            "type": "string"
          }
        }
      }
    }
}
PUT plain_index-1/test_type/test_doc1
{
  "uuid": "some string 1"
}
GET plain_index-1/_search
GET plain_index-1/_mapping

PUT plain_index-1/test_type/test_doc2
{
  "uuid": "some string 2",
  "random": true
}
GET plain_index-1/_search
GET plain_index-1/_mapping

PUT plain_index-1/test_type/test_doc3
{
  "uuid": "some string 3",
  "random": false,
  "condition": { "test": "value" }
}
GET plain_index-1/_search
GET plain_index-1/_mapping
```

So far, all good. Documents are indexed and new fields added to the mapping correctly each time.
Next we're going to drop the data and once confirmed deleted, simply try create one of the documents again (or even a brand new one):

```
DELETE plain_index-1
PUT plain_index-1/test_type/test_doc1
{
  "uuid": "some string 1"
}
GET plain_index-1/_search



{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 1,
    "hits": [
      {
        "_index": "plain_index-1",
        "_type": "test_type",
        "_id": "test_doc3",
        "_score": 1,
        "_source": {
          "uuid": "some string 3"
        }
      },
      {
        "_index": "plain_index-1",
        "_type": "test_type",
        "_id": "test_doc2",
        "_score": 1,
        "_source": {
          "uuid": "some string 2"
        }
      },
      {
        "_index": "plain_index-1",
        "_type": "test_type",
        "_id": "test_doc1",
        "_score": 1,
        "_source": {
          "uuid": "some string 1"
        }
      }
    ]
  }
}
```

The old documents seem to have resurrected as ghosts of their old self, presenting only the fields available in the newly "created" document.

**Comment by vroyer** [comment]
Yes, this is the default behavior. Elassandra use cassandra as the primary storage for Elasticsearch, so by default, deleting an ES index does not delete any data in the underlying cassandra tables. Then if you re-create an ES index, existing data are re-indexed automatically (if you have a lot of data, you will observe a rebuild_index task in the cassandra compaction manager with a node tool compactionstats). So, If you want to remove existing data, you need to TRUNCATE the underlying C* tables.

Alternatively, you can configure Elassandra to work exactly as Elasticsearch with the  drop_on_delete_index setting configured at index or cluster level (see configuration in doc). When  drop_on_delete_index=true deleting an index involve the deletion of the underlying table or even the underlying keyspace if all tables were indexed. drop_on_delete_index=true is applied to play elasticsearch unit tests, thus it behaves like elasticsearch.

**Comment by lmangani** [comment]
Thanks Vincent! I did not realize at first I was just hitting a usecase for the reindexing (so far I was just exploring compatibility overall) so this is interesting to learn. Are there any plans to add a flag to the API to automatically trigger a TRUNCATE on the C* tables rather than choose either method upfront?

**Comment by lmangani** [comment]
Sorry to ask again but I can't quite get this to work.
Both cassandra.yaml and rlasticsearch.yaml seem to dislike it as documented, could you help out with an example? Thanks!
