### ISSUE TITLE
ES Template Mapping issue with Object Type

### ISSUE THREAD

**Issue by lmangani** [strapdata/elassandra#72]
When using template mapping defining  ```object``` types _(alongside any other type)_ in indices with a variable number of fields being sent, some forceful application of the underlying schema seems to take place. 

An example is provided with a set of basic documents with incremental fields/columns being inserted.
The [same scenario](https://github.com/strapdata/elassandra/issues/71) works much better when the template mapping lacks any object definition.

```
PUT _template/test_index
{
    "template": "test_index-*",
    "mappings": {
      "test_type": {
        "properties": {
          "uuid": {
            "type": "string"
          },
          "condition": {
            "type":"object",
            "enabled": false
          }
        }
      }
    }
}
PUT test_index-1/test_type/test_doc1
{
  "uuid": "some string"
}
GET test_index-1/_search
GET test_index-1/_mapping

PUT test_index-1/test_type/test_doc2
{
  "uuid": "some string",
  "random": true
}
GET test_index-1/_search
GET test_index-1/_mapping

PUT test_index-1/test_type/test_doc3
{
  "uuid": "some string",
  "random": false,
  "condition": { "test": "value" }
}




{
   "error": {
      "root_cause": [
         {
            "type": "class_cast_exception",
            "reason": "java.lang.String cannot be cast to java.lang.Boolean"
         }
      ],
      "type": "class_cast_exception",
      "reason": "java.lang.String cannot be cast to java.lang.Boolean"
   },
   "status": 500
}
```

**Comment by vroyer** [comment]
I did not succeed to reproduce this issue. 
As you see below, it works with the elassandra-2.4.2 (master branch).

$ curl -XPUT "$NODE:9200/_template/test_index" -d'{
>     "template": "test_index-*",
>     "mappings": {
>       "test_type": {
>         "properties": {
>           "uuid": {
>             "type": "string"
>           },
>           "condition": {
>             "type":"object",
>             "enabled": false
>           }
>         }
>       }
>     }
> }'
{"acknowledged":true}


$ curl -XPUT "$NODE:9200/test_index-1/test_type/test_doc1" -d'{
>   "uuid": "some string"
> }'
{"_index":"test_index-1","_type":"test_type","_id":"test_doc1","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}


$ get test_index-1/_search
{"took":20,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}


$ get test_index-1/_mapping
{"test_index-1":{"mappings":{"test_type":{"properties":{"condition":{"type":"object","enabled":false},"uuid":{"type":"string"}}}}}}


$ curl -XPUT "$NODE:9200/test_index-1/test_type/test_doc2" -d'{
>   "uuid": "some string",
>   "random": true
> }'
{"_index":"test_index-1","_type":"test_type","_id":"test_doc2","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}


$ get test_index-1/_search
{"took":18,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test_index-1","_type":"test_type","_id":"test_doc1","_score":1.0,"_source »:


$ get test_index-1/_mapping
{"test_index-1":{"mappings":{"test_type":{"properties":{"condition":{"type":"object","enabled":false},"random":{"type":"boolean"},"uuid":{"type":"string"}}}}}}


$ curl -XPUT "$NODE:9200/test_index-1/test_type/test_doc3" -d'{
>   "uuid": "some string",
>   "random": false,
>   "condition": { "test": "value" }
> }'
{"_index":"test_index-1","_type":"test_type","_id":"test_doc3","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}

$ get "test_index-1/_search?pretty"
{
  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_index-1",
      "_type" : "test_type",
      "_id" : "test_doc1",
      "_score" : 1.0,
      "_source" : {
        "uuid" : "some string"
      }
    }, {
      "_index" : "test_index-1",
      "_type" : "test_type",
      "_id" : "test_doc2",
      "_score" : 1.0,
      "_source" : {
        "random" : true,
        "uuid" : "some string"
      }
    }, {
      "_index" : "test_index-1",
      "_type" : "test_type",
      "_id" : "test_doc3",
      "_score" : 1.0,
      "_source" : {
        "random" : false,
        "condition" : { },
        "uuid" : "some string"
      }
    } ]
  }
}

**Comment by lmangani** [comment]
I also cannot longer reproduce this on my setup with a nightly build, apparently one of the other issu patches had positive impact on this scenario. Will test deeper and reopen if necessary, thanks!
