### ISSUE TITLE
Not installing properly using the Tar file.

### ISSUE THREAD

**Issue by JafferWilson** [strapdata/elassandra#73]
I have use the Tar method for installing Elassandra. 

after typing the command : `python pylib/setup.py install`
I am getting the following error and do not know how to resolve it:
```
aims@aims:~/elassandra$ sudo python pylib/setup.py install
[sudo] password for aims: 
Traceback (most recent call last):
  File "pylib/setup.py", line 33, in <module>
    ext_modules=get_extensions(),
  File "pylib/setup.py", line 27, in get_extensions
    return cythonize("cqlshlib/copyutil.py")
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Build/Dependencies.py", line 818, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Build/Dependencies.py", line 704, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Build/Dependencies.py", line 108, in nonempty
    raise ValueError(error_msg)
ValueError: 'cqlshlib/copyutil.py' doesn't match any files

```
Kindly, help me with the problem.

**Comment by vroyer** [comment]
Please check that you run python 2.7+ and install the python cassandra driver : 
$ pip install cassandra-driver

**Comment by JafferWilson** [comment]
You can check this:  
```
aims@aims:~$ python --version
Python 2.7.12
aims@aims:~$ pip install cassandra-driver
Requirement already satisfied: cassandra-driver in ./.local/lib/python2.7/site-packages
Requirement already satisfied: futures in ./.local/lib/python2.7/site-packages (from cassandra-driver)
Requirement already satisfied: six>=1.6 in ./.local/lib/python2.7/site-packages (from cassandra-driver)
```
Still I have this problem.

**Comment by vroyer** [comment]
Ok, could you run <elassandra_install_dir>/bin/cqlsh to see if it works correctly ?

**Comment by JafferWilson** [comment]
@vroyer  Is there anyway I can connect with the open source Cassandra instead of the cassandra that came along with elassandra? I recently did a format to my system owing to the cassandra issue, so may after complete confirmation I wil use Elassandra again. Can you let me know whether how I can connect with the seperately installed Cssandra and elasticsearch?

**Comment by JafferWilson** [comment]
@vroyer  Is there anyway I can connect with the open source Cassandra instead of the cassandra that came along with elassandra? I recently did a format to my system owing to the cassandra issue, so may after complete confirmation I wil use Elassandra again. Can you let me know whether how I can connect with the seperately installed Cssandra and elasticsearch?

**Comment by vroyer** [comment]
No, ELassandra it’s not a connector but cassandra + elasticsearch tightly integrated in the same JVM.
But cqlsh from open source cassandra 2.2 is exactly the same as the one provided by elassandra (elassandra = cassandra 2.2 + elasticsearch 2.4), so if open source cassandra can run on your system, elassandra will run too.

**Comment by JafferWilson** [comment]
I do not know what exactly is the problem. Open cassandra work properly. But when I go for Elassandra, the cassandra in it doesn't works. Then if I shift to open Cassandra, the cqlsh is not connecting. That's why I formatted my system previously. I want to make sure that after using elassandra, I do not get any problem again.
The cassandra in the elassandra was also not getting connected too. So I thought i should ask whether the cqlsh is working or not which is in the elassandra.
Kindly, let me know whether it is the problem of the python or not? if yes then where I can get the dependency libraries?

**Comment by vroyer** [comment]
Yes, cqlsh works with elassandra (like cassandra 3.0.10)
$ python --version
Python 2.7.12
$ pip list
...
cassandra-driver (3.5.0)
...
$ cqlsh
Connected to TestCluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.10-SNAPSHOT | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> 

Please post more details about your issue, what's going wrong ?

**Comment by JafferWilson** [comment]
Thank you for your help :)

**Comment by vroyer** [comment]
I hope you solved your issue, otherwise let me know. 
Thanks.
