### ISSUE TITLE
Add support for uuid and timeuuid Cassandra Types

### ISSUE THREAD

**Issue by Zurvarian** [strapdata/elassandra#74]
It would be nice to have support for UUID and TIMEUUID Cassandra types, as for now system fails due to lack of mapping with ES types.
Even basic mapping (Using ES string type) would be welcome.

**Comment by vroyer** [comment]
Elassandra 2.4.2-5 adds supports for uuid and timeuuid mapped to ES string type.

**Comment by Zurvarian** [comment]
Nice! What type is UUID mapped to in ElasticSearch?
Is it possible to check more up to date documentation than: http://elassandra.readthedocs.io/en/latest/mapping.html ?

EDIT: I've tested it myself, and the answer is string type, thanks!

**Comment by vroyer** [comment]
Ok, I have updated the doc.

**Comment by Zurvarian** [comment]
Wow, that was fast, thanks!
