### ISSUE TITLE
Load balancing Kibana requests [Question]

### ISSUE THREAD

**Issue by ccackerman** [strapdata/elassandra#75]
The suggested method for load balancing of Kibana requests (from the documentation):

> If you have multiple nodes in your Elasticsearch cluster, the easiest way to distribute Kibana requests across the nodes is to run an Elasticsearch client node on the same machine as Kibana. 

Is this method supported in Elassandra, i.e. how can I run an Elassandra/Elasticsearch client node in my Elassandra cluster?
If not supported, is there an intention to support this in future, or any other suggested way of accomplishing the same result?

**Comment by vroyer** [comment]
Sorry for this late response. You could likely use HAProxy on your kibana server to achieve http connexion failover to elassandra nodes.

**Comment by ccackerman** [comment]
Good idea. Thanks for your answer and best of luck with this interesting project.
