### ISSUE TITLE
ES Auto-Discovery fails when Cassandra table has at least one UDT field

### ISSUE THREAD

**Issue by Zurvarian** [strapdata/elassandra#77]
In this scenario I'm taking advantage of the bidirectional support of Elassandra, the scenario described below works if you start creating your index in ES first, but fails if starting in Cassandra.

First, we need a keyspace to test the problem:
`CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '1'}  AND durable_writes = true;`

Let's create a UDT type in Cassandra directly:
`create type test.fullname (firstname text, lastname text);`

Then let's create a table with the mentioned type:
`create table test.testudt (id uuid, name frozen<fullname>, primary key (id));`

Then if you try to auto-discover the table in ES:
`curl -XPUT "http://localhost:9200/test/" -d '{   "settings" : { "keyspace" : "test" } }'`
`curl -XPUT "http://localhost:9200/test/_mapping/testudt" -d '{ "testudt" : { "discover" : ".*" } }'`

The outcome is like:
`{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "Expected map for property [fields] on field [index] but got a class java.lang.String"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Expected map for property [fields] on field [index] but got a class java.lang.String"
    },
    "status": 400
}
`

I'm using Elassandra 2.4.2.5 compiled locally, but the same problem I was able to reproduce it in elassandra-2.1.1-18 which tar.gz I download from the releases page (Please, be aware that uuid type won't be supported by ES in that version)

I've been able to avoid this issue by saving the value as a Json serialized String in Java, so this is not really critical issue, it is just annoying.

**Comment by vroyer** [comment]
There is a bug to discover User Defined Types.
This will be fixed and released tomorrow.
Thanks’ for reporting the issue.

**Comment by Zurvarian** [comment]
I've tried the latest released version of elassandra, 2.4.2-6 and it works now, thanks.
I've tested also with collection of udt:

`CREATE TABLE test.testlistofudt (id uuid, name list<frozen<fullname>>, primary key(id));`
`curl -XPUT "http://localhost:9200/test/_mapping/testlistofudt" -d '{ "testlistofudt" : { "discover" : ".*" } }'`

And it works fine.
