### ISSUE TITLE
Possibility of having data-only or index-only nodes ?

### ISSUE THREAD

**Issue by ddorian** [strapdata/elassandra#78]
This will make reading more efficient. You have different number of replicas. Resources will be better utilized (like cpu+ram on es, just ram on cassandra) etc. 

Some kind of queue, where you write to cassandra and it pushes the es-index to another node.
Makes sense ?

**Comment by vroyer** [comment]
You can have cassandra-only datacenters and cassandra+elasticsearch datacenters in the same cassandra cluster to achieve this. Each datacenter can also have its own ES configuration by defining a datacenter.group in elasticsearch.yml. Please see 
[http://doc.elassandra.io/en/latest/configuration.html#multi-datacenter-configuration](http://doc.elassandra.io/en/latest/configuration.html#multi-datacenter-configuration).

**Comment by ddorian** [comment]
I know, but, the 'elassandra' nodes have data+index. While I mean **only** index (like inverted index) nodes. See example like what couchbase does:: https://www.couchbase.com/press-releases/database-scaling-redefined-by-couchbase-multi-dimensional-scaling-outperforms-one-dimensional-scale-limitations-of-oracle-mongodb-and-cassandra (in this case we need only `data` and `index` nodes)

**Comment by vroyer** [comment]
ES indices are built from Cassandra data, each Cassandra datacenters can scale out depending on your needs. If you really want to remove cassandra data, you can close indices, truncate tables, re-open indices, but you won't be able to retrieve fields values...

**Comment by loint** [comment]
thanks for great info from you guys. Love elassandra !

**Comment by ddorian** [comment]
@loint Dude don't hijack threads.
@vroyer I know that. But you know that my question was/is for a more efficient overall system (on search, writing will probably be slower). You think something like that is possible ?

**Comment by vroyer** [comment]
Elassandra was not intended to do that, but to use cassandra as a primary data storage. 
You could drop cassandra data after indexing, but you won’t be able to fetch a document locally (or you will need to store the document _source, which comes with the same cost).

Again, you can have cassandra only datacenters, and some datacenters indexing some keyspaces dedicated to search. Workload separation is achieve with many datacenters.

**Comment by ddorian** [comment]
Workload separation is achieved, but there's still the overhead of the cassandra-data on the search-only nodes. That's what I want to eliminate, but looks like it would need too much dev-time.
