### ISSUE TITLE
Rows in existing table do not get indexed by elasticsearch

### ISSUE THREAD

**Issue by rickysahu** [strapdata/elassandra#79]
If you create a table, add rows to that table, then create the mapping in ES, elasticsearch does not contain the previously added rows in its index. Only those rows added after the creating the mapping are returned in the ES query though all values are present in cassandra. I would expect to have existing rows returned within the ES query. This is problematic because if an ES index or mapping is deleted, there is no way to recreate that without adding all the rows back.  Am I missing some feature that makes this possible?

# Steps to reproduce on build
Tested on elassandra-2.4.2-6

# Add data in through cqlsh
    DROP KEYSPACE IF EXISTS test1;
    CREATE KEYSPACE test1 WITH replication={ 'class':'NetworkTopologyStrategy', 'DC1':'1' };

    CREATE TYPE test1.friend (
      first text,
      last text
    );

    CREATE TABLE test1.user (
      "id" text,
      "username" text,
      "friends" list<FROZEN<friend>>,
      PRIMARY KEY ("username","id")
    );

    INSERT INTO test1.user (
      "id",
      "username",
      "friends"
    ) VALUES (
      'userid',
      'supercooluser',
      [{"first":'jane', "last":'doe'}]
    );

    SELECT * FROM test1.user;

See that the response from the select returns this as expected  

    username      | id     | friends
    ---------------+--------+--------------------------------
    supercooluser | userid | [{first: 'jane', last: 'doe'}]

# Create elasticsearch index
Go back into shell and create the ES index for the user schema

    curl -XPUT "http://localhost:9201/test1" -d '{
      "mappings": {
        "user" : {
          "discover" : ".*"
        }
      }
    }'

See that the index exists
    curl -XGET "http://localhost:9201/test1?pretty=true"

    {
      "test1" : {
        "aliases" : { },
        "mappings" : {
          "user" : {
            "properties" : {
              "friends" : {
                "type" : "nested",
                "cql_udt_name" : "friend",
                "properties" : {
                  "first" : {
                    "type" : "string",
                    "index" : "not_analyzed",
                    "cql_collection" : "singleton"
                  },
                  "last" : {
                    "type" : "string",
                    "index" : "not_analyzed",
                    "cql_collection" : "singleton"
                  }
                }
              },
              "id" : {
                "type" : "string",
                "index" : "not_analyzed",
                "cql_collection" : "singleton",
                "cql_primary_key_order" : 1
              },
              "username" : {
                "type" : "string",
                "index" : "not_analyzed",
                "cql_collection" : "singleton",
                "cql_partition_key" : true,
                "cql_primary_key_order" : 0
              }
            }
          }
        },
        "settings" : {
          "index" : {
            "creation_date" : "1486556821833",
            "number_of_shards" : "1",
            "number_of_replicas" : "0",
            "uuid" : "DRz75QBIQROsLkcBwTNlsw",
            "version" : {
              "created" : "2040299"
            }
          }
        },
        "warmers" : { }
      }
    }

Attempt a query for the object

    curl -XGET 'http://localhost:9201/test1/_search?pretty=true' -d '
    {
        "query" : {
          matchAll: {}
        }
    }'

See that no hits are returned. We would expect that supercooluser would be in the response.  

    {
      "took" : 3,
      "timed_out" : false,
      "_shards" : {
        "total" : 1,
        "successful" : 1,
        "failed" : 0
      },
      "hits" : {
        "total" : 0,
        "max_score" : null,
        "hits" : [ ]
      }
    }

# Try query with new user

Go back into cqlsh and add another document

    INSERT INTO test1.user (
      "id",
      "username",
      "friends"
    ) VALUES (
      'newuserid',
      'newusername',
      [{"first":'newjane', "last":'newdoe'}]
    );

    SELECT * FROM test1.user;

See that the response from the select returns both users as expected  

    username      | id        | friends
    ---------------+-----------+--------------------------------------
      newusername | newuserid | [{first: 'newjane', last: 'newdoe'}]
    supercooluser |    userid |       [{first: 'jane', last: 'doe'}]

Go back to shell and query elasticsearch again

    curl -XGET 'http://localhost:9201/test1/_search?pretty=true' -d '
    {
        "query" : {
          matchAll: {}
        }
    }'

See that we get the new user but not the first one we created before making the elasticsearch index.

    {
      "took" : 5,
      "timed_out" : false,
      "_shards" : {
        "total" : 1,
        "successful" : 1,
        "failed" : 0
      },
      "hits" : {
        "total" : 1,
        "max_score" : 1.0,
        "hits" : [ {
          "_index" : "test1",
          "_type" : "user",
          "_id" : "[\"newusername\",\"newuserid\"]",
          "_score" : 1.0,
          "_source" : {
            "id" : "newuserid",
            "friends" : {
              "last" : "newdoe",
              "first" : "newjane"
            },
            "username" : "newusername"
          }
        } ]
      }
    }

Try to rebuild the index
`./elassandra-2.4.2-6/bin/nodetool rebuild_index test1 user elastic_test1_user_idx`  

Running query again still shows only the new user

**Comment by vroyer** [comment]
Thanks for all the details.
Cassandra index build and rebuild rely on the Compaction Manager. Unfortunately, it only indexes SSTables, that means non-flushed data are not indexed when creating the ES index and even when rebuilding the index. If you flush (nodetool flush test1) before creating or rebuilding your index, it should work properly.

**Comment by rickysahu** [comment]
thanks for the response. i actually found that the issue is that i used incorrect index names. the indexes created are as follows. 
```
select * from system."IndexInfo" where table_name = 'test1' limit;
 table_name | index_name
------------+--------------------------
      test1 | elastic_user_friends_idx
      test1 |      elastic_user_id_idx
```

rebuilding those fixes the issue.

**Comment by pramodShehan5** [comment]
Hi,

If there are data in memTable and at this point, there aren't elasticsearch index. when I create index when cassandra data is in memTable, those memTable data are indexed.

is this a possible scenario in latest elassandra version?
