### ISSUE TITLE
Frozen Columns

### ISSUE THREAD

**Issue by ChrisFeldmeier** [strapdata/elassandra#8]
Why all columns are frozen columns and not only the data type?

**Comment by ChrisFeldmeier** [comment]
?

**Comment by vroyer** [comment]
By default, elasticsearch document field are multivalued, so each document field of type X is mapped to a cassandra column of type list<X> (where X is a native type string, int, long etc...).

If you want to map field of type X directly to a cassandra column of type X, set the mapping attribute cql_collection to singleton. For example,
curl -XPUT "http://$NODE:9200/twitter/_mapping/tweet3" -d '{
            "properties" : {
              "size" : {
                "type" : "long",
                "cql_collection":"singleton"
              },
              "post_date" : {
                "format" : "strict_date_optional_time||epoch_millis",
                "type" : "date",
                "cql_collection":"singleton"
              },
              "message" : {
                "type" : "string",
                "cql_collection":"singleton"
              },
              "user" : {
                "type" : "string",
                "cql_collection":"singleton"

```
          }
        }
```

}'

# create the following cassandra table.

CREATE TABLE twitter.tweet3 (
    "_id" text PRIMARY KEY,
    message text,
    post_date timestamp,
    size bigint,
    user text
)

If you want to map field of type X to a unique list of values (a set), set cql_collection to "set".

Does this answer your question ?

**Comment by ChrisFeldmeier** [comment]
yeahh cool thanks :+1:
