### ISSUE TITLE
columns declared as list get returned as scalar / mapped value  when only one item in list

### ISSUE THREAD

**Issue by rickysahu** [strapdata/elassandra#80]
When an row using a list containing single instance of a user defined type is returned, it is represented as a scalar rather than a list as would be expected. 

# Steps to reproduce
Tested on elassandra-2.4.2-6
  ```
    DROP KEYSPACE IF EXISTS test1;
    CREATE KEYSPACE test1 WITH replication={ 'class':'NetworkTopologyStrategy', 'DC1':'1' };

    CREATE TYPE test1.friend (
      first text,
      last text
    );

    CREATE TABLE test1.user (
      "_id" text,
      "username" text,
      "friends" list<FROZEN<friend>>,
      PRIMARY KEY ("username","_id")
    );

```

Add the mapping
```
    curl -XPUT "http://localhost:9200/test1" -d '{
      "mappings": {
        "user" : {
          "discover" : ".*"
        }
      }
    }'
```
Add a result in cassandra
```
    INSERT INTO test1.user (
      "_id",
      "username",
      "friends"
    ) VALUES (
      'supercooluseruserid',
      'supercooluser',
      [{"first":'jane', "last":'doe'}]
    );

    SELECT * FROM test1.user;

    username      | id     | friends
    ---------------+--------+--------------------------------
    supercooluser | userid | [{first: 'jane', last: 'doe'}]
```
# Result
Querying ES gives us this.
```
curl -XGET 'http://localhost:9200/test1/_search?pretty=true' -d ' {"query" : {matchAll: {}}}'

{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test1",
      "_type" : "user",
      "_id" : "[\"supercooluser\",\"supercooluseruserid\"]",
      "_score" : 1.0,
      "_source" : {
        "friends" : {
          "last" : "doe",
          "first" : "jane"
        },
        "username" : "supercooluser"
      }
    } ]
  }
}
```
See that the returned value for friends is   
`"friends" : {"last" : "doe", "first" : "jane"}`
Expected result should have an array as friends  
`"friends" : [ {"last" : "doe", "first" : "jane"} ]`

If a row with multiple friends is entered, that _source has the correct array representation

**Comment by rickysahu** [comment]
It seems that there's an underlying problem with how ES defaults to list objects and cass is singleton. So the `values[idx] = (list.size() == 1) ? list.get(0) : list;` line creates problems when only one item is in the list. This probalby isnt just an issue for UDT, but also list<text> or another like that. 

It looks like we need to make 2 changes. The first is to ensure cql_collection = list when cql_udt_name is set. The second is to maintain a list type if an indexed value only contains one element and the mapping is of  cql_collection = list (after fixing the first issue).

1. The discovered mapping should include a `cql_collection: list` at the friends level. Currently there is no cql_collection value of `list` for the friends mapping even though we used `"friends" list<FROZEN<friend>>`. The default may need to be changed to singleton, and apply list only when declared in the schema definition:
```
curl -XPUT "http://localhost:9200/test1" -d '{"mappings": {"user" : {"discover" : ".*"}}}'
{"acknowledged":true}
curl -XGET "http://localhost:9200/test1?pretty=true"
{
  "test1" : {
    "aliases" : { },
    "mappings" : {
      "user" : {
        "properties" : {
          "friends" : {
            "type" : "nested",
            "cql_udt_name" : "friend",
            "properties" : {
              "first" : {
                "type" : "string",
                "index" : "not_analyzed",
                "cql_collection" : "singleton"
              },
              "last" : {
                "type" : "string",
                "index" : "not_analyzed",
                "cql_collection" : "singleton"
              }
            }
          },
          "id" : {
            "type" : "string",
            "index" : "not_analyzed",
            "cql_collection" : "singleton",
            "cql_primary_key_order" : 1
          },
          "username" : {
            "type" : "string",
            "index" : "not_analyzed",
            "cql_collection" : "singleton",
            "cql_partition_key" : true,
            "cql_primary_key_order" : 0
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1486902946377",
        "number_of_shards" : "1",
        "number_of_replicas" : "0",
        "uuid" : "KcI_dzcoTx-4MkgNdY8IsA",
        "version" : {
          "created" : "2040299"
        }
      }
    },
    "warmers" : { }
  }
}
```
For that we must update the mapping creation when its a UDT to use a cql_collection: list specifically, instead of by default when the column is of a list type.  
https://github.com/strapdata/elassandra/blob/ebe59a4dc2099d962ddc253f29e729d2877b7a33/core/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L254


2. Honor the cql_colllection = list value from the mapping when indexing an item. It seems that we need to check if the mapping type is a list here before we convert the value to the first element of the list. Again since the default is currently a list, we may need to change the way defaults are treated:  
https://github.com/strapdata/elassandra/blob/fb54de6d1ddf5ef7d2ee84d0656b51d150050e7b/core/src/main/java/org/elassandra/index/ElasticSecondaryIndex.java#L1421  
and in here: core/src/main/java/org/elassandra/cluster/InternalCassandraClusterService.java

**Comment by vroyer** [comment]
The issue is not clear for me, because `cql_collection: list` is the default mapping, so not displayed unless you request to display defaults. So cql_collection is displayed only when it's singleton or set. 

Moreover, for Elasticsearch, every field is multi-valued (stored as a list in cassandra by default), but indexing a singleton or many values is the same, https://github.com/strapdata/elassandra/blob/fb54de6d1ddf5ef7d2ee84d0656b51d150050e7b/core/src/main/java/org/elassandra/index/ElasticSecondaryIndex.java#L1421 is just a shortcuts, see line https://github.com/strapdata/elassandra/blob/fb54de6d1ddf5ef7d2ee84d0656b51d150050e7b/core/src/main/java/org/elassandra/index/ElasticSecondaryIndex.java#L383.

**Comment by rickysahu** [comment]
This line (ElasticSecondaryIndex.java#L1421) seems to say, if the list only has one item, index it by the first (and only value) rather than the whole list. It works for querying, but when the value is returned documents do not have a consistent structure.

See the difference here where one row has 2 items in the friends list, and another row only has one item. The result where 2 items are in friends is correctly returned as an array, and the one with only one item is not. The inconsistent structure creates issues downstream.
```
{
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test1",
      "_type" : "user",
      "_id" : "[\"supercooluser2\",\"supercooluseruserid1\"]",
      "_score" : 1.0,
      "_source" : {
        "id" : "supercooluseruserid1",

        "friends" : {
          "last" : "doe",
          "first" : "jane"
        },

        "username" : "supercooluser2"
      }
    }, {
      "_index" : "test1",
      "_type" : "user",
      "_id" : "[\"secondusername\",\"secondid\"]",
      "_score" : 1.0,
      "_source" : {
        "id" : "secondid",

        "friends" : [ {
          "last" : "doe",
          "first" : "jane"
        }, {
          "last" : "d",
          "first" : "j"
        } ],

        "username" : "secondusername"
      }
    } ]
  }
}
```


How would i alter the ES query to return the value for friends as a list rather than the first value of the embeded list?

**Comment by vroyer** [comment]
This is the regular behavior of Elasticsearch, when a field has only one value, there is no surrounding square brackets.

Tested with Elasticsearch 2.4.1:
curl -XPUT "http://localhost:9200/test1/user/supercooluseruserid1" -d'{
    "friends" : {
          "last" : "doe",
          "first" : "jane"
        },

        "username" : "supercooluser2"
}'
curl -XPUT "http://localhost:9200/test1/user/secondid" -d'{
    "friends" : [ {
          "last" : "doe",
          "first" : "jane"
        }, {
          "last" : "d",
          "first" : "j"
        } ],
        "username" : "secondusername"
}'

curl -XGET "http://localhost:9200/test1/_search?pretty"
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test1",
      "_type" : "user",
      "_id" : "supercooluseruserid1",
      "_score" : 1.0,
      "_source" : {
        "friends" : {
          "last" : "doe",
          "first" : "jane"
        },
        "username" : "supercooluser2"
      }
    }, {
      "_index" : "test1",
      "_type" : "user",
      "_id" : "secondid",
      "_score" : 1.0,
      "_source" : {
        "friends" : [ {
          "last" : "doe",
          "first" : "jane"
        }, {
          "last" : "d",
          "first" : "j"
        } ],
        "username" : "secondusername"
      }
    } ]
  }
}

**Comment by rickysahu** [comment]
Ah thanks for clarifying that (and for this repo in general). I was able to change this in a forked version, but i see that it wouldnt make sense to alter that in the core since that's native ES.
