### ISSUE TITLE
ClassCastException when creating a Document in ES if partition key of Cassandra table is UUID

### ISSUE THREAD

**Issue by Zurvarian** [strapdata/elassandra#81]
I've found an issue when trying to create a Document through ES API if the the Partition Columns of the Cassandra's table is of UUID type.
This error cannot be reproduced if the Document is created through Cassandra API (i.e.: By inserting the data using CQL), neither if the column with UUID type is not the partition column. I didn't check if the error happens also if the column is one of the clustering columns, though.

I'm using version 2.4.2-6 of Elassandra.

This is how to reproduce the issue:

Create keyspace and tables, one with UUID type for Partition key and the other without (To allow comparison)
`CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '1'}  AND durable_writes = true;`
`create table test.pk_uuid (pk_uuid uuid, column_not_uuid text, primary key(pk_uuid));
`create table test.pk_not_uuid (pk_not_uuid text, column_uuid uuid, primary key(pk_not_uuid));`

Insert data into both tables to demonstrate that it works:
`insert into test.pk_uuid (pk_uuid , column_not_uuid ) VALUES ( uuid(), 'a value');`
`insert into test.pk_not_uuid (pk_not_uuid , column_uuid ) VALUES ( 'pk', uuid());`

Define ES index and types:
`curl -XPUT "http://localhost:9200/test/" -d '{ "settings" : { "keyspace" : "test" } }'`
`curl -XPUT "http://localhost:9200/test/_mapping/pk_uuid" -d '{ "pk_uuid" : { "discover" : ".*" } }'`
`curl -XPUT "http://localhost:9200/test/_mapping/pk_not_uuid" -d '{ "pk_not_uuid" : { "discover" : ".*" } }'`

Try to create the document for the type with UUID as Partition Key:
`curl -XPUT "http://localhost:9200/test/pk_uuid/bacc6c75-91b8-4a86-a408-ff7bafac535d" -d '{
                     "column_not_uuid": "a value",
                     "pk_uuid": "bacc6c75-91b8-4a86-a408-ff7bafac535d"
                     }'`

This is the error that it returns:
`{"error":{"root_cause":[{"type":"class_cast_exception","reason":"java.lang.String cannot be cast to java.util.UUID"}],"type":"class_cast_exception","reason":"java.lang.String cannot be cast to java.util.UUID"},"status":500}`

Now, if you try with the other type:
`curl -XPUT "http://localhost:9200/test/pk_not_uuid/bacc6c75-91b8-4a86-a408-ff7bafac535d" -d '{
                     "column_uuid": "bacc6c75-91b8-4a86-a408-ff7bafac535d",
                     "pk_not_uuid": "pk2"
                     }'`

It works:
`{"_index":"test","_type":"pk_not_uuid","_id":"bacc6c75-91b8-4a86-a408-ff7bafac535d","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}`

**Comment by vroyer** [comment]
Thanks for reporting the issue. 
It is now fixed in 2.4.2-8 and your test included in unit tests (see org.elassandra.CqlTypesTests).

**Comment by Zurvarian** [comment]
Thanks for the quick response, but unfortunately I still can reproduce the issue.
I've downloaded the last release from releases page and install it into a clean environment (i.e.: Just unpack the tar.gz and run elassandra, without any config file changed) and follow the steps I described in the issue, and still got the same results.

On the other hand, I've updated the original comment to amend new lines mess and to fix the name of the DC, as it was a custom one and wouldn't work with out-of-the-box elassandra.

**Comment by vroyer** [comment]
You're right, there still an issue with this specific case, when a field overwrite the _id given in the URL (pk_not_uuid:pk2).

`curl -XPUT "http://localhost:9200/test/pk_not_uuid/bacc6c75-91b8-4a86-a408-ff7bafac535d" -d '{ "column_uuid": "bacc6c75-91b8-4a86-a408-ff7bafac535d", "pk_not_uuid": "pk2" }'`

I have committed a fix for the ClassCastException, but overwriting the _id like this could be confusing.

**Comment by Zurvarian** [comment]
I agree with you, I'm going to check if the ES client we are using can avoid that situation (I'm using Spring's ES Template)
Thanks for the extra work.
