### ISSUE TITLE
Not able to use search query 

### ISSUE THREAD

**Issue by mohita-4** [strapdata/elassandra#84]
i)I have been able to view the data stored in keyspace, after mapping in elasticsearch only by using -XGET on individual documents. No hits are returned on search.
ii) No hits even when i directly index documents in an index  and search the index , even when the the documents are visible in the cassandra keyspace
Would be grateful, if could have any leads.

**Comment by vroyer** [comment]
Hi,
Could you post some details about your test (version used, cluster state, CQL schema, search request and result) ?

**Comment by mohita-4** [comment]
Using  Elassandra version 2.4.2

![image](https://cloud.githubusercontent.com/assets/26269819/23698377/58930a0c-0411-11e7-91f1-030a1c5077d9.png)



Use cassa;
CREATE TABLE user (name text,attrs text,value text,PRIMARY KEY (name));
![image](https://cloud.githubusercontent.com/assets/26269819/23698002/f3649ae8-040f-11e7-972a-f27f30c8e59c.png)

 curl -XPUT "http://localhost:9200/cassa"
curl -XPUT "http://localhost:9200/cassa/_mapping/user" -d '{ "user" : { "discover" : ".*" }}'
![image](https://cloud.githubusercontent.com/assets/26269819/23698325/318bcebc-0411-11e7-8f5a-c0ad8db19906.png)

![image](https://cloud.githubusercontent.com/assets/26269819/23698474/b3c4a7c8-0411-11e7-9796-3400ea7bb510.png)

![image](https://cloud.githubusercontent.com/assets/26269819/23698527/eb1ba41a-0411-11e7-93ea-5146cd69bd82.png)

 
curl -XGET "http://localhost:9200/_cluster/state?pretty"
{
  "cluster_name" : "TestCluster",
  "version" : 8,
  "state_uuid" : "R0WWcf6ASo2Q6Kv_xC-Xpw",
  "master_node" : "daf57647-4d19-4946-8d8d-e0b7401ffb59",
  "blocks" : { },
  "nodes" : {
    "daf57647-4d19-4946-8d8d-e0b7401ffb59" : {
      "name" : "127.0.0.1",
      "status" : "ALIVE",
      "transport_address" : "127.0.0.1:9300",
      "attributes" : {
        "rack" : "r1",
        "data" : "true",
        "data_center" : "DC1",
        "master" : "true"    }   }
  },
  "metadata" : {
    "version" : 13,
    "cluster_uuid" : "daf57647-4d19-4946-8d8d-e0b7401ffb59",
    "templates" : { },
    "indices" : {
      "cassa" : {
        "state" : "open",
        "settings" : {
          "index" : {
            "creation_date" : "1488964500696",
            "number_of_shards" : "1",
            "number_of_replicas" : "2",
            "uuid" : "US2Gt8AGTxa8Cn9oMAVElQ",
            "version" : {
              "created" : "2040299"
            }
          }
        },
        "mappings" : {
          "user" : {
            "properties" : {
              "name" : {
                "index" : "not_analyzed",
                "cql_partition_key" : true,
                "cql_primary_key_order" : 0,
                "type" : "string",
                "cql_collection" : "singleton"
              },
              "value" : {
                "index" : "not_analyzed",
                "type" : "string",
                "cql_collection" : "singleton"
              },
              "attrs" : {
                "index" : "not_analyzed",
                "type" : "string",
                "cql_collection" : "singleton"
              }
            }
          }
        },
        "aliases" : [ ]
      }
    }
  },
  "routing_table" : {
    "indices" : {
      "cassa" : {
        "shards" : {
          "0" : [ {
            "state" : "STARTED",
            "primary" : true,
            "node" : "daf57647-4d19-4946-8d8d-e0b7401ffb59",
            "relocating_node" : null,
            "shard" : 0,
            "index" : "cassa",
            "version" : 8,
            "token_ranges" : [ "(-9223372036854775808,9223372036854775807]" ],
            "allocation_id" : {
              "id" : "HR_plndwQ4qFqIpqk0f4lg"
            }
          } ]
        }
      }
    }
  },
  "routing_nodes" : {
    "unassigned" : [ ],
    "nodes" : {
      "daf57647-4d19-4946-8d8d-e0b7401ffb59" : [ {
        "state" : "STARTED",
        "primary" : true,
        "node" : "daf57647-4d19-4946-8d8d-e0b7401ffb59",
        "relocating_node" : null,
        "shard" : 0,
        "index" : "cassa",
        "version" : 8,
        "token_ranges" : [ "(-9223372036854775808,9223372036854775807]" ],
        "allocation_id" : {
          "id" : "HR_plndwQ4qFqIpqk0f4lg"
        }
      } ]
    }
  }
}

**Comment by vroyer** [comment]
Well, you have discovered the CQL schema of a small existing C* table. This triggers an index_rebuild  on SSTables (not MemTables), but  your small table is not yet flushed on SSTable, so your ES index is empty (indices reports doc.count=0). To solve this, you can 
1 - re-insert your data into cassandra, or
2 - flush (nodetool flush user) and rebuild index (nodetool rebuild_index test elastic_attrs_idx), or
3 - delete your index, flush, discover the table to build the index.

Hope this help.

**Comment by mohita-4** [comment]
Hi, thanks for the response and suggestions. I tried the above methods but still the doc counts remains 0.
1) Tried adding an extra row in keyspace 
2)used ./nodetool flush keyspace tablename and then ./nodetool rebuild_index keyspace tablename elastic_attrs_idx but yet documents were not searchable
3)Deleted the index flushed, created a mapping to discover and searched
I even tried creating the cassandra schema, then put the mapping( with discover option) and then inserted rows, but the same issue persists.
Is there anything that could be missing in configeration files/cluster settings etc./ or would there anything be wrong with commands or sequence of steps?
Please help, if possible.

Thanks!

**Comment by vroyer** [comment]
Ok, could provide your CQL schema to check that secondary index are created ?
Could you check your logs for error or warn messaged (in logs/system.logs) ?
