### ISSUE TITLE
Considerations when changing cql_collection

### ISSUE THREAD

**Issue by emuplz** [strapdata/elassandra#85]
Hi,

I have an urge to map the majority of my fields with `cql_collection: "singleton"`, but I'm guessing `list` is the default for a reason.

What are the considerations when mapping them as a `singleton`?

**Comment by emuplz** [comment]
Apologies, after a bit of reading, I understand that elastic search can index things as multi-fields; each field being indexed in a different way. 

But still, what is the benefit of inserting the data like this into cassandra?

**Comment by vroyer** [comment]
For elasticsearch, all fields are multi-valued, so backed by a list<X> in a Cassandra table.
If you want to index an existing Cassandra table having a text column for exemple, cql_collection=singleton just says that the field is mono-valued.
