### ISSUE TITLE
query matchAll doesn't return any result in 2.4.2-10

### ISSUE THREAD

**Issue by towies** [strapdata/elassandra#86]
I did the same test in both versions: 2.4.2-6 and 2.4.2-10. In the first one I get the results expected however in the second I retrieve nothing (no records). 
The step followed was:
1. Unpack elassandra, set CASSANDRA_HOME env variable, run aliases.sh and check right status
2. Create keyspace and table using cqlsh command line.
3. Create index on the keyspace with discover: `curl -XPUT "http://localhost:9200/<INDEXNAME>/" -d '{   "settings" : { "keyspace" : "<KEYSPACENAME>" } }' `
4. Create a mapping with discover: `curl -XPUT "http://localhost:9200/<INDEXNAME>/_mapping/<MAPPING>" -d '{ "<TABLENAME>" : { "discover" : ".*" }}'`

Both commands returns: `{"acknowledged":true}`

5. Insert data into the database using cqlsh: `INSERT INTO ...`
6. Query all documents (even query for full index) : ` curl -XGET 'http://localhost:9200/<INDEXNAME>/_search?pretty=true' -d '
{
    "query" : {
        "matchAll" : {}
    }
}'`

7. At that point the version 2.4.2-6 shows all records/documents previously stored in the database. However version 2.4.2-10 **doesn't show results**  Is it this behavior expected?

**Comment by vroyer** [comment]
Sorry, due to a small bug, version 2.4.2-10 was indexing only when logging in debug mode.
Please install the fixed release 2.4.2-11.
Thanks'.

**Comment by towies** [comment]
Good to know. I cannot try the new version because I'm getting error when I try compile source code in  Maven Javassist Plugin Core.

**Comment by loint** [comment]
Thanks guys, we had same issue !
