### ISSUE TITLE
Unable query null values from elasticsearch in elassandra 2.4.2-6

### ISSUE THREAD

**Issue by towies** [strapdata/elassandra#87]
I'm using currently elassandra 2.4.2-6 and I cannot build a query to retrieve documents which *have a property with null value* I means, the document in elasticsearch which has not a property. 

I tried several approach suggested by elasticsearch's documentation 
* exists query
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-exists-query.html
*  null_value (set a value by default if the data is null) 
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/null-value.html

However in both cases I get no results data. Any suggestion?
I try the same queries in Elasticsearch 2.1.1 and they work fine.

**Comment by vroyer** [comment]
I take the point to find a solution.

**Comment by vroyer** [comment]
This is fixed in release 2.4.2-12, but due to C* internal behavior, empty array are considered as null where Elasticsearch makes a difference between empty arrays and null values.
