### ISSUE TITLE
Upgrade to Elastic 5.x

### ISSUE THREAD

**Issue by tsindot** [strapdata/elassandra#88]
Are there plans to upgrade from the 2.4.x version of Elastic to 5.x version?  If so any timeframe on this ?

Thanks.

**Comment by loint** [comment]
+1

**Comment by vroyer** [comment]
This is in the pipe, for June 2017.

**Comment by loint** [comment]
@vroyer Thanks for your hard work on it, many new features are coming !!!

**Comment by tsindot** [comment]
@vroyer Excellent, thanks for the update.

**Comment by NanXiangPU** [comment]
What's the progress of upgrading elassandra to elasticsearch 5.X? We are currently adapting our cassandra database to elasticsearch and found this tool. But we cannot use kibana 5 with newest version of elassandra and with kibana 4, there are some mapping problems,

**Comment by vroyer** [comment]
Migration to ES 5.5 is currently under development, it should be available in August 2017.

**Comment by boycode** [comment]
@vroyer  👍  Great to hear that !

**Comment by zcourts** [comment]
Elassandra currently maps index to keyspace and types to tables, what will the new mappings be given that types are being removed in https://github.com/elastic/elasticsearch/issues/15613? Designing upgrade to our app and wanted to use elassandra but unclear what direction will be taken on this and don't want to have to redesign/rebuild after barely 1 month any insight into the dev plan here would be useful. Is dev far enough along to start playing with, even if some stuff's broken would love to play with it/test.

**Comment by vroyer** [comment]
Hi, 

For the current 5.x, document type is still supported.
In the futur releases, if you still need to index many tables in the same ES index, it would just require a sepcific mapping from the document _id to the backing C* table to store and fetch. 
This  will be customizable with a kind of function String idToTable(String _id) stored in the ES mapping.

Thanks.

**Comment by xycloud** [comment]
Hi experts: 
    any progress about playing with es 5.x

**Comment by vroyer** [comment]
HI,
Yes, its almost ready, integration tests and packaging are on going. 
It should be available within the next week.
Thanks.

**Comment by loint** [comment]
Good to hear that man. Thanks for your great efforts !

**Comment by thelordoftheboards** [comment]
@vroyer Thank you for sharing elassandra with the open source community and all the upgrades.

**Comment by porlock** [comment]
Hi, any news about this topic :) ?

**Comment by vroyer** [comment]
Here it is !
I just release Elassandra 5.5.0.0 based on Elasticsearch 5.5.0 + Cassandra 3.11.0.
It works with kibana 5.5.
Cheers.

**Comment by xycloud** [comment]
do we have docker image for 5.x?

**Comment by DBarthe** [comment]
@xycloud you can pull `strapdata/elassandra:5.5.0.0-beta1` from docker hub
Dockerfile and documentation is here : https://github.com/strapdata/docker-elassandra

**Comment by vroyer** [comment]
Cool, merci Barthelemy.
Il y aura bientôt une beta 2, pour enrichir le monitoring JMX.

Cldt,
Vincent.

**Comment by porlock** [comment]
where i can find a rpm or tarball of version 5.5 ?
