### ISSUE TITLE
Dockerfile for Elassandra image

### ISSUE THREAD

**Issue by loint** [strapdata/elassandra#89]
Hi guys,

Do you have Dockerfile for this image xawcourmont/elassandra ? Because I would like to modify it and run in our production with our Kubernetes. Any experience or recommendation about it will be welcome.

Thanks in advanced.

**Comment by vroyer** [comment]
I can't join the author of this docker image right now, but we are going to build and release up-to-date docker images in the next few weeks.

**Comment by loint** [comment]
Cool, great news !
Thanks man.

**Comment by DBarthe** [comment]
Hello @loint,

You'll find a new docker image for elassandra on [docker hub](https://hub.docker.com/r/strapdata/elassandra/).
The *Dockerfile* is in the repository [strapdata/docker-elassandra](https://github.com/strapdata/docker-elassandra).

I hope it's a good starting point for your use case.

**Comment by loint** [comment]
thanks for great contribution @DBarthe
