### ISSUE TITLE
Cannot create index pattern in Kibana (cluster setup)

### ISSUE THREAD

**Issue by sergiomr88** [strapdata/elassandra#9]
Has anyone else experienced any problems while setting up Kibana 4.3 while having multiple nodes?
When using elassandra with just a single node, I'm able to setup the index pattern and see my data in Kibana as it's being loaded. However, when I try to do the same thing with several nodes, I cannot create the index (Kibana is able to find the index and recognize the Time-field name, however it doesn't do anything when I click create).

Additionally, online it is posted that I should use the sed command as:

sed -i .bak -e "s/type: ${q}index-pattern${q}/type: ${q}index_pattern${q}/g" -e "s/type = ${q}index-pattern${q}/type = ${q}index_pattern${q}/g" -e "s%${q}index-pattern${q}: ${q}/settings/objects/savedSearches/${q}%${q}index_pattern${q}: ${q}/settings/objects/savedSearches/${q}%g" optimize/bundles/kibana.bundle.js src/ui/public/index_patterns/_.js src/ui/public/index_patterns/_.js

src/ui/public/index_patterns/*.js is repeated twice. In order to get kibana working on a single node, I also used sed on src/plugins/kibana/public/discover/controllers/discover.js. 

Note: I'm using elassandra 2.1.1

**Comment by vroyer** [comment]
src/ui/public/index_patterns/*.js is repeated twice, it's an error with no impact on your issue.
I did not reproduce your issue with release 2.1.1-4, could you try to reload your page after clicking "create", or restart your nodes. Did you get any WARN or ERROR message in your logs ?

**Comment by sergiomr88** [comment]
Thanks for the reply. I got no error messages. I just get a timeout message from kibana and eventually the node goes down. I'm using elassandra version 2.1.1 built on red hat (Commit 454293e). I will test it with the latest release and see if it works.

**Comment by sergiomr88** [comment]
Using the latest release, kibana works. However I have to reload the page like you said.

Update: With the older version of elassandra, kibana works too. The problem is that with multiple nodes you have to refresh the page by yourself (with a single node, the normal behavior occurs, which is that the page refreshes automatically). I think the crash was being caused because I was hitting the create button more than once when I was not seeing any updates.

However now I have two problems. If I use the newest release, most of my test insertions seem to timeout. I have a test program doing one million insertions, and with the old elassandra version, I'm able to insert the million records without a sweat. However with elassandra 2.1.1-4 only around 90,000 insertions succeed.

Using the older version of elassandra, I can insert several batches of 1 million records and get the counts with elastic search. However, when I install kibana, the performance degrades with each batch. So in each batch, more and more inserts will time out until eventually one of the node crashes.

**Comment by vroyer** [comment]
Which older version were you using to insert several million records ?
You could try with the very last one, 2.1.1-5, it fixes an issue when inserting columns that are not indexed by elasticsearch. Obviously, inserting in both cassandra and elasticsearch would be slower that inserting in cassandra, (index updates are synchronous to cassandra inserts) but you can check these points : 
-Add some RAM to you JVM (20Go more for example).
-Locate Elasticsearch indices on a dedicated disk to reduce IO contention.
-Only index cassandra columns on which you need to search.

**Comment by sergiomr88** [comment]
I cloned the repository and was using commit 454293e. 

Yes inserting with elastic search on is slower than just cassandra, but that was something expected. However the performance is already good for me. The problem I have is that with Kibana on, the performance degrades over time. So the first time I may be able to insert 900,000 records, the next run only 400,000, and at the end it gets to a point where I can only insert 50 records per 1 million. This behavior doesn't happen when I don't use kibana. I can do the 1 million inserts constantly without this decreased performance on each iteration. I also know that the records are being indexed, since I do the overall count using elastic search with curl. 

As for the new version (2.1.1-4), the problem is that most of the inserts time out (just cassandra with ES). I can try during the weekend to use the latest release, but I'm still puzzled about my problem.

**Comment by vroyer** [comment]
Please use the very last release 2.1.1-6, it fixes a bug on refresh operations periodically sent by kibana.

**Comment by sergiomr88** [comment]
Just tried release 2.1.1-6, but now I have the same problem I've been having with newer releases. While trying to do the 1 million inserts, most of my insertions timed out. 

With elassandra 2.1.1 I was getting around 990,000 - 1,000,000 from 1,000,000 insertions with an average time of 200 seconds. With elassandra 2.1.1-6 I'm getting around 125,000 from 1,000,000 insertions with an average time of 400 seconds.

As a point of reference: Cassandra without elastic search is doing the 1 million inserts in around 90 seconds. All the tests until now have been done without using replication.

On the other side, I am no longer experiencing any problems while creating indexes in kibana.

**Comment by vroyer** [comment]
Hi,

I have inserted 1M rows with 80 columns on cassandra (without ElasticSecondaryIndex) in 92s on a 2 nodes cluster (10800 inserts/s with 64 threads, C\* driver using cached preparedStatement, Elassandra logging set to WARN in conf/logback.xml).

The same test with elasticsearch activated (with ElasticSecondaryIndex):
-insert in an empty table/index => 175s (5700 inserts/s)
-insert in the existing table/index involving lucene segment updates => 189s (5283 inserts/s)

Of course, this is slower but this is the cost of indexing.
So, any information about your issue is welcome.

**Comment by sergiomr88** [comment]
Thanks again for the reply. Your results seem similar to the results I was having with the older version of elassandra. With no indexing, my  3 node cluster would be able to handle around 15,000 inserts per second and with indexing between 3500 - 5000 inserts per second. 

My guess right now is that the problem is a configuration issue. However, I have used the same settings on cassandra.yaml, cassandra-env.sh, and elasticsearch.yml, and the problem is still there. Are there any other files I need to check when setting up the configuration settings?

As for my insertions, each row has 30 columns. All the fields are being indexed and not analyzed. I also have a timestamp field which I'm using in kibana for the time-based events feature. 

Additionally I'm reading the result after each insertion to check if the insert was successful. If I remove the read check, then I don't get any timeouts, but the insertions work pretty slowly and eventually I get an OutOfMemoryError: GC overhead limit exceeded. (Removing the read check on the older version didn't cause the out of memory error).

**Comment by vroyer** [comment]
No special configuration required except enough RAM for your JVM.
Could you share your injection code and your schema to reproduce the issue ?

**Comment by sergiomr88** [comment]
Did you get my insertions code? Did you manage to reproduce the problem?
And one unrelated question, does elassandra work if you have static columns in cassandra?

**Comment by vroyer** [comment]
So, sorry i don't get your insertion code. Did you post it ?

You cannot set a secondary index on static columns before cassandra version 3.4 (see CASSANDRA-8103). Elassandra is currently based on cassandra 2.2.4, so you can use some, but it cannot be indexed in elasticsearch.

**Comment by vroyer** [comment]
Hi,
I fix a bug in the last release 2.1.1-8 that was causing some write timeout due to a mapping issue.
Maybe this could fix your issue.
Thanks'.
