### ISSUE TITLE
ElasticSearch mapping index hangs without results

### ISSUE THREAD

**Issue by loint** [strapdata/elassandra#90]
I'm using the latest source code from v2.4.2-11. Cassandra cluster is fine. Schema is created and I'm able to insert a huge of records.

But when I'm trying to create db in Elastic Search, the PUT request hangs. Search structure is created but no results is returned.

How can I debug to identify it's a bug from Elassandra or missing configuration somewhere ?

**Comment by vroyer** [comment]
You can set logging level to DEBUG or even TRACE in conf/logback.conf to get more information about any issue in logs/system.log. Would you have some details about your test to reproduce your issue ?
Thanks.

**Comment by loint** [comment]
Thanks @vroyer 
Currently I solved this problem, seems I'm wrong in Cassandra configuration but good to know how to debug it.
