### ISSUE TITLE
Elassandra  - Kibana Issue in creating the index and Visualization

### ISSUE THREAD

**Issue by boycode** [strapdata/elassandra#99]
Hi all , 

We tried integrating the Elassandra(2017-05-22 Release 2.4.5.1 Elasticsearch 2.4.5 + Cassandra 3.0.13
)with Kibana (4..6.4). But We are struggling to with the following issue.

```
 og   [10:01:51.003] [info][listening] Server running at http://XXXXXX:5601
  log   [10:01:55.983] [info][status][plugin:elasticsearch@1.0.0] Status changed from yellow to yellow - No existing Kibana index found
  log   [10:02:00.913] [info][status][plugin:elasticsearch@1.0.0] Status changed from yellow to green - Kibana index ready
  log   [10:02:00.941] [error][status][plugin:elasticsearch@1.0.0] Status changed from green to red - [document_already_exists_exception] [config][4.6.4]: document already exists, with: {"shard":"0","index":"kibana"}
```
```
health status index        pri rep docs.count docs.deleted store.size pri.store.size
green  open   emp            2   0          0            0       142b           142b
green  open   weatherindex   2   0          0            0       142b           142b
green  open   weatherts1     2   0          0            0       142b           142b
green  open   kibana         2   0          0            0       142b           142b
green  open   weatherts      2   0          0            0       142b           142b
```

Can any body please help to solve this issue ?

**Comment by vroyer** [comment]
Hi,

Could you try a kibana restart ?

Thanks,
Vincent.

**Comment by boycode** [comment]
We tried these options . But not working . I guess the return status from elastic search / elassandra is changing it status from yellow to red. : :(

**Comment by DBarthe** [comment]
Hi @boycode,

First of all, is this happening on a multi-nodes cluster ? then have you started multiple kibana instances ? It could be a bug with two kibana instances trying to create the same document.

You may try to stop kibana, delete the .kibana index with:
```
curl -XDELETE X.X.X.X:9200/.kibana
```
then restart kibana.

Inspecting the elassandra logs could also help.
 
Otherwise, Elassandra 2.4.5.3 is the latest official release. you may upgrade and see if you still encounter the problem.

**Comment by vroyer** [comment]
Hi,
Something goes wrong in your configuration, all your ES indices are empty (doc.count = 0).
Could you provide more information about your setup and your logs ?
Thanks.

**Comment by boycode** [comment]
Hi @DBarthe ,

Please see my answers below

First of all, is this happening on a multi-nodes cluster ?
_Yes . Only elassandra running in multinode_ 
 then have you started multiple kibana instances ? 
_No . Only one instance kibana is running_
It could be a bug with two kibana instances trying to create the same document.

I am also building the code in parallel for the version ( 2017-06-17 Release 2.4.5.2 Elasticsearch 2.4.5 + Cassandra 3.10 ) . Since binary for the same is not available and I am directly following the documentation from elassandra that is the reason started with 2017-05-22 Release 2.4.5.1 Elasticsearch 2.4.5 + Cassandra 3.0.13


Hi @vroyer / @DBarthe ,

I also tried with the plain elastic search with Kibana and Graphana . It is working well , able read the index and able to create the visualization as well. So I guess there is something went either wrong withhe configuration of elassandra or may be issue with build.

Elassandra Configuration Details:

**##parameter configuration for cassandra.yaml**

cluster_name: 'TestCluster'
num_tokens: 8
hinted_handoff_enabled: true
max_hint_window_in_ms: 10800000 # 3 hours
hinted_handoff_throttle_in_kb: 1024
max_hints_delivery_threads: 2
hints_flush_period_in_ms: 10000
max_hints_file_size_in_mb: 128
batchlog_replay_throttle_in_kb: 1024
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
role_manager: CassandraRoleManager
roles_validity_in_ms: 2000
permissions_validity_in_ms: 2000
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
disk_failure_policy: stop
commit_failure_policy: stop
key_cache_size_in_mb:
key_cache_save_period: 14400
row_cache_size_in_mb: 0
row_cache_save_period: 0
counter_cache_size_in_mb:
counter_cache_save_period: 7200
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider: - class_name: org.apache.cassandra.locator.SimpleSeedProvider
                                - seeds: "xx.xx.xx.xxx,xx.xx.xx.xxx"
concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32
concurrent_materialized_view_writes: 32
memtable_allocation_type: heap_buffers
index_summary_capacity_in_mb:
index_summary_resize_interval_in_minutes: 60
trickle_fsync: false
trickle_fsync_interval_in_kb: 10240
storage_port: 7000
ssl_storage_port: 7001
listen_address: xx.xx.xx.xxx
start_native_transport: true
native_transport_port: 9042
start_rpc: false
rpc_address: xx.xx.xx.xxx
rpc_port: 9160
rpc_keepalive: true
rpc_server_type: sync
thrift_framed_transport_size_in_mb: 15
incremental_backups: false
snapshot_before_compaction: false
auto_snapshot: true
tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000
column_index_size_in_kb: 64
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
unlogged_batch_across_partitions_warn_threshold: 10
compaction_throughput_mb_per_sec: 16
compaction_large_partition_warning_threshold_mb: 100
sstable_preemptive_open_interval_in_mb: 50
read_request_timeout_in_ms: 5000
range_request_timeout_in_ms: 10000
write_request_timeout_in_ms: 5000
counter_write_request_timeout_in_ms: 5000
cas_contention_timeout_in_ms: 1000
truncate_request_timeout_in_ms: 60000
request_timeout_in_ms: 10000
cross_node_timeout: false
endpoint_snitch: GossipingPropertyFileSnitch
dynamic_snitch_update_interval_in_ms: 100
dynamic_snitch_reset_interval_in_ms: 600000
dynamic_snitch_badness_threshold: 0.1
request_scheduler: org.apache.cassandra.scheduler.NoScheduler
server_encryption_options:
    internode_encryption: none
    keystore: conf/.keystore
    keystore_password: cassandra
    truststore: conf/.truststore
    truststore_password: cassandra
    # More advanced defaults below:
    # protocol: TLS
    # algorithm: SunX509
    # store_type: JKS
    # cipher_suites: [TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]
client_encryption_options:
    enabled: false
    # If enabled and optional is set to true encrypted and unencrypted connections are handled.
    optional: false
    keystore: conf/.keystore
    keystore_password: cassandra
internode_compression: all
inter_dc_tcp_nodelay: false
tracetype_query_ttl: 86400
tracetype_repair_ttl: 604800
gc_warn_threshold_in_ms: 1000
enable_user_defined_functions: false
enable_scripted_user_defined_functions: false
windows_timer_interval: 1

**#parameter configuration for elasticsearch.yml**

cluster.name: TestCluster
path.data: /datadrive/software/elassandra/elasticIndexData
path.logs: /datadrive/software/elassandra/elasticLogs
network.host: XX.XXX.XXX.118
http.port: 9200


**#parameter configuration for kibana.yml**



server.port: 5601
server.host: "xx.xx.xx.xxx"
elasticsearch.url: "http://xx.xx.xx.xxx:9200"
kibana.index: "kibana"

Attaching the Log

[system.txt](https://github.com/strapdata/elassandra/files/1124034/system.txt)

Looking forward your help on this.

Thanks,
Boycode

**Comment by boycode** [comment]
Dear @DBarthe / @vroyer 

We tried with Latest build : 2.4.5.2 Elasticsearch 2.4.5 + Cassandra 3.10.
It is working , so I guess issue is with (2017-05-22 Release 2.4.5.1 Elasticsearch 2.4.5 + Cassandra 3.0.13 ).

Will update the progress , now the whole setup in single instance . Started trying in parallel clusters.

Thanks,
Boycode

**Comment by DBarthe** [comment]
Good to hear that.

Actually we provided a [pre-compiled release](https://github.com/strapdata/elassandra/releases/tag/v2.4.5.3) for v2.4.5.3, available from the "releases" tab of the repository, in case you did not notice it (README isn't up-to-date).

Let us know if you have any question or problem using Elassandra.

**Comment by boycode** [comment]
Thanks @DBarthe  . Readme is not updated :) 👍
